export enum FractionTypeEnum {
  StoreFraction = 'StoreFraction',
  //
  StringIsAnyValue = 'StringIsAnyValue',

  StringIsLike = 'StringIsLike',
  StringIsEqualTo = 'StringIsEqualTo',
  StringContains = 'StringContains',
  StringStartsWith = 'StringStartsWith',
  StringEndsWith = 'StringEndsWith',
  StringIsNull = 'StringIsNull',
  StringIsBlank = 'StringIsBlank',

  StringIsNotLike = 'StringIsNotLike',
  StringIsNotEqualTo = 'StringIsNotEqualTo',
  StringDoesNotContain = 'StringDoesNotContain',
  StringDoesNotStartWith = 'StringDoesNotStartWith',
  StringDoesNotEndWith = 'StringDoesNotEndWith',
  StringIsNotNull = 'StringIsNotNull',
  StringIsNotBlank = 'StringIsNotBlank',

  NumberIsAnyValue = 'NumberIsAnyValue',

  NumberIsEqualTo = 'NumberIsEqualTo',
  NumberIsGreaterThan = 'NumberIsGreaterThan',
  NumberIsGreaterThanOrEqualTo = 'NumberIsGreaterThanOrEqualTo',
  NumberIsLessThan = 'NumberIsLessThan',
  NumberIsLessThanOrEqualTo = 'NumberIsLessThanOrEqualTo',
  NumberIsBetween = 'NumberIsBetween',
  NumberIsNull = 'NumberIsNull',

  NumberIsNotEqualTo = 'NumberIsNotEqualTo',
  NumberIsNotBetween = 'NumberIsNotBetween',
  NumberIsNotNull = 'NumberIsNotNull',

  BooleanIsAnyValue = 'BooleanIsAnyValue',

  BooleanIsTrue = 'BooleanIsTrue',
  BooleanIsFalse = 'BooleanIsFalse',
  BooleanIsFalseOrNull = 'BooleanIsFalseOrNull',
  BooleanIsNull = 'BooleanIsNull',

  BooleanIsNotTrue = 'BooleanIsNotTrue',
  BooleanIsNotFalse = 'BooleanIsNotFalse',
  BooleanIsNotFalseOrNull = 'BooleanIsNotFalseOrNull',
  BooleanIsNotNull = 'BooleanIsNotNull',

  YesnoIs = 'YesnoIs',
  YesnoIsAnyValue = 'YesnoIsAnyValue',

  DayOfWeekIs = 'DayOfWeekIs',
  DayOfWeekIsNull = 'DayOfWeekIsNull',
  DayOfWeekIsAnyValue = 'DayOfWeekIsAnyValue',
  DayOfWeekIsNot = 'DayOfWeekIsNot',
  DayOfWeekIsNotNull = 'DayOfWeekIsNotNull',
  DayOfWeekIndexIsEqualTo = 'DayOfWeekIndexIsEqualTo',
  DayOfWeekIndexIsNull = 'DayOfWeekIndexIsNull',
  DayOfWeekIndexIsAnyValue = 'DayOfWeekIndexIsAnyValue',
  DayOfWeekIndexIsNotEqualTo = 'DayOfWeekIndexIsNotEqualTo',
  DayOfWeekIndexIsNotNull = 'DayOfWeekIndexIsNotNull',
  MonthNameIs = 'MonthNameIs',
  MonthNameIsNull = 'MonthNameIsNull',
  MonthNameIsAnyValue = 'MonthNameIsAnyValue',
  MonthNameIsNot = 'MonthNameIsNot',
  MonthNameIsNotNull = 'MonthNameIsNotNull',
  QuarterOfYearIs = 'QuarterOfYearIs',
  QuarterOfYearIsNull = 'QuarterOfYearIsNull',
  QuarterOfYearIsAnyValue = 'QuarterOfYearIsAnyValue',
  QuarterOfYearIsNot = 'QuarterOfYearIsNot',
  QuarterOfYearIsNotNull = 'QuarterOfYearIsNotNull',
  TsIsOnMinute = 'TsIsOnMinute',
  TsIsOnHour = 'TsIsOnHour',
  TsIsOnDay = 'TsIsOnDay',
  TsIsOnMonth = 'TsIsOnMonth',
  TsIsOnYear = 'TsIsOnYear',
  TsIsInRange = 'TsIsInRange',
  TsIsBeforeDate = 'TsIsBeforeDate',
  TsIsAfterDate = 'TsIsAfterDate',
  TsIsBeforeRelative = 'TsIsBeforeRelative',
  TsIsAfterRelative = 'TsIsAfterRelative',
  TsIsInLast = 'TsIsInLast',
  TsIsNull = 'TsIsNull',
  TsIsAnyValue = 'TsIsAnyValue',

  TsIsNotNull = 'TsIsNotNull'
}
