export enum ParameterEnum {
  Name = 'name',
  Path = 'path',
  Ext = 'ext',
  //
  FieldClass = 'fieldClass',
  //
  WeekStart = 'week_start',
  DefaultTimezone = 'default_timezone',
  AllowTimezones = 'allow_timezones',
  CaseSensitiveStringFilters = 'case_sensitive_string_filters',
  SimplifySafeAggregates = 'simplify_safe_aggregates',
  //
  AccessRoles = 'access_roles',
  AccessUsers = 'access_users',
  AlwaysJoin = 'always_join',
  As = 'as',
  BuildMetrics = 'build_metrics',
  Calculation = 'calculation',
  Connection = 'connection',
  CurrencyPrefix = 'currency_prefix',
  CurrencySuffix = 'currency_suffix',
  Dashboard = 'dashboard',
  DerivedTable = 'derived_table',
  Dimension = 'dimension',
  Description = 'description',
  Fields = 'fields',
  Filter = 'filter',
  MaxFractions = 'max_fractions',
  ShowIf = 'show_if',
  Required = 'required',
  Or = 'or',
  AndNot = 'and_not',
  Meta = 'meta',
  Controls = 'controls',
  FractionControls = 'fraction_controls',
  Fractions = 'fractions',
  ApplyTo = 'apply_to',
  FormatNumber = 'format_number',
  Formula = 'formula',
  FromView = 'from_view',
  JoinView = 'join_view',
  Group = 'group',
  GroupLabel = 'group_label',
  GroupDescription = 'group_description',
  Hidden = 'hidden',
  HideFields = 'hide_fields',
  Joins = 'joins',
  Label = 'label',
  Limit = 'limit',
  Listen = 'listen',
  Measure = 'measure',

  Model = 'model',
  MproveDir = 'mprove_dir',
  Percentile = 'percentile',
  Report = 'report',
  Tiles = 'tiles',
  Result = 'result',
  FractionTypes = 'fraction_types',
  SuggestModelDimension = 'suggest_model_dimension',
  Rows = 'rows',
  Select = 'select',

  Input = 'input',
  ListInput = 'list_input',
  Switch = 'switch',
  DatePicker = 'date_picker',
  Selector = 'selector',
  Value = 'value',

  Relationship = 'relationship',
  ShowFields = 'show_fields',
  Sorts = 'sorts',
  Source = 'source',
  Sql = 'sql',
  SqlAlwaysWhere = 'sql_always_where',
  SqlAlwaysWhereCalc = 'sql_always_where_calc',
  SqlKey = 'sql_key',
  SqlOn = 'sql_on',
  SqlWhere = 'sql_where',
  Table = 'table',
  Time = 'time',
  Details = 'details',
  Unit = 'unit',
  Timeframes = 'timeframes',
  Title = 'title',
  Type = 'type',
  Udf = 'udf',
  Udfs = 'udfs',
  Unnest = 'unnest',
  View = 'view',
  Store = 'store',
  Method = 'method',
  UrlPath = 'url_path',
  Body = 'body',
  Response = 'response',
  Results = 'results',
  FieldGroups = 'field_groups',
  Chart = 'chart',
  // row
  Parameters = 'parameters',
  ParametersFormula = 'parameters_formula',
  RowId = 'row_id',
  Metric = 'metric',
  ShowChart = 'show_chart',
  // parameter
  Conditions = 'conditions',
  // chart axis
  Data = 'data',
  Options = 'options',
  Plate = 'plate',
  // chart data
  HideColumns = 'hide_columns',
  XField = 'x_field',
  YFields = 'y_fields',
  SizeField = 'size_field',
  MultiField = 'multi_field',
  // chart options
  Format = 'format',
  PageSize = 'page_size',
  XAxis = 'x_axis',
  YAxis = 'y_axis',
  Series = 'series',
  // x_axis, y_axis
  Scale = 'scale',
  // series
  DataField = 'data_field',
  DataRowId = 'data_row_id',
  YAxisIndex = 'y_axis_index',
  //
  // ShowDataLabel = 'show_data_label',
  // Gradient = 'gradient',
  // Legend = 'legend',
  // TooltipDisabled = 'tooltip_disabled',
  // RoundDomains = 'round_domains',
  // ShowGridLines = 'show_grid_lines',
  // Timeline = 'timeline',
  // AutoScale = 'auto_scale',
  // Doughnut = 'doughnut',
  // ExplodeSlices = 'explode_slices',
  // Labels = 'labels',
  // ColorScheme = 'color_scheme',
  // SchemeType = 'scheme_type',
  // ArcWidth = 'arc_width',
  // BarPadding = 'bar_padding',
  // GroupPadding = 'group_padding',
  // InnerPadding = 'inner_padding',
  // RangeFillOpacity = 'range_fill_opacity',
  // AngleSpan = 'angle_span',
  // StartAngle = 'start_angle',
  // BigSegments = 'big_segments',
  // SmallSegments = 'small_segments',
  // Min = 'min',
  // Max = 'max',
  // Units = 'units',
  // BandColor = 'band_color',
  // CardColor = 'card_color',
  // TextColor = 'text_color',
  // EmptyColor = 'empty_color',
  // Animations = 'animations',
  // LegendTitle = 'legend_title',
  // RoundEdges = 'round_edges',
  // Interpolation = 'interpolation',
  // XScaleMax = 'x_scale_max',
  // YScaleMin = 'y_scale_min',
  // YScaleMax = 'y_scale_max',
  // FormatNumberDataLabel = 'format_number_data_label',
  // FormatNumberValue = 'format_number_value',
  // FormatNumberAxisTick = 'format_number_axis_tick',
  // FormatNumberYAxisTick = 'format_number_y_axis_tick',
  // FormatNumberXAxisTick = 'format_number_x_axis_tick',
  //
  // chart plate
  PlateWidth = 'plate_width',
  PlateHeight = 'plate_height',
  PlateX = 'plate_x',
  PlateY = 'plate_y'
}
