version: v2beta1
name: mprove
pipelines:
  dev:
    run: start_dev --all
dev:
  # db:
  #   labelSelector:
  #     app: db
  #   ports:
  #     - port: '3306'

  # rabbit:
  #   labelSelector:
  #     app: rabbit
  #   ports:
  #     - port: '5672'

  # frontnode:
  #   labelSelector:
  #     app: frontnode
  #   # ports:
  #   #   - port: '4200'
  #   sync:
  #     - path: ./apps/front
  #     - path: ./libs
  #       excludePaths:
  #       - ./libs/api-to-blockml
  #       - ./libs/api-to-disk
  #       - ./libs/node-common

  disk:
    labelSelector:
      app: disk
    # ports:
    #   - port: '9230:9229'
    sync:
      - path: ./dist/apps/disk
        initialSync: preferRemote
      - path: ./apps/disk
      - path: ./libs
        excludePaths:
        - ./libs/api-to-blockml
        - ./libs/api-to-backend

  backend:
    labelSelector:
      app: backend
    # ports:
    #   - port: '9231:9229'
    #   - port: '3000:3000'
    sync:
      - path: ./apps/backend
      - path: ./libs
      - path: ./dist/apps/backend
        initialSync: preferRemote    

  backend-scheduler:
    labelSelector:
      app: backend-scheduler
    # ports:
    #   - port: '9232:9229'
    sync:
      - path: ./apps/backend
      - path: ./libs
      # - path: ./dist/apps/backend
      #   initialSync: preferRemote

  # blockml-single:
  #   labelSelector:
  #     app: blockml-single
  #   # ports:
  #   #   - port: '9233:9229'
  #   sync:
  #     - path: ./apps/blockml
  #     - path: ./libs
  #       excludePaths:
  #       - ./libs/api-to-backend
  #       - ./libs/api-to-disk
  #     - path: ./dist/apps/blockml
  #       initialSync: preferRemote    

  # blockml-main:
  #   labelSelector:
  #     app: blockml-main
  #   # ports:
  #   #   - port: '9234:9229'
  #   sync:
  #     - path: ./apps/blockml
  #     - path: ./libs
  #       excludePaths:
  #       - ./libs/api-to-backend
  #       - ./libs/api-to-disk
  #     # - path: ./dist/apps/blockml
  #     #   initialSync: preferRemote     

  # blockml-worker:
  #   labelSelector:
  #     app: blockml-worker
  #   # ports:
  #   #   - port: '9235:9229'
  #   sync:
  #     - path: ./apps/blockml
  #     - path: ./libs
  #       excludePaths:
  #       - ./libs/api-to-backend
  #       - ./libs/api-to-disk
  #     # - path: ./dist/apps/blockml
  #     #   initialSync: preferRemote  

  blockml-main-worker:
    labelSelector:
      app: blockml-main-worker
    # ports:
    #   - port: '9236:9229'
    sync:
      - path: ./apps/blockml
      - path: ./libs
        excludePaths:
        - ./libs/api-to-backend
        - ./libs/api-to-disk
      # - path: ./dist/apps/blockml
      #   initialSync: preferRemote  
     


