packages:
  - '.' 

ignoredBuiltDependencies:
  - '@vaadin/vaadin-usage-statistics'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@parcel/watcher'
  - bcrypt
  - duckdb
  - esbuild
  - husky
  - isolated-vm
  - lmdb
  - msgpackr-extract
  - nodegit
  - nx
  - protobufjs
