packages:
  - apps/*
  - libs/*

catalog:
  '@acrodata/code-editor': 0.5.1
  '@ali-hm/angular-tree-component': 21.0.3
  '@angular-devkit/build-angular': 21.1.0
  '@angular-devkit/core': 21.1.0
  '@angular-devkit/schematics': 21.1.0
  '@angular/animations': 21.1.0
  '@angular/build': 21.1.0
  '@angular/cdk': 21.1.0
  '@angular/cli': 21.1.0
  '@angular/common': 21.1.0
  '@angular/compiler': 21.1.0
  '@angular/compiler-cli': 21.1.0
  '@angular/core': 21.1.0
  '@angular/forms': 21.1.0
  '@angular/language-service': 21.1.0
  '@angular/platform-browser': 21.1.0
  '@angular/platform-browser-dynamic': 21.1.0
  '@angular/router': 21.1.0
  '@auth0/angular-jwt': 5.2.0
  '@biomejs/biome': 2.3.12
  '@codemirror/commands': 6.10.0
  '@codemirror/language': 6.11.3
  '@codemirror/language-data': 6.5.1
  '@codemirror/lint': 6.9.2
  '@codemirror/search': 6.5.11
  '@codemirror/state': 6.5.2
  '@codemirror/view': 6.36.7
  '@duckdb/node-api': 1.4.3-r.1
  '@google-cloud/bigquery': 5.12.0
  '@katoid/angular-grid-layout': 3.1.0
  '@kubiks/otel-drizzle': 2.1.0
  '@leeoniya/ufuzzy': 1.0.18
  '@lezer/highlight': 1.2.3
  '@malloydata/db-bigquery': 0.0.335
  '@malloydata/db-duckdb': 0.0.335
  '@malloydata/db-mysql': 0.0.335
  '@malloydata/db-postgres': 0.0.335
  '@malloydata/db-snowflake': 0.0.335
  '@malloydata/db-trino': 0.0.335
  '@malloydata/malloy': 0.0.335
  '@malloydata/malloy-filter': 0.0.335
  '@malloydata/malloy-interfaces': 0.0.335
  '@malloydata/malloy-query-builder': 0.0.335
  '@malloydata/malloy-tag': 0.0.335
  '@malloydata/render': 0.0.335
  '@nest-lab/throttler-storage-redis': 1.1.0
  '@nestjs/common': 11.1.0
  '@nestjs/config': 3.0.1
  '@nestjs/core': 11.1.0
  '@nestjs/jwt': 11.0.0
  '@nestjs/passport': 11.0.5
  '@nestjs/platform-express': 11.1.0
  '@nestjs/schedule': 4.1.1
  '@nestjs/testing': 11.1.0
  '@nestjs/throttler': 6.4.0
  '@ng-select/ng-select': 21.1.3
  '@ngneat/dialog': 5.1.2
  '@ngneat/elf': 2.5.1
  '@ngneat/helipopper': 12.1.0
  '@ngneat/overview': 7.0.0
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/auto-instrumentations-node': 0.67.2
  '@opentelemetry/auto-instrumentations-web': 0.54.0
  '@opentelemetry/context-zone': 2.2.0
  '@opentelemetry/core': 2.2.0
  '@opentelemetry/exporter-metrics-otlp-http': 0.208.0
  '@opentelemetry/exporter-trace-otlp-http': 0.208.0
  '@opentelemetry/instrumentation': 0.208.0
  '@opentelemetry/resources': 2.2.0
  '@opentelemetry/sdk-metrics': 2.2.0
  '@opentelemetry/sdk-node': 0.208.0
  '@opentelemetry/sdk-trace-base': 2.2.0
  '@opentelemetry/sdk-trace-web': 2.2.0
  '@opentelemetry/semantic-conventions': 1.38.0
  '@prestodb/presto-js-client': 1.1.0
  '@replit/codemirror-indentation-markers': 6.5.3
  '@schematics/angular': 21.1.0
  '@swc-node/register': 1.11.1
  '@swc/cli': 0.7.10
  '@swc/core': 1.15.11
  '@swc/helpers': 0.5.18
  '@tailwindcss/aspect-ratio': 0.4.2
  '@tailwindcss/forms': 0.4.1
  '@tailwindcss/typography': 0.5.9
  '@tweenjs/tween.js': 18.6.4
  '@types/async-retry': 1.4.9
  '@types/bcrypt': 3.0.1
  '@types/body-parser': 1.19.6
  '@types/codemirror': 5.60.15
  '@types/bun': 1.3.8
  '@types/cron': 1.7.3
  '@types/d3-format': 2.0.5
  '@types/d3-shape': 3.1.6
  '@types/express': 4.17.21
  '@types/fs-extra': 9.0.13
  '@types/js-yaml': 4.0.9
  '@types/json-schema': 7.0.15
  '@types/lodash-es': 4.17.6
  '@types/luxon': 2.4.0
  '@types/node': 22.7.5
  '@types/nodemailer': 7.0.4
  '@types/passport-jwt': 3.0.13
  '@types/passport-local': 1.0.38
  '@types/pg': 8.11.10
  '@types/retry': 0.12.5
  '@types/snowflake-sdk': 1.6.24
  '@types/sshpk': 1.17.4
  '@types/supertest': 6.0.3
  '@types/throttle-debounce': 5.0.0
  '@types/tiny-async-pool': 1.0.5
  '@types/walk': 2.3.4
  '@vaadin/date-picker': 23.5.3
  '@vaadin/time-picker': 23.5.3
  ag-grid-angular: 33.3.0
  ag-grid-community: 33.3.0
  async-retry: 1.3.3
  autoprefixer: 10.4.20
  ava: 6.4.1
  axios: 1.13.1
  bcrypt: 5.1.1
  body-parser: 2.2.1
  class-transformer: 0.3.1
  class-transformer-validator: 0.9.1
  class-validator: 0.14.2
  clipanion: 3.2.1
  cross-env: 7.0.3
  d3-format: 1.4.5
  d3-shape: 3.2.0
  date-fns: 4.1.0
  date-fns-tz: 3.2.0
  dayjs: 1.11.19
  dotenv: 17.2.3
  dotenv-cli: 11.0.0
  drizzle-kit: 0.27.1
  drizzle-orm: 0.36.0
  echarts: 5.5.1
  esbuild: 0.24.0
  express: 5.1.0
  fast-deep-equal: 3.1.3
  fs-extra: 11.2.0
  google-auth-library: 9.15.1
  groupmq: 1.1.0
  hammerjs: 2.0.8
  husky: 9.1.7
  ioredis: 5.8.2
  ipaddr.js: 2.3.0
  isolated-vm: 6.0.2
  js-yaml: 4.1.1
  license-checker: 25.0.1
  lint-staged: 16.2.6
  lodash-es: 4.17.21
  luxon: 2.5.2
  madge: 8.0.0
  mysql2: 3.11.3
  nanoid: 3.3.10
  neoip: 3.0.1
  nest-winston: 1.9.4
  ngx-color: 10.1.0
  ngx-echarts: 21.0.0
  ngx-image-compress: 18.1.5
  ngx-image-cropper: 9.1.5
  ngx-pagination: 6.0.3
  ngx-scrollbar: 19.1.1
  ngx-spinner: 21.0.0
  ngx-ui-switch: 16.1.0
  nodemailer: 7.0.11
  p-iteration: 1.1.8
  passport: 0.7.0
  passport-jwt: 4.0.1
  passport-local: 1.0.0
  pg: 8.13.0
  pg-promise: 11.10.1
  prettier: 3.3.3
  prettier-plugin-tailwindcss: 0.6.11
  prettyjson: 1.2.5
  reflect-metadata: 0.2.2
  retry: 0.13.1
  rimraf: 6.0.1
  rxjs: 7.8.1
  serve: 14.2.5
  shiki: 0.10.1
  shx: 0.4.0
  simple-git: 3.30.0
  snowflake-sdk: 2.3.1
  ssf: 0.11.2
  sshpk: 1.18.0
  supertest: 7.1.4
  tailwindcss: 3.4.14
  throttle-debounce: 5.0.0
  tiny-async-pool: 1.3.0
  tippy.js: 6.3.7
  toposort: 2.0.2
  trino-client: 0.2.9
  ts-loader: 9.5.1
  ts-node: 10.9.2
  tsconfig-paths: 3.14.2
  tslib: 2.7.0
  turbo: 2.7.6
  typanion: 3.14.0
  typescript: 5.9.2
  uuid: 11.1.0
  vscode-oniguruma: 1.7.0
  vscode-textmate: 9.2.0
  walk: 2.3.15
  winston: 3.14.2
  zone.js: 0.16.0

ignoredBuiltDependencies:
  - '@vaadin/vaadin-usage-statistics'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bcrypt
  - duckdb
  - esbuild
  - husky
  - isolated-vm
  - lmdb
  - msgpackr-extract
  - protobufjs
