import { enums } from '~api-to-backend/barrels/enums';
import * as interfaces from '~api-to-backend/interfaces/_index';

export const nameToClass = {
  [enums.ToBackendRequestInfoNameEnum.ToBackendSpecialRebuildStructs]:
    interfaces.ToBackendSpecialRebuildStructsRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetRebuildStruct]:
    interfaces.ToBackendGetRebuildStructRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSeedRecords]:
    interfaces.ToBackendSeedRecordsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteRecords]:
    interfaces.ToBackendDeleteRecordsRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendCompleteUserRegistration]:
    interfaces.ToBackendCompleteUserRegistrationRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendConfirmUserEmail]:
    interfaces.ToBackendConfirmUserEmailRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetUserProfile]:
    interfaces.ToBackendGetUserProfileRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendLoginUser]:
    interfaces.ToBackendLoginUserRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendLogoutUser]:
    interfaces.ToBackendLogoutUserRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendRegisterUser]:
    interfaces.ToBackendRegisterUserRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendResendUserEmail]:
    interfaces.ToBackendResendUserEmailRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetUserName]:
    interfaces.ToBackendSetUserNameRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetUserUi]:
    interfaces.ToBackendSetUserUiRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendResetUserPassword]:
    interfaces.ToBackendResetUserPasswordRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendUpdateUserPassword]:
    interfaces.ToBackendUpdateUserPasswordRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteUser]:
    interfaces.ToBackendDeleteUserRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateOrg]:
    interfaces.ToBackendCreateOrgRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetOrgsList]:
    interfaces.ToBackendGetOrgsListRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetOrg]:
    interfaces.ToBackendGetOrgRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendIsOrgExist]:
    interfaces.ToBackendIsOrgExistRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetOrgInfo]:
    interfaces.ToBackendSetOrgInfoRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetOrgOwner]:
    interfaces.ToBackendSetOrgOwnerRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteOrg]:
    interfaces.ToBackendDeleteOrgRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGenerateProjectRemoteKey]:
    interfaces.ToBackendGenerateProjectRemoteKeyRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateProject]:
    interfaces.ToBackendCreateProjectRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendIsProjectExist]:
    interfaces.ToBackendIsProjectExistRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetProject]:
    interfaces.ToBackendGetProjectRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetProjectTimezone]:
    interfaces.ToBackendSetProjectTimezoneRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetProjectWeekStart]:
    interfaces.ToBackendSetProjectWeekStartRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetProjectAllowTimezones]:
    interfaces.ToBackendSetProjectAllowTimezonesRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetProjectsList]:
    interfaces.ToBackendGetProjectsListRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteProject]:
    interfaces.ToBackendDeleteProjectRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetProjectInfo]:
    interfaces.ToBackendSetProjectInfoRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetEnvsList]:
    interfaces.ToBackendGetEnvsListRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetEnvs]:
    interfaces.ToBackendGetEnvsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateEnv]:
    interfaces.ToBackendCreateEnvRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateEnvVar]:
    interfaces.ToBackendCreateEnvVarRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateEnvUser]:
    interfaces.ToBackendCreateEnvUserRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendEditEnvVar]:
    interfaces.ToBackendEditEnvVarRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteEnv]:
    interfaces.ToBackendDeleteEnvRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteEnvVar]:
    interfaces.ToBackendDeleteEnvVarRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteEnvUser]:
    interfaces.ToBackendDeleteEnvUserRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendEditEnvFallbacks]:
    interfaces.ToBackendEditEnvFallbacksRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetMembers]:
    interfaces.ToBackendGetMembersRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetMembersList]:
    interfaces.ToBackendGetMembersListRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateMember]:
    interfaces.ToBackendCreateMemberRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendEditMember]:
    interfaces.ToBackendEditMemberRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteMember]:
    interfaces.ToBackendDeleteMemberRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetOrgUsers]:
    interfaces.ToBackendGetOrgUsersRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetConnections]:
    interfaces.ToBackendGetConnectionsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateConnection]:
    interfaces.ToBackendCreateConnectionRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteConnection]:
    interfaces.ToBackendDeleteConnectionRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendEditConnection]:
    interfaces.ToBackendEditConnectionRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetBranchesList]:
    interfaces.ToBackendGetBranchesListRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendIsBranchExist]:
    interfaces.ToBackendIsBranchExistRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateBranch]:
    interfaces.ToBackendCreateBranchRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteBranch]:
    interfaces.ToBackendDeleteBranchRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetRepo]:
    interfaces.ToBackendGetRepoRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCommitRepo]:
    interfaces.ToBackendCommitRepoRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendPushRepo]:
    interfaces.ToBackendPushRepoRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendPullRepo]:
    interfaces.ToBackendPullRepoRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendRevertRepoToLastCommit]:
    interfaces.ToBackendRevertRepoToLastCommitRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendRevertRepoToRemote]:
    interfaces.ToBackendRevertRepoToRemoteRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendMergeRepo]:
    interfaces.ToBackendMergeRepoRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSyncRepo]:
    interfaces.ToBackendSyncRepoRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetStruct]:
    interfaces.ToBackendGetStructRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendMoveCatalogNode]:
    interfaces.ToBackendMoveCatalogNodeRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendRenameCatalogNode]:
    interfaces.ToBackendRenameCatalogNodeRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateFolder]:
    interfaces.ToBackendCreateFolderRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteFolder]:
    interfaces.ToBackendDeleteFolderRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetFile]:
    interfaces.ToBackendGetFileRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateFile]:
    interfaces.ToBackendCreateFileRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteFile]:
    interfaces.ToBackendDeleteFileRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSaveFile]:
    interfaces.ToBackendSaveFileRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendValidateFiles]:
    interfaces.ToBackendValidateFilesRequest,
  //

  [enums.ToBackendRequestInfoNameEnum.ToBackendGetSuggestFields]:
    interfaces.ToBackendGetSuggestFieldsRequest,

  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetModels]:
    interfaces.ToBackendGetModelsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetModel]:
    interfaces.ToBackendGetModelRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateDraftChart]:
    interfaces.ToBackendCreateDraftChartRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteChart]:
    interfaces.ToBackendDeleteChartRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteDraftCharts]:
    interfaces.ToBackendDeleteDraftChartsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendEditDraftChart]:
    interfaces.ToBackendEditDraftChartRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetChart]:
    interfaces.ToBackendGetChartRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetCharts]:
    interfaces.ToBackendGetChartsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSaveCreateChart]:
    interfaces.ToBackendSaveCreateChartRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSaveModifyChart]:
    interfaces.ToBackendSaveModifyChartRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateDraftDashboard]:
    interfaces.ToBackendCreateDraftDashboardRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteDashboard]:
    interfaces.ToBackendDeleteDashboardRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteDraftDashboards]:
    interfaces.ToBackendDeleteDraftDashboardsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendEditDraftDashboard]:
    interfaces.ToBackendEditDraftDashboardRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetDashboard]:
    interfaces.ToBackendGetDashboardRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetDashboards]:
    interfaces.ToBackendGetDashboardsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSaveCreateDashboard]:
    interfaces.ToBackendSaveCreateDashboardRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSaveModifyDashboard]:
    interfaces.ToBackendSaveModifyDashboardRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateDraftReport]:
    interfaces.ToBackendCreateDraftReportRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteReport]:
    interfaces.ToBackendDeleteReportRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDeleteDraftReports]:
    interfaces.ToBackendDeleteDraftReportsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendEditDraftReport]:
    interfaces.ToBackendEditDraftReportRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetReport]:
    interfaces.ToBackendGetReportRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetReports]:
    interfaces.ToBackendGetReportsRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSaveCreateReport]:
    interfaces.ToBackendSaveCreateReportRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSaveModifyReport]:
    interfaces.ToBackendSaveModifyReportRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetMconfig]:
    interfaces.ToBackendGetMconfigRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateTempMconfig]:
    interfaces.ToBackendCreateTempMconfigRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCreateTempMconfigAndQuery]:
    interfaces.ToBackendCreateTempMconfigAndQueryRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendDuplicateMconfigAndQuery]:
    interfaces.ToBackendDuplicateMconfigAndQueryRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetQueries]:
    interfaces.ToBackendGetQueriesRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetQuery]:
    interfaces.ToBackendGetQueryRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendRunQueries]:
    interfaces.ToBackendRunQueriesRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendRunQueriesDry]:
    interfaces.ToBackendRunQueriesDryRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendCancelQueries]:
    interfaces.ToBackendCancelQueriesRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetNav]:
    interfaces.ToBackendGetNavRequest,
  //
  [enums.ToBackendRequestInfoNameEnum.ToBackendGetAvatarBig]:
    interfaces.ToBackendGetAvatarBigRequest,
  [enums.ToBackendRequestInfoNameEnum.ToBackendSetAvatar]:
    interfaces.ToBackendSetAvatarRequest
};
