export enum ChartTypeEnum {
  Table = 'table',
  // if remove _ then check for split('_') in code
  ELine = 'e_line',
  EBar = 'e_bar',
  EScatter = 'e_scatter',
  EBubble = 'e_effect_scatter',
  EPie = 'e_pie',
  EHeatMap = 'e_heatmap',
  ETreeMap = 'e_treemap',
  EGauge = 'e_gauge',
  // ERadar = 'e_radar',
  //
  AgLine = 'ag_line',
  AgBar = 'ag_bar',
  AgArea = 'ag_area',
  AgScatter = 'ag_scatter',
  AgBubble = 'ag_bubble',
  AgPie = 'ag_pie',
  AgDonut = 'ag_donut',
  //
  BarVertical = 'bar_vertical',
  BarVerticalGrouped = 'bar_vertical_grouped',
  BarVerticalStacked = 'bar_vertical_stacked',
  BarVerticalNormalized = 'bar_vertical_normalized',
  BarHorizontal = 'bar_horizontal',
  BarHorizontalGrouped = 'bar_horizontal_grouped',
  BarHorizontalStacked = 'bar_horizontal_stacked',
  BarHorizontalNormalized = 'bar_horizontal_normalized',
  Pie = 'pie',
  PieAdvanced = 'pie_advanced',
  PieGrid = 'pie_grid',
  Line = 'line',
  Area = 'area',
  AreaStacked = 'area_stacked',
  AreaNormalized = 'area_normalized',
  HeatMap = 'heat_map',
  TreeMap = 'tree_map',
  NumberCard = 'number_card',
  Gauge = 'gauge',
  GaugeLinear = 'gauge_linear'
}
