export enum ErEnum {
  //
  M_BACKEND_ORGANIZATION_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP = 'M_BACKEND_ORGANIZATION_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP',
  M_BACKEND_PROJECT_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP = 'M_BACKEND_PROJECT_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP',
  //
  M_DISK_WRONG_REQUEST_INFO_NAME = 'M_DISK_WRONG_REQUEST_INFO_NAME',

  M_DISK_ORGANIZATION_ALREADY_EXIST = 'M_DISK_ORGANIZATION_ALREADY_EXIST',
  M_DISK_ORGANIZATION_IS_NOT_EXIST = 'M_DISK_ORGANIZATION_IS_NOT_EXIST',

  M_DISK_PROJECT_ALREADY_EXIST = 'M_DISK_PROJECT_ALREADY_EXIST',
  M_DISK_PROJECT_IS_NOT_EXIST = 'M_DISK_PROJECT_IS_NOT_EXIST',

  M_DISK_REPO_ALREADY_EXIST = 'M_DISK_REPO_ALREADY_EXIST',
  M_DISK_REPO_IS_NOT_EXIST = 'M_DISK_REPO_IS_NOT_EXIST',

  M_DISK_REPO_IS_NOT_CLEAN_FOR_CHECKOUT_BRANCH = 'M_DISK_REPO_IS_NOT_CLEAN_FOR_CHECKOUT_BRANCH',
  M_DISK_REPO_STATUS_IS_NOT_NEED_PUSH = 'M_DISK_REPO_STATUS_IS_NOT_NEED_PUSH',

  M_DISK_BRANCH_ALREADY_EXIST = 'M_DISK_BRANCH_ALREADY_EXIST',
  M_DISK_BRANCH_IS_NOT_EXIST = 'M_DISK_BRANCH_IS_NOT_EXIST',
  M_DISK_BRANCH_MASTER_CAN_NOT_BE_DELETED = 'M_DISK_BRANCH_MASTER_CAN_NOT_BE_DELETED',

  M_DISK_NEW_PATH_ALREADY_EXIST = 'M_DISK_NEW_PATH_ALREADY_EXIST',
  M_DISK_TO_PATH_ALREADY_EXIST = 'M_DISK_TO_PATH_ALREADY_EXIST',

  M_DISK_PARENT_PATH_IS_NOT_EXIST = 'M_DISK_PARENT_PATH_IS_NOT_EXIST',
  M_DISK_FROM_PATH_IS_NOT_EXIST = 'M_DISK_FROM_PATH_IS_NOT_EXIST',
  M_DISK_OLD_PATH_IS_NOT_EXIST = 'M_DISK_OLD_PATH_IS_NOT_EXIST',

  M_DISK_FOLDER_ALREADY_EXIST = 'M_DISK_FOLDER_ALREADY_EXIST',
  M_DISK_FOLDER_IS_NOT_EXIST = 'M_DISK_FOLDER_IS_NOT_EXIST',

  M_DISK_FILE_ALREADY_EXIST = 'M_DISK_FILE_ALREADY_EXIST',
  M_DISK_FILE_IS_NOT_EXIST = 'M_DISK_FILE_IS_NOT_EXIST'
}
