

# DOMAIN
export DOMAIN="http://localhost:8080"
#export DOMAIN="https://dev.mprove.io"
#export DOMAIN="https://arhar.online"

export BEARER="Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1EazNNamc1TlRJeU5qaEdNalE1UXpBM04wRXdOVGs1UWpKRFJqZ3hNRU15TlRSRU1qbEVRUSJ9.eyJnaXZlbl9uYW1lIjoiQWxleGFuZGVyIiwiZmFtaWx5X25hbWUiOiJLYWxpdGVueWEiLCJuaWNrbmFtZSI6ImFrYWxpdGVueWEiLCJuYW1lIjoiQWxleGFuZGVyIEthbGl0ZW55YSIsInBpY3R1cmUiOiJodHRwczovL21lZGlhLmxpY2RuLmNvbS9kbXMvaW1hZ2UvQzU2MDNBUUhEQkhyYkNKckJkUS9wcm9maWxlLWRpc3BsYXlwaG90by1zaHJpbmtfMTAwXzEwMC8wP2U9MTUzMzc3MjgwMCZ2PWJldGEmdD1acE1scGlFd2ZOZXo2UFREN0pDODN6ZkhYNm50ZElwMkpfa3daNE5EbnlZIiwidXBkYXRlZF9hdCI6IjIwMTgtMDktMTdUMDY6NDk6MTUuNDUwWiIsImVtYWlsIjoiYWthbGl0ZW55YUBtcHJvdmUuaW8iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9tcHJvdmUuYXV0aDAuY29tLyIsInN1YiI6ImxpbmtlZGlufGdmNEFQMVVTc2MiLCJhdWQiOiJ5ZWZiMUw5RnRJRFFBdkJnczV4cmxDMEN5aWo0dm5nUSIsImlhdCI6MTUzNzE2Njk1NSwiZXhwIjoxNTM3MjAyOTU1LCJhdF9oYXNoIjoibU1QVkdIUWpKT0w2OFM4SjVRek5FdyIsIm5vbmNlIjoic3QxdnpRSExFb3EyLXpFSXdwQkUyMnhYVE9ueE9kQ3YifQ.vNZCrLOm_0mxbcXVYL56NLEXwaKM2Ul6fLze8-mkOmyfKW9mN4jfFkzRMch1dMlBoft69t1zHRqbxSxrLZ5cD4dm-jeqrZPs0vFOhyIFegdGjOWGpu_aqWIx2QLyrdgGCYVBjkqk9W22G68XmAm-I9etziSjjAMsNJBKQ3LoX-E5MHlxtaxexRNVevi249t5S1JNsSffVB_jccEyOjkkVTm9nf8BEvxst0qMvZCY6C9TkrEwzuiQ_JHw-ZxY_WS4chly_fPYMA52QVX0oo8oLHdBDhJtqExnM8xrIz30QtsoGlVzwucRtntjtvm3oVObCU2es28o-HJ2aahtb7wnKg"

curl $DOMAIN/api/v1/projects.checkProjectIdUnique \
-H "Authorization: $BEARER" \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-X POST \
-d @sh/api_error_check_project_id_unique.json