

# DOMAIN
export DOMAIN="http://localhost:8080"
#export DOMAIN="https://dev.mprove.io"
#export DOMAIN="https://arhar.online"

export BEARER="Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1EazNNamc1TlRJeU5qaEdNalE1UXpBM04wRXdOVGs1UWpKRFJqZ3hNRU15TlRSRU1qbEVRUSJ9.eyJnaXZlbl9uYW1lIjoiQWxleGFuZGVyIiwiZmFtaWx5X25hbWUiOiJLYWxpdGVueWEiLCJuaWNrbmFtZSI6ImFrYWxpdGVueWEiLCJuYW1lIjoiQWxleGFuZGVyIEthbGl0ZW55YSIsInBpY3R1cmUiOiJodHRwczovL21lZGlhLmxpY2RuLmNvbS9kbXMvaW1hZ2UvQzU2MDNBUUhEQkhyYkNKckJkUS9wcm9maWxlLWRpc3BsYXlwaG90by1zaHJpbmtfMTAwXzEwMC8wP2U9MTUzMzc3MjgwMCZ2PWJldGEmdD1acE1scGlFd2ZOZXo2UFREN0pDODN6ZkhYNm50ZElwMkpfa3daNE5EbnlZIiwidXBkYXRlZF9hdCI6IjIwMTgtMDktMjFUMDk6Mjc6MjkuMTM1WiIsImVtYWlsIjoiYWthbGl0ZW55YUBtcHJvdmUuaW8iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9tcHJvdmUuYXV0aDAuY29tLyIsInN1YiI6ImxpbmtlZGlufGdmNEFQMVVTc2MiLCJhdWQiOiJ5ZWZiMUw5RnRJRFFBdkJnczV4cmxDMEN5aWo0dm5nUSIsImlhdCI6MTUzNzUyMjA0OSwiZXhwIjoxNTM3NTU4MDQ5LCJhdF9oYXNoIjoidjlrNjY2aVBiZU9pbGFPTlI1a0RHdyIsIm5vbmNlIjoidXpBNjZ-amRYdThNfmpPd2JyNnhVVVBUWlRuR3dweWQifQ.uJsYgg3FpxNaE1ZzR9X92ndrgrIN8I9wZQ9GEWQbpAljVFuNxtS9iK-Wlh37hQmnLbqi5vwA4yTaBzRokP0o84zXd_ntC726xKZKBRB7MzB_dRACLFw6j65QiwGIPy8vqAPBmjuYG8aslPMxB9LVzIVkqibrLBval0G_JXUuX2MFza52XaKIgcKtDkGQab36wVEQK0WEx1l8n8GzicUr2t63olK47jSgWXF9eFIAO8FLb8uAzBJAbbXUxgBR9OqWeW_LGoNVFeqMC7j95ASQwNTrcEPqmEhTG5ByAViZQPkXlWTOkP5kDY4du2wOKJg47tQuSKQAfeRXws9QEZDkjA"

curl $DOMAIN/api/v1/projects.checkProjectIdUnique \
-H "Authorization: $BEARER" \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-X POST \
-d @sh/check_project_id_unique.json