export enum ErEnum {
  M_DISK_WRONG_REQUEST_INFO_NAME = 'M_DISK_WRONG_REQUEST_INFO_NAME',
  M_DISK_ORGANIZATION_ALREADY_EXIST = 'M_DISK_ORGANIZATION_ALREADY_EXIST',
  M_DISK_ORGANIZATION_IS_NOT_EXIST = 'M_DISK_ORGANIZATION_IS_NOT_EXIST',
  M_DISK_PROJECT_ALREADY_EXIST = 'M_DISK_PROJECT_ALREADY_EXIST',
  M_DISK_PROJECT_IS_NOT_EXIST = 'M_DISK_PROJECT_IS_NOT_EXIST'
}
