import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

let __dirname = dirname(fileURLToPath(import.meta.url));

let mproveDocsHost = process.env.MPROVE_DOCS_HOST;

if (!mproveDocsHost) {
  throw new Error('MPROVE_DOCS_HOST is required to build docs');
}

let docsOrigin = mproveDocsHost.replace(/\/+$/, '');

let docsIndexPath = '/content/docs/docs-for-ai.mdx';

let docsIndexUrl = `${docsOrigin}${docsIndexPath}`;

let docsPathPrefix = '/content/docs/';

let outDir = resolve(__dirname, 'src/mprove-docs-cache');

let tocFilePath = resolve(outDir, 'toc.ts');

let tocToContentFilePath = resolve(outDir, 'toc-to-content.ts');

let indexContent = await fetchText({ url: docsIndexUrl });

let toc = getDocsMdxPaths({ indexContent: indexContent });

let entries = await Promise.all(
  toc.map(async filePath => {
    let url = `${docsOrigin}${docsPathPrefix}${filePath}`;

    let content = await fetchText({ url: url });

    return [filePath, content] as const;
  })
);

let tocToContent = Object.fromEntries(entries);

let tocLiteral = stringifyTsStringArray({ values: toc });

let tocToContentLiteral = stringifyTsStringRecord({ value: tocToContent });

let tocFileContent = `// Auto-generated by build-docs.ts. Do not edit by hand.

export const toc: readonly string[] = ${tocLiteral};
`;

let tocToContentFileContent = `// Auto-generated by build-docs.ts. Do not edit by hand.

export const tocToContent: Readonly<Record<string, string>> = ${tocToContentLiteral};
`;

await rm(outDir, { recursive: true, force: true });

await mkdir(outDir, { recursive: true });

await writeFile(tocFilePath, tocFileContent, 'utf8');

await writeFile(tocToContentFilePath, tocToContentFileContent, 'utf8');

console.log(`docs: fetched ${docsIndexUrl}`);
console.log(`docs: wrote ${toc.length} files`);
console.log(`  toc:            ${tocFilePath}`);
console.log(`  toc-to-content: ${tocToContentFilePath}`);

async function fetchText(item: { url: string }) {
  let { url } = item;

  let response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${url}: ${response.status} ${response.statusText}`
    );
  }

  return response.text();
}

function getDocsMdxPaths(item: { indexContent: string }) {
  let { indexContent } = item;

  let matches = indexContent.matchAll(/href="([^"]+\.mdx)"/g);

  let paths = Array.from(matches)
    .map(match => match[1])
    .filter(path => path.startsWith(docsPathPrefix))
    .map(path => path.slice(docsPathPrefix.length));

  return Array.from(new Set(paths)).sort((a, b) => a.localeCompare(b));
}

function stringifyTsStringArray(item: { values: string[] }) {
  let { values } = item;

  let lines = values.map(value => `  ${stringifyTsString({ value: value })}`);

  return `[
${lines.join(',\n')}
]`;
}

function stringifyTsStringRecord(item: { value: Record<string, string> }) {
  let { value } = item;

  let lines = Object.entries(value).map(([key, content]) => {
    let tsKey = stringifyTsString({ value: key });
    let tsContent = stringifyTsTemplateString({ value: content });

    return `  ${tsKey}: ${tsContent}`;
  });

  return `{
${lines.join(',\n')}
}`;
}

function stringifyTsString(item: { value: string }) {
  let { value } = item;

  let jsonString = JSON.stringify(value);
  let innerString = jsonString.slice(1, -1).replace(/'/g, "\\'");

  return `'${innerString}'`;
}

function stringifyTsTemplateString(item: { value: string }) {
  let { value } = item;

  let escapedValue = value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  return `\`${escapedValue}\``;
}
