import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

let __dirname = dirname(fileURLToPath(import.meta.url));

let mproveDocsHost = process.env.MPROVE_DOCS_HOST;

if (!mproveDocsHost) {
  throw new Error('MPROVE_DOCS_HOST is required to build docs');
}

let fetchTimeoutMs = 10_000;

let docsOrigin = mproveDocsHost.replace(/\/+$/, '');

let docsIndexPath = '/content/docs/docs-for-ai.mdx';

let docsIndexUrl = `${docsOrigin}${docsIndexPath}`;

let docsPathPrefix = '/content/docs/';

let skillsPathPrefix = '/content/skills/';

let excludedFilePaths = ['docs-for-ai.mdx'];

let outDir = resolve(__dirname, 'src/mprove-docs-cache');

let tocFilePath = resolve(outDir, 'toc.ts');

let tocToContentFilePath = resolve(outDir, 'toc-to-content.ts');

let skillsFilePath = resolve(outDir, 'skills.ts');

let indexContent = await fetchText({ url: docsIndexUrl });

let toc = getDocsMdxPaths({ indexContent: indexContent });

let skillNames = getSkillNames({ indexContent: indexContent });

let entries = await Promise.all(
  toc.map(async filePath => {
    let url = `${docsOrigin}${docsPathPrefix}${filePath}`;

    let content = await fetchText({ url: url });

    return [filePath, content] as const;
  })
);

let skills = await Promise.all(
  skillNames.map(async name => {
    let url = `${docsOrigin}${skillsPathPrefix}${name}.mdx`;

    let content = await fetchText({ url: url });

    return { name: name, content: content };
  })
);

let tocToContent = entries.map(([filePath, content]) => ({
  filePath: filePath,
  content: content
}));

let tocLiteral = stringifyTsStringArray({ values: toc });

let tocToContentLiteral = stringifyTsTocToContentArray({
  value: tocToContent
});

let skillsLiteral = stringifyTsSkillsArray({ value: skills });

let tocFileContent = `// Auto-generated by build-docs.ts. Do not edit by hand.

export const toc: readonly string[] = ${tocLiteral};
`;

let tocToContentFileContent = `// Auto-generated by build-docs.ts. Do not edit by hand.

export const tocToContent: { filePath: string; content: string }[] = ${tocToContentLiteral};
`;

let skillsFileContent = `// Auto-generated by build-docs.ts. Do not edit by hand.

export const SKILLS_DATA: { name: string; content: string }[] = ${skillsLiteral};
`;

await rm(outDir, { recursive: true, force: true });

await mkdir(outDir, { recursive: true });

await writeFile(tocFilePath, tocFileContent, 'utf8');

await writeFile(tocToContentFilePath, tocToContentFileContent, 'utf8');

await writeFile(skillsFilePath, skillsFileContent, 'utf8');

console.log(`docs: fetched ${docsIndexUrl}`);
console.log(`docs: wrote ${toc.length} doc files, ${skills.length} skills`);
console.log(`  toc:            ${tocFilePath}`);
console.log(`  toc-to-content: ${tocToContentFilePath}`);
console.log(`  skills:         ${skillsFilePath}`);

async function fetchText(item: { url: string }) {
  let { url } = item;

  let response: Response;
  try {
    response = await fetch(url, {
      signal: AbortSignal.timeout(fetchTimeoutMs)
    });
  } catch (error) {
    let reason =
      error instanceof Error && error.name === 'TimeoutError'
        ? `timed out after ${fetchTimeoutMs}ms`
        : error instanceof Error
          ? error.message
          : String(error);
    throw new Error(`Failed to fetch ${url}: ${reason}`);
  }

  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${url}: ${response.status} ${response.statusText}`
    );
  }

  return response.text();
}

function getDocsMdxPaths(item: { indexContent: string }) {
  let { indexContent } = item;

  let matches = indexContent.matchAll(/href="([^"]+\.mdx)"/g);

  let paths = Array.from(matches)
    .map(match => match[1])
    .filter(path => path.startsWith(docsPathPrefix))
    .map(path => path.slice(docsPathPrefix.length))
    .filter(path => !excludedFilePaths.includes(path));

  return Array.from(new Set(paths)).sort((a, b) => a.localeCompare(b));
}

function getSkillNames(item: { indexContent: string }) {
  let { indexContent } = item;

  let matches = indexContent.matchAll(/href="([^"]+\.mdx)"/g);

  let names = Array.from(matches)
    .map(match => match[1])
    .filter(path => path.startsWith(skillsPathPrefix))
    .map(path => path.slice(skillsPathPrefix.length))
    .map(file => file.replace(/\.mdx$/, ''));

  return Array.from(new Set(names)).sort((a, b) => a.localeCompare(b));
}

function stringifyTsStringArray(item: { values: string[] }) {
  let { values } = item;

  let lines = values.map(value => `  ${stringifyTsString({ value: value })}`);

  return `[
${lines.join(',\n')}
]`;
}

function stringifyTsTocToContentArray(item: {
  value: { filePath: string; content: string }[];
}) {
  let { value } = item;

  let lines = value.map(entry => {
    let tsFilePath = stringifyTsString({ value: entry.filePath });
    let tsContent = stringifyTsTemplateString({ value: entry.content });

    return `  { filePath: ${tsFilePath}, content: ${tsContent} }`;
  });

  return `[
${lines.join(',\n')}
]`;
}

function stringifyTsSkillsArray(item: {
  value: { name: string; content: string }[];
}) {
  let { value } = item;

  let lines = value.map(skill => {
    let tsName = stringifyTsString({ value: skill.name });
    let tsContent = stringifyTsTemplateString({ value: skill.content });

    return `  { name: ${tsName}, content: ${tsContent} }`;
  });

  return `[
${lines.join(',\n')}
]`;
}

function stringifyTsString(item: { value: string }) {
  let { value } = item;

  let jsonString = JSON.stringify(value);
  let innerString = jsonString.slice(1, -1).replace(/'/g, "\\'");

  return `'${innerString}'`;
}

function stringifyTsTemplateString(item: { value: string }) {
  let { value } = item;

  let escapedValue = value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  return `\`${escapedValue}\``;
}
