import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

let __dirname = dirname(fileURLToPath(import.meta.url));

let mproveDocsHost = process.env.MPROVE_DOCS_HOST;

if (!mproveDocsHost) {
  throw new Error('MPROVE_DOCS_HOST is required to build docs');
}

let docsOrigin = mproveDocsHost.replace(/\/+$/, '');

let docsIndexPath = '/content/docs/docs-for-ai.mdx';

let docsIndexUrl = `${docsOrigin}${docsIndexPath}`;

let docsPathPrefix = '/content/docs/';

let outDir = resolve(__dirname, 'src/mprove-docs-cache');

let tocFilePath = resolve(outDir, 'toc.ts');

let tocToContentFilePath = resolve(outDir, 'toc-to-content.ts');

let indexContent = await fetchText({ url: docsIndexUrl });

let toc = getDocsMdxPaths({ indexContent: indexContent });

let entries = await Promise.all(
  toc.map(async filePath => {
    let url = `${docsOrigin}${docsPathPrefix}${filePath}`;

    let content = await fetchText({ url: url });

    return [filePath, content];
  })
);

let tocToContent = Object.fromEntries(entries);

let tocLiteral = JSON.stringify(toc, null, 2);

let tocToContentLiteral = JSON.stringify(tocToContent, null, 2);

let tocFileContent = `// Auto-generated by build-docs.mjs. Do not edit by hand.

export const toc: readonly string[] = ${tocLiteral};
`;

let tocToContentFileContent = `// Auto-generated by build-docs.mjs. Do not edit by hand.

export const tocToContent: Readonly<Record<string, string>> = ${tocToContentLiteral};
`;

await rm(outDir, { recursive: true, force: true });

await mkdir(outDir, { recursive: true });

await writeFile(tocFilePath, tocFileContent, 'utf8');

await writeFile(tocToContentFilePath, tocToContentFileContent, 'utf8');

console.log(`docs: fetched ${docsIndexUrl}`);
console.log(`docs: wrote ${toc.length} files`);
console.log(`  toc:            ${tocFilePath}`);
console.log(`  toc-to-content: ${tocToContentFilePath}`);

async function fetchText(item) {
  let { url } = item;

  let response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }

  return response.text();
}

function getDocsMdxPaths(item) {
  let { indexContent } = item;

  let matches = indexContent.matchAll(/href="([^"]+\.mdx)"/g);

  let paths = Array.from(matches)
    .map(match => match[1])
    .filter(path => path.startsWith(docsPathPrefix))
    .map(path => path.slice(docsPathPrefix.length));

  return Array.from(new Set(paths)).sort((a, b) => a.localeCompare(b));
}
