export enum ChartTypeEnum {
  Table = 'Table',
  BarVertical = 'BarVertical',
  BarVerticalGrouped = 'BarVerticalGrouped',
  BarVerticalStacked = 'BarVerticalStacked',
  BarVerticalNormalized = 'BarVerticalNormalized',
  BarHorizontal = 'BarHorizontal',
  BarHorizontalGrouped = 'BarHorizontalGrouped',
  BarHorizontalStacked = 'BarHorizontalStacked',
  BarHorizontalNormalized = 'BarHorizontalNormalized',
  Pie = 'Pie',
  PieAdvanced = 'PieAdvanced',
  PieGrid = 'PieGrid',
  Line = 'Line',
  Area = 'Area',
  AreaStacked = 'AreaStacked',
  AreaNormalized = 'AreaNormalized',
  HeatMap = 'HeatMap',
  TreeMap = 'TreeMap',
  NumberCard = 'NumberCard',
  Gauge = 'Gauge',
  GaugeLinear = 'GaugeLinear'
}
