export enum ChartTypeEnum {
  Table = 'table',
  BarVertical = 'bar_vertical',
  BarVerticalGrouped = 'bar_vertical_grouped',
  BarVerticalStacked = 'bar_vertical_stacked',
  BarVerticalNormalized = 'bar_vertical_normalized',
  BarHorizontal = 'bar_horizontal',
  BarHorizontalGrouped = 'bar_horizontal_grouped',
  BarHorizontalStacked = 'bar_horizontal_stacked',
  BarHorizontalNormalized = 'bar_horizontal_normalized',
  Pie = 'pie',
  PieAdvanced = 'pie_advanced',
  PieGrid = 'pie_grid',
  Line = 'line',
  Area = 'area',
  AreaStacked = 'area_stacked',
  AreaNormalized = 'area_normalized',
  HeatMap = 'heat_map',
  TreeMap = 'tree_map',
  NumberCard = 'number_card',
  Gauge = 'gauge',
  GaugeLinear = 'gauge_linear'
}
