import { ngrxType } from '@app/ngrx/ngrx-type';

export const CREATE_PROJECT = ngrxType('CREATE_PROJECT');
export const CREATE_PROJECT_SUCCESS = ngrxType('CREATE_PROJECT_SUCCESS');
export const CREATE_PROJECT_FAIL = ngrxType('CREATE_PROJECT_FAIL');

export const DELETE_PROJECT = ngrxType('DELETE_PROJECT');
export const DELETE_PROJECT_SUCCESS = ngrxType('DELETE_PROJECT_SUCCESS');
export const DELETE_PROJECT_FAIL = ngrxType('DELETE_PROJECT_FAIL');

export const DELETE_PROJECT_CREDENTIALS = ngrxType(
  'DELETE_PROJECT_CREDENTIALS'
);
export const DELETE_PROJECT_CREDENTIALS_SUCCESS = ngrxType(
  'DELETE_PROJECT_CREDENTIALS_SUCCESS'
);
export const DELETE_PROJECT_CREDENTIALS_FAIL = ngrxType(
  'DELETE_PROJECT_CREDENTIALS_FAIL'
);

export const SET_PROJECT_CREDENTIALS = ngrxType('SET_PROJECT_CREDENTIALS');
export const SET_PROJECT_CREDENTIALS_SUCCESS = ngrxType(
  'SET_PROJECT_CREDENTIALS_SUCCESS'
);
export const SET_PROJECT_CREDENTIALS_FAIL = ngrxType(
  'SET_PROJECT_CREDENTIALS_FAIL'
);

export const SET_PROJECT_QUERY_SIZE_LIMIT = ngrxType(
  'SET_PROJECT_QUERY_SIZE_LIMIT'
);
export const SET_PROJECT_QUERY_SIZE_LIMIT_SUCCESS = ngrxType(
  'SET_PROJECT_QUERY_SIZE_LIMIT_SUCCESS'
);
export const SET_PROJECT_QUERY_SIZE_LIMIT_FAIL = ngrxType(
  'SET_PROJECT_QUERY_SIZE_LIMIT_FAIL'
);

export const SET_PROJECT_TIMEZONE = ngrxType('SET_PROJECT_TIMEZONE');
export const SET_PROJECT_TIMEZONE_SUCCESS = ngrxType(
  'SET_PROJECT_TIMEZONE_SUCCESS'
);
export const SET_PROJECT_TIMEZONE_FAIL = ngrxType('SET_PROJECT_TIMEZONE_FAIL');

export const SET_PROJECT_WEEK_START = ngrxType('SET_PROJECT_WEEK_START');
export const SET_PROJECT_WEEK_START_SUCCESS = ngrxType(
  'SET_PROJECT_WEEK_START_SUCCESS'
);
export const SET_PROJECT_WEEK_START_FAIL = ngrxType(
  'SET_PROJECT_WEEK_START_FAIL'
);
