export enum blockmlErrorsEnum {
  // BLOCKML_GET_PROJECTS = 'BLOCKML_GET_PROJECTS',
  BLOCKML_PROCESS_DASHBOARD = 'BLOCKML_PROCESS_DASHBOARD',
  BLOCKML_PROCESS_QUERY = 'BLOCKML_PROCESS_QUERY',
  BLOCKML_REBUILD_STRUCT = 'BLOCKML_REBUILD_STRUCT'
  // BLOCKML_WRAP_BLOCKML_REQUEST = 'BLOCKML_WRAP_BLOCKML_REQUEST',
}
