export enum diskErrorsEnum {
  DISK_EMPTY_DIR = 'DISK_EMPTY_DIR',
  DISK_ENSURE_FILE = 'DISK_ENSURE_FILE',
  DISK_ENSURE_DIR = 'DISK_ENSURE_DIR',
  DISK_GET_REPO_CATALOG_NODES_AND_FILES = 'DISK_GET_REPO_CATALOG_NODES_AND_FILES',
  DISK_GET_DIR_CATALOG_NODES_AND_FILES_RECURSIVE = 'DISK_GET_DIR_CATALOG_NODES_AND_FILES_RECURSIVE',
  DISK_IS_PROJECT_EXIST_ON_DISK = 'DISK_IS_PROJECT_EXIST_ON_DISK',
  DISK_IS_REPO_EXIST_ON_DISK = 'DISK_IS_REPO_EXIST_ON_DISK',
  DISK_MOVE_PATH = 'DISK_MOVE_PATH',
  DISK_REMOVE_PATH = 'DISK_REMOVE_PATH',
  DISK_WRITE_TO_FILE = 'DISK_WRITE_TO_FILE',
}
