export enum generatorErrorsEnum {
  // GENERATOR_MAKE_FILE = 'GENERATOR_MAKE_FILE',
  // GENERATOR_MAKE_MEMBER = 'GENERATOR_MAKE_MEMBER',
  // GENERATOR_MAKE_PROJECT = 'GENERATOR_MAKE_PROJECT',
  // GENERATOR_MAKE_REPO = 'GENERATOR_MAKE_REPO',
  // GENERATOR_MAKE_USER = 'GENERATOR_MAKE_USER',
}
