export enum gitErrorsEnum {
  GIT_ADD_CHANGES_TO_STAGE = 'GIT_ADD_CHANGES_TO_STAGE',
  GIT_CLONE_CENTRAL_TO_DEV = 'GIT_CLONE_CENTRAL_TO_DEV',
  GIT_CLONE_CENTRAL_TO_PROD = 'GIT_CLONE_CENTRAL_TO_PROD',
  GIT_PREPARE_CENTRAL_AND_PROD = 'GIT_PREPARE_CENTRAL_AND_PROD',
  GIT_INIT_CENTRAL_REPO = 'GIT_INIT_CENTRAL_REPO',
  GIT_COMMIT = 'GIT_COMMIT',
  GIT_CREATE_INITIAL_COMMIT_TO_PROD = 'GIT_CREATE_INITIAL_COMMIT_TO_PROD',
  GIT_FETCH_ORIGIN = 'GIT_FETCH_ORIGIN',
  GIT_GET_DIFF_FILES = 'GIT_GET_DIFF_FILES',
  GIT_GET_REPO_STATUS = 'GIT_GET_REPO_STATUS',
  GIT_MERGE_BRANCHES_ORIGIN_TO_LOCAL = 'GIT_MERGE_BRANCHES_ORIGIN_TO_LOCAL',
  GIT_MERGE_COMMITS_ORIGIN_TO_LOCAL = 'GIT_MERGE_COMMITS_ORIGIN_TO_LOCAL',
  GIT_PUSH_TO_CENTRAL = 'GIT_PUSH_TO_CENTRAL',
  GIT_REVERT_REPO_TO_LAST_COMMIT = 'GIT_REVERT_REPO_TO_LAST_COMMIT',
  GIT_REVERT_REPO_TO_PRODUCTION = 'GIT_REVERT_REPO_TO_PRODUCTION'
}
