export enum handlerErrorsEnum {
  HANDLER_CATCH_ASYNC_ERRORS = 'HANDLER_CATCH_ASYNC_ERRORS',
  HANDLER_ERROR_TO_RESPONSE = 'HANDLER_ERROR_TO_RESPONSE',
  HANDLER_PROMISIFY_CATCH_ASYNC_ERRORS = 'HANDLER_PROMISIFY_CATCH_ASYNC_ERRORS',
}
