export enum procErrorsEnum {
  PROC_CREATE_DATASET = 'PROC_CREATE_DATASET',
  PROC_FIND_ALIAS = 'PROC_FIND_ALIAS',
  PROC_FIND_DIFFERENCES_IN_FILES = 'PROC_FIND_DIFFERENCES_IN_FILES',
  PROC_PREPARE_MESSAGE = 'PROC_PREPARE_MESSAGE',
  PROC_PROCESS_DEV_REPO_CHANGES = 'PROC_PROCESS_DEV_REPO_CHANGES',
  PROC_PROCESS_RUNNING_QUERY = 'PROC_PROCESS_RUNNING_QUERY',
  PROC_PROCESS_WAITING_QUERY = 'PROC_PROCESS_WAITING_QUERY',
  PROC_RUN_QUERY_DRY = 'PROC_RUN_QUERY_DRY',
  PROC_RUN_QUERY_WITHOUT_DEPS = 'PROC_RUN_QUERY_WITHOUT_DEPS',
  PROC_RUN_QUERY = 'PROC_RUN_QUERY',
  PROC_SPLIT_CHUNK = 'PROC_SPLIT_CHUNK',
  PROC_SPLIT_CHUNK_CREATE_MESSAGE = 'PROC_SPLIT_CHUNK_CREATE_MESSAGE',

  PROC_CHECK_COPYING_QUERY = 'PROC_CHECK_COPYING_QUERY',
  PROC_CHECK_NOT_COPYING_QUERY = 'PROC_CHECK_NOT_COPYING_QUERY',
  PROC_COPY_QUERY_RESULTS_TO_PDT = 'PROC_COPY_QUERY_RESULTS_TO_PDT',
}
