export enum schedulerErrorsEnum {
  SCHEDULER_DELETE_SESSIONS = 'SCHEDULER_DELETE_SESSIONS',
  SCHEDULER_PING = 'SCHEDULER_PING',
  SCHEDULER_RESEND_MESSAGE = 'SCHEDULER_RESEND_MESSAGE',
  SCHEDULER_CHECK_QUERIES = 'SCHEDULER_CHECK_QUERIES',
  SCHEDULER_CHECK_DEMO = 'SCHEDULER_CHECK_DEMO',
  SCHEDULER_CHECK_CHUNKS = 'SCHEDULER_CHECK_CHUNKS'
}
