export enum schedulerErrorsEnum {
  SCHEDULER_DELETE_SESSIONS = 'SCHEDULER_DELETE_SESSIONS',
  SCHEDULER_DELETE_PROJECTS = 'SCHEDULER_DELETE_PROJECTS',
  SCHEDULER_DELETE_QUERIES = 'SCHEDULER_DELETE_QUERIES',
  SCHEDULER_DELETE_MEMBERS = 'SCHEDULER_DELETE_MEMBERS',
  SCHEDULER_DELETE_USERS = 'SCHEDULER_DELETE_USERS',
  SCHEDULER_PING = 'SCHEDULER_PING',
  SCHEDULER_RESEND_MESSAGE = 'SCHEDULER_RESEND_MESSAGE',
  SCHEDULER_CHECK_QUERIES = 'SCHEDULER_CHECK_QUERIES',
  SCHEDULER_CHECK_DEMO = 'SCHEDULER_CHECK_DEMO',
  SCHEDULER_CHECK_CHUNKS = 'SCHEDULER_CHECK_CHUNKS'
}
