export enum schedulerErrorsEnum {
  SCHEDULER_DELETE_SESSIONS = 'SCHEDULER_DELETE_SESSIONS',
  SCHEDULER_PING = 'SCHEDULER_PING',
  SCHEDULER_CHECK_QUERIES = 'SCHEDULER_CHECK_QUERIES',
  SCHEDULER_CHECK_CHUNKS = 'SCHEDULER_CHECK_CHUNKS'
}
