export enum storeErrorsEnum {
  STORE_DELETE_OLD_STRUCT = 'STORE_DELETE_OLD_STRUCT',
  STORE_INSERT = 'STORE_INSERT',
  STORE_SAVE = 'STORE_SAVE',

  // USERS

  STORE_USERS_FIND_ONE = 'STORE_USERS_FIND_ONE',
  STORE_USERS_FIND = 'STORE_USERS_FIND',
  STORE_USERS_INSERT = 'STORE_USERS_INSERT',
  STORE_USERS_SAVE = 'STORE_USERS_SAVE',

  // PROJECTS

  STORE_PROJECTS_FIND_ONE = 'STORE_PROJECTS_FIND_ONE',
  STORE_PROJECTS_FIND = 'STORE_PROJECTS_FIND',
  STORE_PROJECTS_INSERT = 'STORE_PROJECTS_INSERT',
  STORE_PROJECTS_SAVE = 'STORE_PROJECTS_SAVE',

  // MEMBERS

  STORE_MEMBERS_FIND_ONE = 'STORE_MEMBERS_FIND_ONE',
  STORE_MEMBERS_FIND = 'STORE_MEMBERS_FIND',
  STORE_MEMBERS_INSERT = 'STORE_MEMBERS_INSERT',

  STORE_MEMBERS_SAVE = 'STORE_MEMBERS_SAVE',

  // REPOS

  STORE_REPOS_FIND = 'STORE_REPOS_FIND',
  STORE_REPOS_FIND_ONE = 'STORE_REPOS_FIND_ONE',
  STORE_REPOS_INSERT = 'STORE_REPOS_INSERT',
  STORE_REPOS_SAVE = 'STORE_REPOS_SAVE',

  // FILES

  STORE_FILES_FIND_ONE = 'STORE_FILES_FIND_ONE',
  STORE_FILES_FIND = 'STORE_FILES_FIND',
  STORE_FILES_INSERT = 'STORE_FILES_INSERT',
  STORE_FILES_SAVE = 'STORE_FILES_SAVE',
  STORE_FILES_DELETE = 'STORE_FILES_DELETE',

  // ERRORS

  STORE_ERRORS_FIND = 'STORE_ERRORS_FIND',
  STORE_ERRORS_INSERT = 'STORE_ERRORS_INSERT',
  STORE_ERRORS_SAVE = 'STORE_ERRORS_SAVE',
  STORE_ERRORS_DELETE = 'STORE_ERRORS_DELETE',

  // MODELS

  STORE_MODELS_FIND_ONE = 'STORE_MODELS_FIND_ONE',
  STORE_MODELS_FIND = 'STORE_MODELS_FIND',
  STORE_MODELS_INSERT = 'STORE_MODELS_INSERT',
  STORE_MODELS_SAVE = 'STORE_MODELS_SAVE',
  STORE_MODELS_DELETE = 'STORE_MODELS_DELETE',

  // DASHBOARDS

  STORE_DASHBOARDS_FIND_ONE = 'STORE_DASHBOARDS_FIND_ONE',
  STORE_DASHBOARDS_FIND = 'STORE_DASHBOARDS_FIND',
  STORE_DASHBOARDS_INSERT = 'STORE_DASHBOARDS_INSERT',
  STORE_DASHBOARDS_SAVE = 'STORE_DASHBOARDS_SAVE',
  STORE_DASHBOARDS_DELETE = 'STORE_DASHBOARDS_DELETE',

  // MCONFIGS

  STORE_MCONFIGS_FIND_ONE = 'STORE_MCONFIGS_FIND_ONE',
  STORE_MCONFIGS_FIND = 'STORE_MCONFIGS_FIND',
  STORE_MCONFIGS_INSERT = 'STORE_MCONFIGS_INSERT',
  STORE_MCONFIGS_SAVE = 'STORE_MCONFIGS_SAVE',
  STORE_MCONFIGS_DELETE = 'STORE_MCONFIGS_DELETE',

  // QUERIES

  STORE_QUERIES_FIND = 'STORE_QUERIES_FIND',
  STORE_QUERIES_FIND_ONE = 'STORE_QUERIES_FIND_ONE',
  STORE_QUERIES_INSERT = 'STORE_QUERIES_INSERT',
  STORE_QUERIES_SAVE = 'STORE_QUERIES_SAVE',
  STORE_QUERIES_DELETE = 'STORE_QUERIES_DELETE',

  // CHUNKS

  STORE_CHUNKS_QUERY_BUILDER = 'STORE_CHUNKS_QUERY_BUILDER',
  STORE_CHUNKS_FIND = 'STORE_CHUNKS_FIND',
  STORE_CHUNKS_INSERT = 'STORE_CHUNKS_INSERT',

  // MESSAGES

  STORE_MESSAGES_QUERY_BUILDER = 'STORE_MESSAGES_QUERY_BUILDER',
  STORE_MESSAGES_FIND = 'STORE_MESSAGES_FIND',
  STORE_MESSAGES_FIND_ONE = 'STORE_MESSAGES_FIND_ONE',
  STORE_MESSAGES_INSERT = 'STORE_MESSAGES_INSERT',
  STORE_MESSAGES_SAVE = 'STORE_MESSAGES_SAVE',

  // SESSIONS

  STORE_SESSIONS_QUERY_BUILDER = 'STORE_SESSIONS_QUERY_BUILDER',
  STORE_SESSIONS_FIND_ONE = 'STORE_SESSIONS_FIND_ONE',
  STORE_SESSIONS_INSERT = 'STORE_SESSIONS_INSERT',
  STORE_SESSIONS_SAVE = 'STORE_SESSIONS_SAVE',
  STORE_SESSIONS_DELETE = 'STORE_SESSIONS_DELETE',

  // CHUNK SESSION
  CHUNK_SESSION_INSERT = 'CHUNK_SESSION_INSERT',
  CHUNK_SESSION_QUERY_BUILDER = 'CHUNK_SESSION_QUERY_BUILDER'
}
