import { z } from 'zod';
import { zEmailTransport } from '#common/types/backend/config/email-transport';
import { zProjectRemoteType } from '#common/types/backend/parts/project/project-remote-type';
import { zBackendEnv } from '#common/types/node-common/env/backend-env';

export let zBackendConfig = z.object({
  mproveReleaseTag: z.string(),
  isTelemetryEnabled: z.boolean(),
  isTraceDrizzleEnabled: z.boolean(),
  telemetryEndpoint: z.string().optional(),
  telemetryHyperdxIngestApiKey: z.string().optional(),
  otelLogLevel: z.string().optional(),
  backendEnv: zBackendEnv,
  isEncryptDb: z.boolean(),
  isEncryptMetadata: z.boolean(),
  aesKey: z.string(),
  aesKeyTag: z.string(),
  prevAesKey: z.string().optional(),
  prevAesKeyTag: z.string().optional(),
  totalDiskShards: z.number(),
  rpcDiskTimeoutMs: z.number(),
  rpcBlockmlTimeoutMs: z.number(),
  isScheduler: z.boolean(),
  demoProjectDwhBigqueryCredentialsPath: z.string().optional(),
  demoProjectDwhGoogleApiCredentialsPath: z.string().optional(),
  jwtSecret: z.string(),
  specialKey: z.string(),
  allowTestRoutes: z.boolean(),
  mproveAdminEmail: z.string(),
  mproveAdminInitialPassword: z.string(),
  apiBlockHosts: z.string().optional(),
  apiAllowHosts: z.string().optional(),
  seedDemoOrgAndProject: z.boolean(),
  demoOrgId: z.string().optional(),
  demoProjectId: z.string().optional(),
  demoProjectName: z.string().optional(),
  demoProjectRemoteType: zProjectRemoteType.optional(),
  demoProjectRemoteGitUrl: z.string().optional(),
  demoProjectRemotePrivateKeyEncryptedPath: z.string().optional(),
  demoProjectRemotePublicKeyPath: z.string().optional(),
  demoProjectRemotePassPhrase: z.string().optional(),
  demoProjectDwhPostgresHost: z.string().optional(),
  demoProjectDwhPostgresUser: z.string().optional(),
  demoProjectDwhPostgresPassword: z.string().optional(),
  demoProjectDwhMysqlHost: z.string().optional(),
  demoProjectDwhMysqlPort: z.number().optional(),
  demoProjectDwhMysqlDatabase: z.string().optional(),
  demoProjectDwhMysqlUser: z.string().optional(),
  demoProjectDwhMysqlPassword: z.string().optional(),
  demoProjectDwhTrinoUser: z.string().optional(),
  demoProjectDwhTrinoPassword: z.string().optional(),
  demoProjectDwhPrestoUser: z.string().optional(),
  demoProjectDwhPrestoPassword: z.string().optional(),
  demoProjectDwhSnowflakeAccount: z.string().optional(),
  demoProjectDwhSnowflakeWarehouse: z.string().optional(),
  demoProjectDwhSnowflakeUsername: z.string().optional(),
  demoProjectDwhSnowflakePassword: z.string().optional(),
  demoProjectDwhMotherDuckToken: z.string().optional(),
  calcPostgresHost: z.string(),
  calcPostgresPort: z.number(),
  calcPostgresUsername: z.string(),
  calcPostgresPassword: z.string(),
  allowUsersToCreateOrganizations: z.boolean(),
  registerOnlyInvitedUsers: z.boolean(),
  hostUrl: z.string(),
  sendEmailFromName: z.string(),
  sendEmailFromAddress: z.string(),
  emailTransport: zEmailTransport,
  smtpHost: z.string(),
  smtpPort: z.number().int(),
  smtpSecure: z.boolean(),
  smtpAuthUser: z.string(),
  smtpAuthPassword: z.string(),
  backendIsForwardTelemetryEnabled: z.boolean(),
  backendValkeyHost: z.string(),
  backendValkeyPassword: z.string(),
  backendPostgresDatabaseUrl: z.string(),
  backendIsPostgresTls: z.boolean(),
  backendRequestIpHeaderA: z.string().optional(),
  backendRequestIpHeaderB: z.string().optional(),
  backendThrottlePublicRoutesByIp: z.boolean(),
  backendThrottlePrivateRoutesByUserId: z.boolean(),
  backendLogThrottleTracker: z.boolean(),
  backendLogDrizzlePostgres: z.boolean(),
  backendLogIsJson: z.boolean(),
  backendLogResponseError: z.boolean(),
  backendLogResponseOk: z.boolean(),
  dwhColumnUniqueValuesCacheLimit: z.number(),
  demoProjectE2bApiKey: z.string().optional(),
  e2bPublicTemplate: z.string().optional(),
  sandboxTimeoutMinutes: z.number().optional(),
  sessionLastActivityToPauseMinutes: z.number().optional(),
  sessionPauseOnUserTurnMinutes: z.number().optional(),
  maxActiveEditorSessionsPerProjectUser: z.number().optional(),
  sandboxMproveCliHost: z.string()
});

export type BackendConfig = z.infer<typeof zBackendConfig>;
