export enum ChartTypeEnum {
    Table = <any>'table',
    BarVertical = <any>'bar_vertical',
    BarVerticalGrouped = <any>'bar_vertical_grouped',
    BarVerticalStacked = <any>'bar_vertical_stacked',
    BarVerticalNormalized = <any>'bar_vertical_normalized',
    BarHorizontal = <any>'bar_horizontal',
    BarHorizontalGrouped = <any>'bar_horizontal_grouped',
    BarHorizontalStacked = <any>'bar_horizontal_stacked',
    BarHorizontalNormalized = <any>'bar_horizontal_normalized',
    Pie = <any>'pie',
    PieAdvanced = <any>'pie_advanced',
    PieGrid = <any>'pie_grid',
    Line = <any>'line',
    Area = <any>'area',
    AreaStacked = <any>'area_stacked',
    AreaNormalized = <any>'area_normalized',
    HeatMap = <any>'heat_map',
    TreeMap = <any>'tree_map',
    NumberCard = <any>'number_card',
    Gauge = <any>'gauge',
    GaugeLinear = <any>'gauge_linear'
}
