import { AvatarEnt } from '#backend/drizzle/postgres/schema/avatars';
import { BranchEnt } from '#backend/drizzle/postgres/schema/branches';
import { BridgeEnt } from '#backend/drizzle/postgres/schema/bridges';
import { ChartEnt } from '#backend/drizzle/postgres/schema/charts';
import { ConnectionEnt } from '#backend/drizzle/postgres/schema/connections';
import { DashboardEnt } from '#backend/drizzle/postgres/schema/dashboards';
import { DconfigEnt } from '#backend/drizzle/postgres/schema/dconfigs';
import { EnvEnt } from '#backend/drizzle/postgres/schema/envs';
import { KitEnt } from '#backend/drizzle/postgres/schema/kits';
import { MconfigEnt } from '#backend/drizzle/postgres/schema/mconfigs';
import { MemberEnt } from '#backend/drizzle/postgres/schema/members';
import { ModelEnt } from '#backend/drizzle/postgres/schema/models';
import { NoteEnt } from '#backend/drizzle/postgres/schema/notes';
import { OcEventEnt } from '#backend/drizzle/postgres/schema/oc-events';
import { OcMessageEnt } from '#backend/drizzle/postgres/schema/oc-messages';
import { OcPartEnt } from '#backend/drizzle/postgres/schema/oc-parts';
import { OcSessionEnt } from '#backend/drizzle/postgres/schema/oc-sessions';
import { OrgEnt } from '#backend/drizzle/postgres/schema/orgs';
import { ProjectEnt } from '#backend/drizzle/postgres/schema/projects';
import { QueryEnt } from '#backend/drizzle/postgres/schema/queries';
import { ReportEnt } from '#backend/drizzle/postgres/schema/reports';
import { SessionEnt } from '#backend/drizzle/postgres/schema/sessions';
import { StructEnt } from '#backend/drizzle/postgres/schema/structs';
import { UconfigEnt } from '#backend/drizzle/postgres/schema/uconfigs';
import { UserEnt } from '#backend/drizzle/postgres/schema/users';

export class DbEntsPack {
  avatars?: AvatarEnt[];
  branches?: BranchEnt[];
  bridges?: BridgeEnt[];
  connections?: ConnectionEnt[];
  dashboards?: DashboardEnt[];
  dconfigs?: DconfigEnt[];
  envs?: EnvEnt[];
  ocEvents?: OcEventEnt[];
  kits?: KitEnt[];
  mconfigs?: MconfigEnt[];
  members?: MemberEnt[];
  ocMessages?: OcMessageEnt[];
  models?: ModelEnt[];
  notes?: NoteEnt[];
  ocSessions?: OcSessionEnt[];
  orgs?: OrgEnt[];
  ocParts?: OcPartEnt[];
  projects?: ProjectEnt[];
  queries?: QueryEnt[];
  reports?: ReportEnt[];
  sessions?: SessionEnt[];
  structs?: StructEnt[];
  uconfigs?: UconfigEnt[];
  users?: UserEnt[];
  charts?: ChartEnt[];
}
