export enum otherErrorsEnum {
  INTERNAL = 'INTERNAL',
  AUTHORIZATION_EMAIL = 'AUTHORIZATION_EMAIL',
  API = 'API',

  PROMISE_ALL = 'ALL',
  FOR_EACH = 'FOR_EACH',

  EMAIL_ALIAS = 'EMAIL_ALIAS',
  SERVER_TS = 'SERVER_TS',
  REGISTER_ERROR_USER_ALREADY_EXISTS = 'REGISTER_ERROR_USER_ALREADY_EXISTS',
  LOGIN_ERROR_WRONG_PASSWORD = 'LOGIN_ERROR_WRONG_PASSWORD',
  LOGIN_ERROR_USER_DOES_NOT_EXIST = 'LOGIN_ERROR_USER_DOES_NOT_EXIST',
  VERIFY_EMAIL_ERROR_USER_DOES_NOT_EXIST = 'VERIFY_EMAIL_ERROR_USER_DOES_NOT_EXIST',
  CONFIRM_EMAIL_ERROR_USER_DOES_NOT_EXIST = 'CONFIRM_EMAIL_ERROR_USER_DOES_NOT_EXIST',
  MEMBER_ALREADY_EXIST = 'MEMBER_ALREADY_EXIST',
  MEMBER_IS_DELETED = 'MEMBER_IS_DELETED',
  USER_IS_NOT_ADMIN = 'USER_IS_NOT_ADMIN',
  USER_CAN_NOT_CHANGE_HIS_ADMIN_STATUS = 'USER_CAN_NOT_CHANGE_HIS_ADMIN_STATUS',
  USER_CAN_NOT_CHANGE_MEMBER_THEMES = 'USER_CAN_NOT_CHANGE_MEMBER_THEMES',
  USER_CAN_NOT_DELETE_HIMSELF = 'USER_CAN_NOT_DELETE_HIMSELF',

  // BLOCKML_RESPONSE

  BLOCKML_RESPONSE_WRONG_REQUEST_PARAMS = 'BLOCKML_RESPONSE_WRONG_REQUEST_PARAMS',
  BLOCKML_RESPONSE_INTERNAL = 'BLOCKML_RESPONSE_INTERNAL',
  BLOCKML_RESPONSE_NOT_OK = 'BLOCKML_RESPONSE_NOT_OK',

  // NOT FOUND

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  REPO_NOT_FOUND = 'REPO_NOT_FOUND',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  MCONFIG_NOT_FOUND = 'MCONFIG_NOT_FOUND',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  DASHBOARD_NOT_FOUND = 'DASHBOARD_NOT_FOUND',
  QUERY_NOT_FOUND = 'QUERY_NOT_FOUND',
  MODEL_NOT_FOUND = 'MODEL_NOT_FOUND',
  PDT_NOT_FOUND = 'PDT_NOT_FOUND'
}
