export enum FuncEnum {
  CollectFiles = '01-yaml/01-collect-files',
  RemoveWrongExt = '01-yaml/02-remove-wrong-ext',
  DeduplicateFileNames = '01-yaml/03-deduplicate-file-names',
  YamlToObjects = '01-yaml/04-yaml-to-objects',
  MakeLineNumbers = '01-yaml/05-make-line-numbers',
  CheckTopUnknownParameters = '01-yaml/06-check-top-unknown-parameters',
  CheckTopValues = '01-yaml/07-check-top-values',
  CheckConnections = '01-yaml/08-check-connections',
  CheckSupportUdfs = '01-yaml/09-check-support-udfs',
  SplitFiles = '01-yaml/10-split-files',

  CheckFieldsExist = '02-field/01-check-fields-exist',
  CheckFieldIsObject = '02-field/02-check-field-is-object',
  CheckFieldDeclaration = '02-field/03-check-field-declaration',
  CheckSqlExist = '02-field/04-check-sql-exist',
  CheckFieldNameDuplicates = '02-field/05-check-field-name-duplicates',
  CheckFieldUnknownParameters = '02-field/06-check-field-unknown-parameters',
  SetImplicitLabel = '02-field/07-set-implicit-label',
  CheckDimensions = '02-field/08-check-dimensions',
  TransformYesNoDimensions = '02-field/09-transform-yesno-dimensions',
  CheckMeasures = '02-field/10-check-measures',
  CheckCalculations = '02-field/11-check-calculations',
  CheckAndSetImplicitResult = '02-field/12-check-and-set-implicit-result',
  CheckAndSetImplicitFormatNumber = '02-field/13-check-and-set-implicit-format-number',
  TransformTimes = '02-field/14-transform-times',
  MakeFieldsDeps = '02-field/15-make-fields-deps',
  CheckFieldsDeps = '02-field/16-check-fields-deps',
  CheckCycles = '02-field/17-check-cycles',
  SubstituteSingleRefs = '02-field/18-substitute-single-refs',

  MakeUdfsDict = '03-udf/01-make-udfs-dict',

  CheckTable = '04-view/01-check-table',
  CheckViewUdfs = '04-view/02-check-view-udfs',
  CheckViewFilterDefaults = '04-view/03-check-view-filter-defaults',
  CheckDerivedTableApplyFilter = '04-view/04-check-derived-table-apply-filter',
  MakeViewAsDeps = '04-view/05-make-view-as-deps',
  CheckViewCycles = '04-view/06-check-view-cycles',
  CheckViewAsDeps = '04-view/07-check-view-as-deps',
  PickUdfsFromAsDeps = '04-view/08-pick-udfs-from-as-deps',
  ProcessViewRefs = '04-view/09-process-view-refs',

  CheckModelAccess = '05-model/01-check-model-access',
  CheckModelUdfs = '05-model/02-check-model-udfs',
  CheckJoinsExist = '05-model/03-check-joins-exist',
  CheckJoinsFromView = '05-model/04-check-joins-from-view',
  CheckAliases = '05-model/05-check-aliases',
  MakeJoins = '05-model/06-make-joins',
  MakeFieldsDoubleDeps = '05-model/07-make-fields-double-deps',
  CheckFieldsDoubleDeps = '05-model/08-check-fields-double-deps',
  MakeFieldsDoubleDepsAfterSingles = '05-model/09-make-fields-double-deps-after-singles',
  CheckModelFilterDefaults = '05-model/10-check-model-filter-defaults',

  CheckJoinUnknownParameters = '06-join/1-check-join-unknown-parameters',
  CheckJoinType = '06-join/2-check-join-type',
  // UpgradeJoinCalculationsForceDims = '06-join/3-upgrade-join-calculations-force-dims',
  CheckSqlOnExist = '06-join/4-check-sql-on-exist',
  CheckJoinHideShowFields = '06-join/5-check-join-hide-show-fields',

  JsoCheckCharsInRefs = '07-join-sql-on/1-jso-check-chars-in-refs',
  JsoMakeDoubleDeps = '07-join-sql-on/2-jso-make-double-deps',
  JsoCheckDoubleDeps = '07-join-sql-on/3-jso-check-double-deps',
  JsoCheckSingleRefs = '07-join-sql-on/4-jso-check-single-refs',
  JsoSubstituteSingleRefs = '07-join-sql-on/5-jso-substitute-single-refs',
  JsoMakeJoinsDoubleDepsAfterSingles = '07-join-sql-on/6-jso-make-joins-double-deps-after-singles',

  JswCheckCharsInRefs = '08-join-sql-where/1-jsw-check-chars-in-refs',
  JswMakeDoubleDeps = '08-join-sql-where/2-jsw-make-double-deps',
  JswCheckDoubleDeps = '08-join-sql-where/3-jsw-check-double-deps',
  JswCheckSingleRefs = '08-join-sql-where/4-jsw-check-single-refs',
  JswSubstituteSingleRefs = '08-join-sql-where/5-jsw-substitute-single-refs',
  JswUpdateJoinsDoubleDepsAfterSingles = '08-join-sql-where/6-jsw-update-joins-double-deps-after-singles',
  JswCheckApplyFilter = '08-join-sql-where/7-jsw-check-apply-filter',

  CheckJoinsCyclesAndToposort = '09-sort-joins/1-check-joins-cycles-and-toposort',
  CheckAlwaysJoin = '09-sort-joins/2-check-always-join',

  SawCheckCharsInRefs = '10-sql-always-where/1-saw-check-chars-in-refs',
  SawMakeDoubleDeps = '10-sql-always-where/2-saw-make-double-deps',
  SawCheckDoubleDeps = '10-sql-always-where/3-saw-check-double-deps',
  SawCheckSingleRefs = '10-sql-always-where/4-saw-check-single-refs',
  SawSubstituteSingleRefs = '10-sql-always-where/5-saw-substitute-single-refs',
  SawMakeDoubleDepsAfterSingles = '10-sql-always-where/6-saw-make-double-deps-after-singles',
  SawCheckApplyFilter = '10-sql-always-where/7-saw-check-apply-filter',
  SawUpdateAlwaysJoinUnique = '10-sql-always-where/8-saw-update-always-join-unique',

  AwcCheckCharsInRefs = '11-sql-always-where-calc/1-awc-check-chars-in-refs',
  AwcMakeDoubleDeps = '11-sql-always-where-calc/2-awc-make-double-deps',
  AwcCheckDoubleDeps = '11-sql-always-where-calc/3-awc-check-double-deps',
  AwcCheckSingleRefs = '11-sql-always-where-calc/4-awc-check-single-refs',
  AwcSubstituteSingleRefs = '11-sql-always-where-calc/5-awc-substitute-single-refs',
  AwcMakeDoubleDepsAfterSubstitutions = '11-sql-always-where-calc/6-awc-make-double-deps-after-substitutions',
  AwcCheckApplyFilter = '11-sql-always-where-calc/7-awc-check-apply-filter',
  AwcUpdateAlwaysJoinUnique = '11-sql-always-where-calc/8-awc-update-always-join-unique',

  CheckDashboardAccess = '12-dashboard/1-check-dashboard-access',
  CheckDashboardFilterDefaults = '12-dashboard/2-check-dashboard-filter-defaults',
  CheckDashboardReportsExist = '12-dashboard/3-check-dashboard-reports-exist',

  CheckVizAccess = '13-viz/1-check-viz-access',
  CheckVizReportsExist = '13-viz/2-check-viz-reports-exist',

  CheckReportIsObject = '14-report/1-check-report-is-object',
  CheckReportUnknownParameters = '14-report/2-check-report-unknown-parameters',
  CheckReportTitleModelSelect = '14-report/3-check-report-title-model-select',
  CheckSelectElements = '14-report/4-check-select-elements',
  // CheckSelectForceDims = '14-report/5-check-select-force-dims',
  CheckSorts = '14-report/6-check-sorts',
  CheckTimezone = '14-report/7-check-timezone',
  CheckLimit = '14-report/8-check-limit',
  CheckListenFilters = '14-report/9-check-listen-filters',
  CheckDefaultFilters = '14-report/10-check-default-filters',
  CombineReportFilters = '14-report/11-combine-report-filters',
  // CheckFiltersForceDims = '14-report/12-check-filters-force-dims',
  // CheckSqlAlwaysWhereCalcForceDims = '14-report/13-check-sql-always-where-calc-force-dims',
  FetchSql = '14-report/14-fetch-sql',

  CheckChartType = '15-chart/1-check-chart-type',
  CheckChartData = '15-chart/2-check-chart-data',
  CheckChartDataParameters = '15-chart/3-check-chart-data-parameters',
  CheckChartAxisParameters = '15-chart/4-check-chart-axis-parameters',
  CheckChartOptionsParameters = '15-chart/5-check-chart-options-parameters',
  CheckChartTileParameters = '15-chart/6-check-chart-tile-parameters',

  CheckMdzAccess = 'special/check-mdz-access',
  CheckVmdFilterDefaults = 'special/check-vmd-filter-defaults',
  LogStruct = 'special/log-struct',

  SubMakeDepMeasuresAndDimensions = 'special-1-sub/1-sub-make-dep-measures-and-dimensions',
  SubMakeMainText = 'special-1-sub/2-sub-make-main-text',
  SubMakeNeedsAll = 'special-1-sub/3-sub-make-needs-all',
  SubMakeWith = 'special-1-sub/4-sub-make-with',
  SubComposeMain = 'special-1-sub/5-sub-compose-main',
  SubComposeCalc = 'special-1-sub/6-sub-compose-calc',

  MakeDepMeasuresAndDimensions = 'special-2-sql/1-make-dep-measures-and-dimensions',
  MakeMainText = 'special-2-sql/2-make-main-text',
  MakeNeedsDoubles = 'special-2-sql/3-make-needs-doubles',
  FindJoinsUsingJoinsDeps = 'special-2-sql/4-find-joins-using-joins-deps',
  MakeNeedsAll = 'special-2-sql/5-make-needs-all',
  MakeFilters = 'special-2-sql/6-make-filters',
  MakeWith = 'special-2-sql/7-make-with',
  MakeTop = 'special-2-sql/8-make-top',
  ComposeMain = 'special-2-sql/9-compose-main',
  ProcessTimezone = 'special-2-sql/10-process-timezone',
  ComposeCalc = 'special-2-sql/11-compose-calc'
}
