// Auto-generated by fetch-docs.ts. Do not edit by hand.

export const SKILLS_DATA: { name: string; content: string }[] = [
  { name: 'mprove-basic', content: `---
name: mprove-basic
description: Mprove Basics
---

# mprove-basic

Use \`mprove\` CLI for \`sync\` command only. 
For other tasks, use Mprove MCP tools.

If you changed or created files, run \`mprove sync --env <env-id>\` before calling Mprove MCP tools to:
- sync uncommitted changes between local repo and backend repo
- validate (rebuild) Malloy and Mprove files

If project has no \`mprove.yml\` file - you should setup Mprove project first.

## Mprove project setup

The flow for setup a new Mprove project:

- create \`.gitignore\` file if not exist (or add missing parts from \`.gitignore\` example)
- load more relevant skills to context if needed
- call \`get-schemas\` tool. If there are no connections, ask the user to create Mprove database connection in UI before proceeding to the next step.
- create \`mprove.yml\` (if not exist)
- call \`get-state\` tool
- create \`.schema\` file for metadata and relationships (use \`get-schemas\` and \`get-sample\` tools to understand relationships)
- create Mprove model(s) based on Malloy sources
- create Mprove report, dashboard, chart
- run report, dashboard, chart
- provide report, dashboard, chart links to user

## Load more relevant skills if needed

- mprove-project-structure (Files and folders structure patterns)
- mprove-connection-schemas (\`.schema\` metadata files)
- mprove-build-malloy-model (Build Mprove Model based on Malloy sources)
- mprove-build-store-model (Build Mprove \`*.store\` Model file based on HTTP API sources)
- mprove-build-chart (Build Mprove Chart)
- mprove-build-report (Build Mprove Report)
- mprove-build-dashboard (Build Mprove Dashboard)
- mprove-query-data (Query chart, dashboard, report or build a new one. Answer question using data.)

## Notes

If YAML property has an array type - use an empty array [] instead of undefined or null value.

Mprove Reports are much more useful for Metrics (measures + time based dimension) than Mprove Charts or Dashboards.

## .gitignore Example

\`\`\`
.mprove/

*.env
.envrc

.DS_Store
Thumbs.db
\`\`\`

## Malloy Docs

When you need to look up Malloy documentation, check https://docs.malloydata.dev/documentation/user_guides/quickstart_modeling and/or other pages based on task.
` },
  { name: 'mprove-build-chart', content: `---
name: mprove-build-chart
description: Build Mprove Chart
---

# mprove-build-chart

Call \`read-docs\` tool with \`pageId: reference/chart\`

## Chart Link URL Structure

The \`run\` MCP tool returns \`RunChart\` objects with a \`url\` property containing this URL.

\`{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/{branch}/env/{env}/models/model/{modelId}/chart/{chartId}?timezone={tz}\`

## Query Parameters

### timezone

IANA timezone identifier, URL-encoded.

- \`America/New_York\` -> \`America%2FNew_York\`
- \`America/Port-au-Prince\` -> \`America%2FPort-au-Prince\`
- \`UTC\` -> \`UTC\`

Provided timezone is project's \`default_timezone\` from Mprove config.
` },
  { name: 'mprove-build-dashboard', content: `---
name: mprove-build-dashboard
description: Build Mprove Dashboard
---

# mprove-build-dashboard

Call \`read-docs\` tool with \`pageId: reference/dashboard\`

## Dashboard Link URL Structure

The \`run\` MCP tool returns \`RunDashboard\` objects with a \`url\` property containing this URL.

\`{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/{branch}/env/{env}/dashboards/dashboard/{dashboardId}?timezone={tz}\`

## Rules

If you build dashboard with top parameters (filters), then make tiles listen to top parameters.

## Query Parameters

### timezone

IANA timezone identifier, URL-encoded.

- \`America/New_York\` -> \`America%2FNew_York\`
- \`America/Port-au-Prince\` -> \`America%2FPort-au-Prince\`
- \`UTC\` -> \`UTC\`

Provided timezone is project's \`default_timezone\` from mprove config.
` },
  { name: 'mprove-build-malloy-model', content: `---
name: mprove-build-malloy-model
description: Build Mprove Model based on Malloy sources
---

# mprove-build-malloy-model

Call \`read-docs\` tool with \`pageId: reference/model-malloy\`

For Malloy documentation you can check https://docs.malloydata.dev/documentation

## Parts of Malloy language are not supported in Mprove Models yet

Do not use it:

- Malloy Nest
- Malloy Calculations
- Malloy Views

## Joins

Joins in Malloy are lazy. Actual SQL joins calculated based on selected and filtered fields.
When you build Mprove Malloy Model - join all possible leaf sources on model top source level (if they make sense).

For tables that have relationhips A->B->C:

- source A should join source B
- source A should join source C after joining B, using keys of B and C

Use this flat style instead of joining source D that already have source C joined.

Ensure that each table has its own malloy source (leaf) in a separate file for reusability.

## Mprove Model Labels

Use this pattern for top level source:

\`\`\`
#(mprove) model
#(mprove) label="Order Items (Postgres)"
#(mprove) top_label="Order Items"
source: c1_order_items is c1_order_items_tx extend {
  join_one: orders is c1_orders_tx on order_id = orders.order_id
\`\`\`

This way we remove "c1\\_" prefix in Mprove UI Model Labels.

## Build Model Metrics

Mprove Reports are based on Metrics.

When you build Mprove Malloy Model - always build metrics if dwh table schema has meaningful time field.

Use this pattern:

\`\`\`
##! experimental{sql_functions}
source: c1_orders_table is c1_postgres.table('ecommerce.orders') extend {}
source: c1_orders_tx is c1_orders_table extend {
  primary_key: order_id
  #(mprove) build_metrics field_group="Created At"
  dimension:
    created_at_ts is sql_timestamp(""" TIMESTAMP 'epoch' + \${created_at} * INTERVAL '1 second' """)
    created_at_day is created_at_ts.day
    created_at_week is created_at_ts.week
    created_at_month is created_at_ts.month
    created_at_quarter is created_at_ts.quarter
    created_at_year is created_at_ts.year
    created_at_hour is created_at_ts.hour
    created_at_minute is created_at_ts.minute
    created_at_second is created_at_ts.second
  measure: orders_count is count()
}
\`\`\`

Add \`##! experimental{sql_functions}\` malloy source tag if using sql functions like \`sql_timestamp\`.

It is important to have all time parts to be present (.day, .week, .month, etc) so user will be able to select any Time Detail in UI.

\`build_metrics\` tag creates metrics for each pair of measure and time dimension of \`field_group\`.

\`\`\`
  #(mprove) build_metrics field_group="Created At"
\`\`\`

Dimensions in \`field_group\` must be based on the same "\\_ts" field. Create "\\_ts" dimension based on time column.

Mprove \`build_metrics\` and \`field_group\` tags should be applied at the sources (prefer "\\_tx") that have useful time columns.

# Types

Use and apply Malloy types for sources that are based on tables (prefer "\\_table" suffix sources).
The type should list all columns of the source table.

https://docs.malloydata.dev/documentation/experiments/virtual_sources
` },
  { name: 'mprove-build-report', content: `---
name: mprove-build-report
description: Build Mprove Report
---

# mprove-build-report

Call \`read-docs\` tool with \`pageId: reference/report\`

## Report Link URL Structure

The \`run\` MCP tool returns \`RunReport\` objects with a \`url\` property containing this URL (defaults applied). You can use it as-is or modify query parameters.

\`{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/{branch}/env/{env}/reports/report/{reportId}?timezone={tz}&timeSpec={timeSpec}&timeRange={timeRange}\`

## Rules

If you build report with top parameters (filters), then make rows listen to top parameters.

Use single letters as row_id (A, B, C, D, etc...) and set \`options\` to an empty object as a default.

## Query Parameters

### timezone

IANA timezone identifier, URL-encoded.

- \`America/New_York\` -> \`America%2FNew_York\`
- \`America/Port-au-Prince\` -> \`America%2FPort-au-Prince\`
- \`UTC\` -> \`UTC\`

Default: project's \`default_timezone\` from Mprove config.

### timeSpec

Time granularity for report time columns. One of:

\`timestamps\` | \`seconds\` | \`minutes\` | \`hours\` | \`days\` | \`weeks\` | \`months\` | \`quarters\` | \`years\`

Default: \`days\`

### timeRange

Malloy temporal filter expression in f-backtick format.

Default: \`\` f\`last 5 days\` \`\`

To put timeRange into the URL, replace \`\` \` \`\` with \`%60\` and space with \`%20\`:

\`\` f\`last 5 days\` \`\` -> \`f%60last%205%20days%60\`

Prefer using the URL returned by the \`run\` MCP tool and only replacing the timeRange query param value when needed.

## Common timeRange Patterns

Raw values (before URL encoding):

Relative:

- \`\` f\`last 5 days\` \`\`
- \`\` f\`last 2 weeks\` \`\`
- \`\` f\`last 3 months\` \`\`
- \`\` f\`last 4 quarters\` \`\`

You can call \`read-docs\` tool with \`pageId: reference/filter-conditions\`

## Example

Report showing last 3 months by month in US Eastern time:

\`{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/main/env/prod/reports/report/{reportId}?timezone=America%2FNew_York&timeSpec=months&timeRange=f%60last%203%20months%60\`

## Notes

- \`timeSpec\` should be consistent with the \`timeRange\` unit for meaningful results (e.g., \`timeSpec=months\` with \`\` f\`last 6 months\` \`\`, \`timeSpec=days\` with \`\` f\`last 30 days\` \`\`).
- Prefer using the URL from the \`run\` MCP tool directly. Only modify query params (\`timezone\`, \`timeSpec\`, \`timeRange\`) when needed.
- Charts and dashboards only use \`timezone\` as a query parameter. Reports are unique in also having \`timeSpec\` and \`timeRange\`.
` },
  { name: 'mprove-build-store-model', content: `---
name: mprove-build-store-model
description: Build Mprove Model based on HTTP API (Store) sources
---

# mprove-build-store-model

Call \`read-docs\` tool with \`pageId: reference/model-store\`

## If user asked to create mprove model (Store) for HTTP API data source

Use \`get-connections-list\` tool to understand existing HTTP API (non-SQL) connections added by User.

Check if \`.store\` file referencing these connection already exist.

If not exist - create a new \`.store\` file for requested HTTP API connection.

You can search web for docs of requested HTTP API data source.

If user requested HTTP API data sources that is not present in \`get-connections-list\` response - ask user to add connection first. 
` },
  { name: 'mprove-connection-schemas', content: `---
name: mprove-connection-schemas
description: Get, create or update schema metadata for Mprove project connections
---

# mprove-connection-schemas

Call \`read-docs\` tool with \`pageId: dwh-schema\`

## Schema Files

Schema files provide metadata (descriptions, examples, relationships, cache_unique_values) for database tables and columns.
They are combined with raw database schemas to build "combined schemas" that are useful for creating Malloy semantic models.

## When to Use

Call \`get-connections-list\` and \`get-schemas\` tools when: 
- User requested to create or edit Mprove model based on Malloy

Call \`get-connections-list\`, \`get-schemas\` tools and create/update \`.schema\` files when: 
- User asks to setup Mprove project
- Schema file does not exist for Mprove project SQL connection
- User requested to create or update schema metadata for a SQL connection

## File Location and Naming

- Directory: \`schemas/\` inside the \`mprove_dir\` directory (e.g., \`data/schemas/\`)
- Naming: \`<connection_name>.<schema_name>.schema\`
- Example: \`c1_postgres.fleet.schema\`

## Workflow for create/update .schema files

### Step 1: Fetch Combined Schemas

Read \`/home/user/.config/opencode/mprove-session.json\` (if file exist) to get \`projectId\`, \`repoId\`, \`branchId\`, and \`envId\`.

Call \`get-connections-list\` and \`get-schemas\` MCP tools.

### Step 2: Check Existing Schema Files

Look for existing \`.schema\` files in \`data/schemas/\` if need to create/update metadata.

### Step 3: Write Schema Files

For tables of interest, call the \`get-sample\` MCP tool.

Use \`foreignKeys\` and sample data to infer relationships and to understand if we should cache unique values for the column. 

For non-sensitive data write realistic examples.

Create or update \`.schema\` files in \`data/schemas/\`. 

Guidelines:
- Include all tables and columns
- Write clear, business-oriented descriptions
- For non-sensitive data set \`example\` value
- Speficy \`cache_unique_values: true\` to recommend column unique values to be cached (good candidates are non-id string columns like \`categories\`, etc)
` },
  { name: 'mprove-project-structure', content: `---
name: mprove-project-structure
description: Mprove project files and folders structure patterns
---

# mprove-project-structure

## Connections

Connections are created by user in Mprove Server UI.
If connection name follows recommended \`<prefix>_<db-type>\` pattern - then reuse this prefix in malloy file names.
If connection name does not follow this pattern - ask user before continue - maybe he will fix it.

## Project Structure

\`\`\`
my-project/
  mprove.yml                                        # project config
  data/                                             # mprove_dir (set in mprove.yml)
    schemas/                                        # schema files
      c1_postgres.ecommerce.schema                  # <connection>.<schema>.schema
    c1_postgres/                                    # connection folder (one per database connection)
      models/
        tables/                                     # table source files
          c1_orders_tx.malloy                       # <prefix>_<table>_tx.malloy
          c1_users_tx.malloy
          c1_products_tx.malloy
          c1_user_order_facts_tx.malloy             # <prefix>_<derived_name>_tx.malloy - derived table source
        c1_order_items.malloy                       # main model file: <prefix>_<table>.malloy
      charts/
        BSANVXV135J7MF4YX32G.chart                  # <ID>.chart (auto-generated by Mprove UI)
      dashboards/
        TDEXWBE5PI2X17CJCFKC.dashboard              # <ID>.dashboard
      reports/
        IEWZFR718VMKXXIHDV5J.report                 # <ID>.report
    mprove-users/                                   # objects "saved" by users through server UI
      <user-id>/
        AFASVXV135J7MF4Y387D.chart
        FJS29ASDFJLPA7KJ8SDF.report
        JF9L7AK7J9SDF7KL8SJD.dashboard
\`\`\`

Connection folder names must match the connection name configured in Mprove server.

## mprove.yml

Project configuration file at the repository root.

\`\`\`yaml
mprove_dir: ./data
case_sensitive_string_filters: false
format_number: ""
thousands_separator: " "
currency_prefix: "$"
currency_suffix: ""
\`\`\`

- \`mprove_dir\` - path to the data directory (relative to project root)

## Models

### Table Source Files

Each database table gets its own file in \`models/tables/\`.

Naming convention: \`<prefix>_<table_name>_tx.malloy\`

- \`<prefix>\` matches the connection folder prefix (e.g. \`c1\`)
- \`_tx\` suffix indicates a table source definition

Source naming inside the file:

- \`<prefix>_<table>_table\` - raw table reference (e.g. \`c1_orders_table\`)
- \`<prefix>_<table>_tx\` - extended source with primary key, measures, dimensions (e.g. \`c1_orders_tx\`)

The raw table reference uses \`<connection>.table('<schema>.<table>')\`.

### Derived Table Sources

A derived table source imports another \`_tx\` source and produces a new \`_tx\` source.

File naming follows the same convention: \`<prefix>_<derived_name>_tx.malloy\`

Import uses relative path within \`tables/\`:

\`\`\`
import './c1_orders_tx.malloy';
\`\`\`

### Main Model Files

Main model files sit directly in \`models/\` (not in \`tables/\`).

Naming convention: \`<prefix>_<table>.malloy\`

A model file:

1. Imports table sources from \`./tables/\` using relative paths
2. Defines a source marked with \`#(mprove) model\`
3. Joins table sources together
4. Adds computed measures

Import paths use \`./tables/\`:

\`\`\`
import './tables/c1_order_items_tx.malloy';
import './tables/c1_orders_tx.malloy';
import './tables/c1_users_tx.malloy';
\`\`\`

The model source name (e.g. \`c1_order_items\`) is what charts, dashboards, and reports reference.

## Naming Conventions Summary

| Item                       | Pattern                        | Example                          |
| -------------------------- | ------------------------------ | -------------------------------- |
| Connection folder          | \`<connection_name>\`            | \`c1_postgres\`                    |
| Table source file          | \`<prefix>_<table>_tx.malloy\`   | \`c1_orders_tx.malloy\`            |
| Raw table source name      | \`<prefix>_<table>_table\`       | \`c1_orders_table\`                |
| Extended table source name | \`<prefix>_<table>_tx\`          | \`c1_orders_tx\`                   |
| Model file                 | \`<prefix>_<table>.malloy\`      | \`c1_order_items.malloy\`          |
| Model source name          | \`<prefix>_<table>\`             | \`c1_order_items\`                 |
| Schema file                | \`<connection>.<schema>.schema\` | \`c1_postgres.ecommerce.schema\`   |
| Chart file                 | \`<ID>.chart\`                   | \`BSANVXV135J7MF4YX32G.chart\`     |
| Dashboard file             | \`<ID>.dashboard\`               | \`TDEXWBE5PI2X17CJCFKC.dashboard\` |
| Report file                | \`<ID>.report\`                  | \`IEWZFR718VMKXXIHDV5J.report\`    |
` },
  { name: 'mprove-query-data', content: `---
name: mprove-query-data
description: Query chart, dashboard, report or build a new one. Answer question using data.
---

# mprove-query-data

Use \`get-state\` tool to see if project has valid Mprove models.

You can use \`get-model\` to see available fields.

You can search files by modelId to understand model main source and imported sources.

You can build a new model if current models cannot answer user question.

\`get-state\` also provides reports, dashboards and charts.

You can search files by reportId and dashboardId to understand it.

If existing reports and dashboard cannot answer user question - you create a new report or dashboard.

Instead of searching for existing charts by chartId - you can always create a new mprove chart file.

If user asks for question that can be answered using metric (time dimension + measure) - provide a report as an answer (existing report or create a new one).

If user asks for dashboard - provide dashboard (existing dashboard or create a new one).

If user asks for non-time based data - provide chart.

If you create or modify files - run \`mprove sync --env <envId>\` to validate and rebuild Mprove state.

Fix errors (if any) and call \`run\` tool.

` }
];
