// Auto-generated by build-docs.ts. Do not edit by hand.

export const SKILLS_DATA: { name: string; content: string }[] = [
  { name: 'mprove-basic', content: `---
name: mprove-basic
description: Mprove Basics
---

# mprove-basic

Use \`mprove\` CLI for \`sync\` command only. 
For other tasks, use Mprove MCP tools.

If you changed or created files, run \`mprove sync --env <env-id>\` before calling mprove mcp tools to:
- sync uncommitted changes between local repo and backend repo
- validate (rebuild) Malloy and Mprove files

If project has no \`mprove.yml\` file - you should setup Mprove project first.

## Mprove project setup

The flow for setup a new Mprove project:

- create .gitignore if not exist (or add missing parts from .gitignore example)
- load more relevant skills to context
- call \`get-schemas\` tool. If there are no connections, ask the user to create Mprove connection to database in UI before proceeding to the next step.
- create \`mprove.yml\` (if not exist)
- call \`get-state\` tool
- create \`.schema\` file for metadata and relationships (use \`get-schemas\` and \`get-sample\` tools to understand relationships)
- create Mprove model(s) based on Malloy sources
- create Mprove report, dashboard, chart
- run report, dashboard, chart
- provide report, dashboard, chart links to user

## Load more relevant skills if needed

- mprove-project-structure (Files and folders structure patterns)
- mprove-connection-schemas (\`.schema\` metadata files)
- mprove-build-malloy-model (Build Mprove Model based on Malloy sources)
- mprove-build-store-model (Build Mprove Model based on HTTP API (Store) sources)
- mprove-build-chart (Build Mprove Chart)
- mprove-build-report (Build Mprove Report)
- mprove-build-dashboard (Build Mprove Dashboard)
- mprove-query-data (Query chart, dashboard, report or build a new one. Answer question using data.)

## Notes

If YAML property has an array type - use an empty array [] instead of undefined or null value.

Mprove Reports are much more useful for Metrics (measures + time based dimension) than Mprove Charts or Dashboards.

## Docs

When you need to look up Mprove documentation, check \`https://docs.mprove.io/docs/reference/model-malloy\` and/or other pages based on task.

When you need to look up Malloy documentation, check \`https://docs.malloydata.dev/documentation/user_guides/quickstart_modeling\` and/or other pages based on task.

## .gitignore Example

\`\`\`
.mprove/

*.env
.envrc

.DS_Store
Thumbs.db
\`\`\`
` },
  { name: 'mprove-build-chart', content: `---
name: mprove-build-chart
description: Build Mprove Chart
---

# Build Mprove Chart

https://docs.mprove.io/docs/reference/chart

## Chart Link URL Structure

The \`run\` MCP tool returns \`RunChart\` objects with a \`url\` property containing this URL.

\`\`\`
{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/{branch}/env/{env}/models/model/{modelId}/chart/{chartId}?timezone={tz}
\`\`\`

## Query Parameters

### timezone

IANA timezone identifier, URL-encoded.

- \`America/New_York\` → \`America%2FNew_York\`
- \`America/Port-au-Prince\` → \`America%2FPort-au-Prince\`
- \`UTC\` → \`UTC\`

Provided timezone is project's \`default_timezone\` from mprove config.
` },
  { name: 'mprove-build-dashboard', content: `---
name: mprove-build-dashboard
description: Build Mprove Dashboard
---

# Build Mprove Dashboard

https://docs.mprove.io/docs/reference/dashboard

## Dashboard Link URL Structure

The \`run\` MCP tool returns \`RunDashboard\` objects with a \`url\` property containing this URL.

\`\`\`
{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/{branch}/env/{env}/dashboards/dashboard/{dashboardId}?timezone={tz}
\`\`\`

## Rules

If you build dashboard with top parameters (filters). Tiles should listen to them.

## Query Parameters

### timezone

IANA timezone identifier, URL-encoded.

- \`America/New_York\` → \`America%2FNew_York\`
- \`America/Port-au-Prince\` → \`America%2FPort-au-Prince\`
- \`UTC\` → \`UTC\`

Provided timezone is project's \`default_timezone\` from mprove config.
` },
  { name: 'mprove-build-malloy-model', content: `---
name: mprove-build-malloy-model
description: Build Mprove Model based on Malloy sources
---

# Build Mprove Model based on Malloy sources

## Docs

https://docs.mprove.io/docs/reference/model-malloy
https://docs.malloydata.dev/documentation

## Some parts of Malloy language are not supported in Mprove Models yet

Do not use it:

- Malloy Nest
- Malloy Calculations
- Malloy Views

## Joins

Joins in Malloy are lazy. Actual SQL joins calculated based on selected and filtered fields.
When you build Mprove Malloy Model - join all possible leaf sources on model top source level (if they make sense).

For tables that have relationhips A->B->C:

- source A should join source B
- source A should join source C after joining B, using keys of B and C

Use this flat style instead of joining source D that already have source C joined.

Ensure that each table has its own malloy source (leaf) in a separate file for reusability.

## Mprove Model Labels

Use this pattern for top level source:

\`\`\`
#(mprove) model
#(mprove) label="Order Items (Postgres)"
#(mprove) top_label="Order Items"
source: c1_order_items is c1_order_items_tx extend {
  join_one: orders is c1_orders_tx on order_id = orders.order_id
\`\`\`

This way we remove "c1\\_" prefix in Mprove UI Model Labels.

## Build Model Metrics

Mprove Reports are based on Metrics.

When you build Mprove Malloy Model - always build metrics if dwh table schema has meaningful time field.

Use this pattern:

\`\`\`
##! experimental{sql_functions}
source: c1_orders_table is c1_postgres.table('ecommerce.orders') extend {}
source: c1_orders_tx is c1_orders_table extend {
  primary_key: order_id
  #(mprove) build_metrics field_group="Created At"
  dimension:
    created_at_ts is sql_timestamp(""" TIMESTAMP 'epoch' + \${created_at} * INTERVAL '1 second' """)
    created_at_day is created_at_ts.day
    created_at_week is created_at_ts.week
    created_at_month is created_at_ts.month
    created_at_quarter is created_at_ts.quarter
    created_at_year is created_at_ts.year
    created_at_hour is created_at_ts.hour
    created_at_minute is created_at_ts.minute
    created_at_second is created_at_ts.second
  measure: orders_count is count()
}
\`\`\`

Add \`##! experimental{sql_functions}\` malloy source tag if using sql functions like \`sql_timestamp\`.

It is important to have all time parts to be present (.day, .week, .month, etc) so user will be able to select any Time Detail in UI.

These tags build metrics for all measures of Mprove Malloy Model for a field_group of time dimensions.

\`\`\`
  #(mprove) build_metrics field_group="Created At"
\`\`\`

Dimensions in field_group must be based on the same "\\_ts" field.

Mprove tags \`build_metrics\` and \`field_group\` should be applied at the sources (prefer "\\_tx") that have the time columns which are useful. Create "\\_ts" dimension based on time column.

# Types

Use and apply malloy types for sources that are based on tables (prefer "\\_table" suffix sources).
The type should list all columns of the source table.

https://docs.malloydata.dev/documentation/experiments/virtual_sources
` },
  { name: 'mprove-build-report', content: `---
name: mprove-build-report
description: Build Mprove Report
---

# Build Mprove Report

https://docs.mprove.io/docs/reference/report

## Report Link URL Structure

The \`run\` MCP tool returns \`RunReport\` objects with a \`url\` property containing this URL (defaults applied). You can use it as-is or modify query parameters.

\`\`\`
{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/{branch}/env/{env}/reports/report/{reportId}?timezone={tz}&timeSpec={timeSpec}&timeRange={timeRange}
\`\`\`

## Rules

If you build report with top parameters (filters). Rows should listen to them.

Use single letters as row_id (A, B, C, D, etc...) and "options: {}" as a default.

## Query Parameters

### timezone

IANA timezone identifier, URL-encoded.

- \`America/New_York\` → \`America%2FNew_York\`
- \`America/Port-au-Prince\` → \`America%2FPort-au-Prince\`
- \`UTC\` → \`UTC\`

Default: project's \`default_timezone\` from mprove config.

### timeSpec

Time granularity for report time columns. One of:

\`timestamps\` | \`seconds\` | \`minutes\` | \`hours\` | \`days\` | \`weeks\` | \`months\` | \`quarters\` | \`years\`

Default: \`days\`

### timeRange

Malloy temporal filter expression in f-backtick format.

Default: \`\` f\`last 5 days\` \`\`

To put timeRange into the URL, replace \`\` \` \`\` with \`%60\` and space with \`%20\`:

\`\` f\`last 5 days\` \`\` → \`f%60last%205%20days%60\`

Prefer using the URL returned by the \`run\` MCP tool and only replacing the timeRange query param value when needed.

## Common timeRange Patterns

Raw values (before URL encoding):

Relative:

- \`\` f\`last 5 days\` \`\`
- \`\` f\`last 2 weeks\` \`\`
- \`\` f\`last 3 months\` \`\`
- \`\` f\`last 4 quarters\` \`\`

https://docs.mprove.io/docs/reference/filter-conditions#timestamp

## Example

Report showing last 3 months by month in US Eastern time:

\`\`\`
{host}/org/{orgId}/project/{projectId}/repo/{repoId}/branch/main/env/prod/reports/report/{reportId}?timezone=America%2FNew_York&timeSpec=months&timeRange=f%60last%203%20months%60
\`\`\`

## Notes

- \`timeSpec\` should be consistent with the \`timeRange\` unit for meaningful results (e.g., \`timeSpec=months\` with \`\` f\`last 6 months\` \`\`, \`timeSpec=days\` with \`\` f\`last 30 days\` \`\`).
- Prefer using the URL from the \`run\` MCP tool directly. Only modify query params (\`timezone\`, \`timeSpec\`, \`timeRange\`) when needed.
- Charts and dashboards only use \`timezone\` as a query parameter. Reports are unique in also having \`timeSpec\` and \`timeRange\`.
` },
  { name: 'mprove-build-store-model', content: `---
name: mprove-build-store-model
description: Build Mprove Model based on HTTP API (Store) sources
---

# Build Mprove Model based on HTTP API (Store) sources

## Docs

https://docs.mprove.io/docs/reference/model-store

## If user asked to create mprove model (Store) for HTTP API data source

Use get-connections-list tool to understand existing HTTP API (non-SQL) connections added by User.

Check if .store files referencing these connections already exist.

If not exist - create a new .store file per HTTP API connection.

You can search web for docs of requested HTTP API data source.

If user requested HTTP API data sources that is not presend in get-connections-list response - ask user to add connection first. You can guide user based on searched HTTP API docs.

After creation of Store model:

- create mprove report, chart and dashboard
- use run tool to test
- fix errors (if any)
` },
  { name: 'mprove-connection-schemas', content: `---
name: mprove-connection-schemas
description: Get, create or update schema metadata for mprove project connections
---

# Get, create or update schema metadata for mprove project connections

## Mprove Schema Files

Schema files provide metadata (descriptions, examples, relationships) for database tables and columns.
They are combined with raw database schemas to build "combined schemas" that are useful for creating Malloy semantic models.

## When to Use

- Before creating Malloy models, to ensure combined schemas have proper metadata
- User asks to create or update schema metadata for a connection
- User asks to describe tables, columns, or relationships for a connection

## File Location and Naming

- Directory: \`schemas/\` inside the \`mprove_dir\` directory (e.g., \`data/schemas/\`)
- Naming: \`<connection_name>.<schema_name>.schema\`
- Example: \`c1_postgres.fleet.schema\`

## File Format

\`\`\`yaml
schema: <connection_name>.<schema_name>
description: 'Human-readable description of this database schema'
tables:
  - table: <table_name>
    description: 'What this table contains and its business purpose'
    columns:
      - column: <column_name>
        description: 'What this column represents'
        example: 'A realistic sample value'
        relationships:
          - to: <target_table>.<target_column>
            type: <relationship_type>
\`\`\`

## Allowed Parameters

Using unknown parameters at any level causes a validation error.

**Schema level:** \`schema\` (required), \`description\`, \`tables\` (required)

**Table level:** \`table\` (required), \`description\`, \`columns\`

**Column level:** \`column\` (required), \`description\`, \`example\`, \`relationships\`

**Relationship level:** \`to\` (required), \`type\` (required), \`to_schema\` (optional, for cross-schema)

## Relationship Rules

**Types:** \`many_to_one\`, \`one_to_many\`, \`one_to_one\`, \`many_to_many\`

**\`to\` format:** Must be \`table_name.column_name\` (exactly one dot, word characters only).

**Cross-schema:** For relationships to tables in a different schema on the same connection, add \`to_schema: <connection_name>.<other_schema_name>\`. The connection name must match the file's \`schema\` connection name.

**No duplicates:** A column cannot have two relationships with the same \`to\` (and \`to_schema\`) value.

**Mirror consistency:** If table A column X relates to table B column Y, and table B column Y also relates back to table A column X, the types must be consistent mirrors:

- \`one_to_many\` mirrors \`many_to_one\` (and vice versa)
- \`one_to_one\` mirrors \`one_to_one\`
- \`many_to_many\` mirrors \`many_to_many\`

You do not need to define both sides. Prefer \`many_to_one\` over \`one_to_many\` — define on the "many" side pointing to the "one" side. If you define both sides, ensure the types are consistent.

## Partial Coverage

You must include all tables that have relationships to other tables. For columns, only include those where you want to add descriptions, examples, or relationships. Omitted columns simply get no metadata enrichment.

## Workflow

### Step 1: Read Session Parameters

Read \`/home/user/.config/opencode/mprove-session.json\` to get \`projectId\`, \`repoId\`, \`branchId\`, and \`envId\`.

### Step 2: Fetch Combined Schemas

Call the \`get-schemas\` MCP tool:

| Parameter              | Value        |
| ---------------------- | ------------ |
| projectId              | from session |
| envId                  | from session |
| repoId                 | from session |
| branchId               | from session |
| isRefreshExistingCache | false        |

Set \`isRefreshExistingCache\` to \`true\` only if you need to refresh cached schemas from the database.

Response structure:

- \`combinedSchemaItems\` — array, each item has:
  - \`connectionId\` — connection name (e.g., \`c1_postgres\`)
  - \`schemas\` — array of \`{ schemaName, description?, tables[] }\`
    - Each table: \`{ tableName, tableType, columns[], indexes[], description? }\`
    - Each column: \`{ columnName, dataType, isNullable, isPrimaryKey?, isUnique?, foreignKeys[], description?, example?, references[] }\`
    - Each reference: \`{ relationshipType?, isForeignKey, referencedSchemaName?, referencedTableName, referencedColumnName }\`

Existing \`description\`, \`example\`, and \`references\` values come from previously written schema files.
Use \`foreignKeys\` and \`references\` arrays to infer relationships without running queries.

### Step 3: Check Existing Schema Files

Look for existing \`.schema\` files in \`data/schemas/\`. If files exist, read them to understand what metadata has already been defined.

### Step 4: Sample Data

For tables of interest, call the \`get-sample\` MCP tool:

| Parameter    | Value                               |
| ------------ | ----------------------------------- |
| projectId    | from session                        |
| envId        | from session                        |
| connectionId | e.g., \`c1_postgres\`                 |
| schemaName   | e.g., \`fleet\`                       |
| tableName    | e.g., \`trips\`                       |
| columnName   | optional — omit to get all columns  |
| offset       | optional — skip rows for pagination |

Response: \`{ columnNames: string[], rows: string[][], errorMessage? }\`

Use sample data to write meaningful descriptions and realistic examples.

### Step 5: Determine Relationship Types

If \`foreignKeys\`, \`references\`, and sample data from previous steps are not enough to determine cardinality,
you can create a custom malloy source with mprove model tag:

\`\`\`malloy
#(mprove) model
source: check is c1_postgres.table('fleet.trips') extend {
  measure:
    total_rows is count()
    distinct_vehicle_ids is count(distinct vehicle_id)
}
\`\`\`

Then create an mprove chart file and run it using mcp tool to get data (total_rows and distinct_vehicle_ids)

If \`total_rows\` equals \`distinct_vehicle_ids\`, the relationship is \`one_to_one\`.
If \`total_rows\` is greater, it is \`many_to_one\` from \`trips\` to \`vehicles\`.

### Step 6: Write Schema Files

Create or update \`.schema\` files in \`data/schemas/\`. Guidelines:

- Write clear, business-oriented descriptions (not just restating the column name)
- Use realistic but non-sensitive values for \`example\` fields (do not copy actual data from get-sample — use it only to understand the format and range)
- Only include columns that have relationships or where descriptions/examples add value
- Verify relationship types are accurate before writing

## Complete Example

\`\`\`yaml
schema: c1_postgres.fleet
description: 'Fleet management system tracking vehicles, drivers, trips, and maintenance records'
tables:
  - table: trips
    description: 'Individual vehicle trips with route, distance, and assigned driver'
    columns:
      - column: trip_id
        description: 'Unique identifier for each trip'
        example: '80234'
      - column: vehicle_id
        description: 'The vehicle used for this trip'
        example: '152'
        relationships:
          - to: vehicles.vehicle_id
            type: many_to_one
      - column: driver_id
        description: 'The driver who operated the vehicle on this trip'
        example: '38'
        relationships:
          - to: drivers.driver_id
            type: many_to_one
      - column: status
        description: 'Trip completion status'
        example: 'completed'

  - table: vehicles
    description: 'Fleet vehicles with make, model, and current operational status'
    columns:
      - column: vehicle_id
        description: 'Unique identifier for each vehicle'
        example: '152'
      - column: license_plate
        description: 'Vehicle registration plate number'
        example: 'AB-1234-CD'

  - table: drivers
    description: 'Drivers certified to operate fleet vehicles'
    columns:
      - column: driver_id
        description: 'Unique identifier for each driver'
        example: '38'
      - column: name
        description: 'Full name of the driver'
        example: 'Carlos Rivera'

  - table: maintenance_records
    description: 'Scheduled and unscheduled vehicle maintenance events'
    columns:
      - column: record_id
        description: 'Unique identifier for each maintenance record'
        example: '6010'
      - column: vehicle_id
        description: 'The vehicle that was serviced'
        example: '152'
        relationships:
          - to: vehicles.vehicle_id
            type: many_to_one
      - column: service_type
        description: 'Type of maintenance performed'
        example: 'oil change'
\`\`\`
` },
  { name: 'mprove-project-structure', content: `---
name: mprove-project-structure
description: Mprove project files and folders structure patterns
---

# Mprove project files and folders structure patterns

## Connections

Connections are created by user on mprove server.
If connection name follows recommended \`<prefix>_<db-type>\` pattern - then reuse this prefix in malloy file names.
If connection name does not follow this pattern - ask user before continue - maybe he will fix it.

## Project Structure

\`\`\`
my-project/
  mprove.yml                                        # project config
  data/                                             # mprove_dir (set in mprove.yml)
    schemas/                                        # schema descriptions (optional)
      c1_postgres.ecommerce.schema                  # <connection>.<schema>.schema
    c1_postgres/                                    # connection folder (one per database connection)
      models/
        tables/                                     # table source files
          c1_orders_tx.malloy                       # <prefix>_<table>_tx.malloy
          c1_users_tx.malloy
          c1_products_tx.malloy
          c1_user_order_facts_tx.malloy             # derived table source
        c1_order_items.malloy                       # main model file: <prefix>_<entity>.malloy
      charts/
        BSANVXV135J7MF4YX32G.chart                  # <ID>.chart (auto-generated by Mprove UI)
      dashboards/
        TDEXWBE5PI2X17CJCFKC.dashboard              # <ID>.dashboard
      reports/
        IEWZFR718VMKXXIHDV5J.report                 # <ID>.report
    mprove-users/                                   # objects "saved" by users through server UI
      <user-id>/
        AFASVXV135J7MF4Y387D.chart
        FJS29ASDFJLPA7KJ8SDF.report
        JF9L7AK7J9SDF7KL8SJD.dashboard
\`\`\`

Connection folder names must match the connection name configured in Mprove server.

## mprove.yml

Project configuration file at the repository root.

\`\`\`yaml
mprove_dir: ./data
case_sensitive_string_filters: false
format_number: ''
thousands_separator: ' '
currency_prefix: '$'
currency_suffix: ''
\`\`\`

- \`mprove_dir\` - path to the data directory (relative to project root)

## Models

### Table Source Files (\`models/tables/\`)

Each database table gets its own file in \`models/tables/\`.

Naming convention: \`<prefix>_<table_name>_tx.malloy\`

- \`<prefix>\` matches the connection folder prefix (e.g. \`c1\`)
- \`_tx\` suffix indicates a table source definition

Source naming inside the file:

- \`<prefix>_<table>_table\` - raw table reference (e.g. \`c1_orders_table\`)
- \`<prefix>_<table>_tx\` - extended source with primary key, measures, dimensions (e.g. \`c1_orders_tx\`)

The raw table reference uses \`<connection>.table('<schema>.<table>')\`.

### Derived Table Sources

A derived table source imports another \`_tx\` source and produces a new \`_tx\` source.

File naming follows the same convention: \`<prefix>_<derived_name>_tx.malloy\`

Import uses relative path within \`tables/\`:

\`\`\`
import './c1_orders_tx.malloy';
\`\`\`

### Main Model Files (\`models/\`)

Main model files sit directly in \`models/\` (not in \`tables/\`).

Naming convention: \`<prefix>_<primary_entity>.malloy\`

A model file:

1. Imports table sources from \`./tables/\` using relative paths
2. Defines a source marked with \`#(mprove) model\`
3. Joins table sources together
4. Adds computed measures

Import paths use \`./tables/\`:

\`\`\`
import './tables/c1_order_items_tx.malloy';
import './tables/c1_orders_tx.malloy';
import './tables/c1_users_tx.malloy';
\`\`\`

The model source name (e.g. \`c1_order_items\`) is what charts, dashboards, and reports reference.

## Naming Conventions Summary

| Item                       | Pattern                        | Example                          |
| -------------------------- | ------------------------------ | -------------------------------- |
| Connection folder          | \`<connection_name>\`            | \`c1_postgres\`                    |
| Table source file          | \`<prefix>_<table>_tx.malloy\`   | \`c1_orders_tx.malloy\`            |
| Raw table source name      | \`<prefix>_<table>_table\`       | \`c1_orders_table\`                |
| Extended table source name | \`<prefix>_<table>_tx\`          | \`c1_orders_tx\`                   |
| Model file                 | \`<prefix>_<entity>.malloy\`     | \`c1_order_items.malloy\`          |
| Model source name          | \`<prefix>_<entity>\`            | \`c1_order_items\`                 |
| Schema file                | \`<connection>.<schema>.schema\` | \`c1_postgres.ecommerce.schema\`   |
| Chart file                 | \`<ID>.chart\`                   | \`BSANVXV135J7MF4YX32G.chart\`     |
| Dashboard file             | \`<ID>.dashboard\`               | \`TDEXWBE5PI2X17CJCFKC.dashboard\` |
| Report file                | \`<ID>.report\`                  | \`IEWZFR718VMKXXIHDV5J.report\`    |
` },
  { name: 'mprove-query-data', content: `---
name: mprove-query-data
description: Query chart, dashboard, report or build a new one. Answer question using data.
---

# Query chart, dashboard, report or build a new one. Answer question using data.

Use get-state tool to see if project has valid mprove models.
You can use get-model to see available fields.
You can search files by modelId to understand model source and imported sources.
You can build a new model if current models cannot answer user question.

get-state also provides reports, dashboards and charts.
You can search files by reportId and dashboardId to understand it.
If existing reports and dashboard cannot answer user question - you create a new report or dashboard.

Instead of searching for existing charts by chartId - you can create a new mprove chart file.

If user asks for question that can be answered using metric (time dimension + measure) - provide a report as an answer (existing report or create a new one).

Priority:

- if metric question - use report (multiple or single rows (queries)).
- if need for multiple queries, but not all of them are metric based - use dashboard (multiple tiles (queries)).
- single query, not metric based - use chart.

If you create or modify files - run \`mprove sync --env <envId>\` to validate and rebuild mprove state.

Then:

- get-state (optional)
- get-query-info (optional)
- run
` }
];
