// Auto-generated by fetch-docs.ts. Do not edit by hand.

export const toc: readonly string[] = [
  'about',
  'access-roles',
  'builder/builder',
  'builder/editor-ai-session',
  'builder/mcp-server',
  'builder/openai-codex-setup',
  'builder/skills',
  'connections',
  'dwh-schema',
  'environments',
  'quickstart',
  'reference/chart',
  'reference/dashboard',
  'reference/filter-conditions',
  'reference/format-number',
  'reference/model-malloy',
  'reference/model-store',
  'reference/parameters',
  'reference/project-config',
  'reference/report',
  'user-roles',
  'version-control'
];
