arrowParens: avoid
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: strict
# jsxBracketSameLine: false
# jsxSingleQuote: false
# parser: babylon
printWidth: 80
proseWrap: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false