export enum ErEnum {
  // BLOCKML

  BLOCKML_WRONG_ENV_VALUES = 'BLOCKML_WRONG_ENV_VALUES',

  BLOCKML_WRONG_REQUEST_INFO_NAME = 'BLOCKML_WRONG_REQUEST_INFO_NAME',
  BLOCKML_WRONG_REQUEST_PARAMS = 'BLOCKML_WRONG_REQUEST_PARAMS',
  BLOCKML_WRONG_TEST_TRANSFORM_AND_VALIDATE = 'BLOCKML_WRONG_TEST_TRANSFORM_AND_VALIDATE',

  BLOCKML_GEN_SQL_OUTCOME_ERROR = 'BLOCKML_GEN_SQL_OUTCOME_ERROR',

  // BLOCKML_WORKER

  BLOCKML_WORKER_WRONG_REQUEST_INFO_NAME = 'BLOCKML_WORKER_WRONG_REQUEST_INFO_NAME',
  BLOCKML_WORKER_WRONG_REQUEST_PARAMS = 'BLOCKML_WORKER_WRONG_REQUEST_PARAMS',
  BLOCKML_WORKER_WRONG_TEST_TRANSFORM_AND_VALIDATE = 'BLOCKML_WORKER_WRONG_TEST_TRANSFORM_AND_VALIDATE'
}
