export enum axiosErrorsEnum {

  AXIOS_BLOCKML_POST_PROCESS_DASHBOARD = 'AXIOS_BLOCKML_POST_PROCESS_DASHBOARD',
  AXIOS_BLOCKML_POST_PROCESS_QUERY = 'AXIOS_BLOCKML_POST_PROCESS_QUERY',
  AXIOS_BLOCKML_REBUILD_STRUCT = 'AXIOS_BLOCKML_REBUILD_STRUCT',
}
