export enum bigqueryErrorsEnum {

  BIGQUERY_DATASET_EXISTS_CHECK = 'BIGQUERY_DATASET_EXISTS_CHECK',
  BIGQUERY_DATASET_CREATE = 'BIGQUERY_DATASET_CREATE',
  BIGQUERY_TABLE_DELETE = 'BIGQUERY_TABLE_DELETE',
  BIGQUERY_TABLE_EXISTS_CHECK = 'BIGQUERY_TABLE_EXISTS_CHECK',
  BIGQUERY_CREATE_COPY_JOB = 'BIGQUERY_CREATE_COPY_JOB',
  BIGQUERY_JOB_GET = 'BIGQUERY_JOB_GET',
  BIGQUERY_JOB_GET_QUERY_RESULTS = 'BIGQUERY_JOB_GET_QUERY_RESULTS',
}
