export enum fseErrorsEnum {

  FSE_EMPTY_DIR = 'FSE_EMPTY_DIR',
  FSE_ENSURE_FILE = 'FSE_ENSURE_FILE',
  FSE_ENSURE_DIR = 'FSE_ENSURE_DIR',
  FSE_READ_DIR = 'FSE_READ_DIR',
  FSE_STAT = 'FSE_STAT',
  FSE_READ_FILE = 'FSE_READ_FILE',
  FSE_PATH_EXISTS_CHECK = 'FSE_PATH_EXISTS_CHECK',
  FSE_MOVE = 'FSE_MOVE',
  FSE_REMOVE = 'FSE_REMOVE',
  FSE_WRITE_FILE = 'FSE_WRITE_FILE',
}
