export enum nodegitErrorsEnum {

  NODEGIT_REPO_OPEN = 'NODEGIT_REPO_OPEN',
  NODEGIT_REPO_GET_REMOTE = 'NODEGIT_REPO_GET_REMOTE',
  NODEGIT_REPO_MERGE_BRANCHES = 'NODEGIT_REPO_MERGE_BRANCHES',
  NODEGIT_REPO_INDEX = 'NODEGIT_REPO_INDEX',
  NODEGIT_REPO_REFRESH_INDEX = 'NODEGIT_REPO_REFRESH_INDEX',
  NODEGIT_REPO_GET_COMMIT = 'NODEGIT_REPO_GET_COMMIT',
  NODEGIT_REPO_GET_HEAD_COMMIT = 'NODEGIT_REPO_GET_HEAD_COMMIT',
  NODEGIT_REPO_CREATE_COMMIT = 'NODEGIT_REPO_CREATE_COMMIT',
  NODEGIT_REPO_FETCH = 'NODEGIT_REPO_FETCH',
  NODEGIT_REPO_GET_REFERENCE = 'NODEGIT_REPO_GET_REFERENCE',
  NODEGIT_REPO_GET_REFERENCE_COMMIT = 'NODEGIT_REPO_GET_REFERENCE_COMMIT',

  NODEGIT_INDEX_ADD_BY_PATH = 'NODEGIT_INDEX_ADD_BY_PATH',
  NODEGIT_INDEX_ADD_ALL = 'NODEGIT_INDEX_ADD_ALL',
  NODEGIT_INDEX_WRITE = 'NODEGIT_INDEX_WRITE',
  NODEGIT_INDEX_WRITE_TREE = 'NODEGIT_INDEX_WRITE_TREE',
  NODEGIT_INDEX_WRITE_TREE_TO = 'NODEGIT_INDEX_WRITE_TREE_TO',

  NODEGIT_RESET_RESET = 'NODEGIT_RESET_RESET',
  NODEGIT_REMOTE_PUSH = 'NODEGIT_REMOTE_PUSH',
  NODEGIT_CLONE = 'NODEGIT_CLONE',
  NODEGIT_INIT = 'NODEGIT_INIT',
  NODEGIT_MERGE_BASE = 'NODEGIT_MERGE_BASE',
  NODEGIT_MERGE_MERGE = 'NODEGIT_MERGE_MERGE',
  NODEGIT_REFERENCE_NAME_TO_ID = 'NODEGIT_REFERENCE_NAME_TO_ID',
  NODEGIT_COMMIT_GET_TREE = 'NODEGIT_COMMIT_GET_TREE',
  NODEGIT_ANNOTATED_COMMIT_FROM_REF = 'NODEGIT_ANNOTATED_COMMIT_FROM_REF',

  NODEGIT_DIFF_TREE_TO_TREE = 'NODEGIT_DIFF_TREE_TO_TREE',
  NODEGIT_DIFF_TREE_TO_INDEX = 'NODEGIT_DIFF_TREE_TO_INDEX',
  NODEGIT_DIFF_PATCHES = 'NODEGIT_DIFF_PATCHES',
}
