export enum typeormErrorsEnum {

  TYPEORM_GET_CONNECTION_OPTIONS = 'TYPEORM_GET_CONNECTION_OPTIONS',
  TYPEORM_CREATE_CONNECTION = 'TYPEORM_CREATE_CONNECTION',
  TYPEORM_CONNECTION_DROP_DATABASE = 'TYPEORM_CONNECTION_DROP_DATABASE',
  TYPEORM_SYNCHRONIZE = 'TYPEORM_SYNCHRONIZE',
  TYPEORM_RUN_MIGRATIONS = 'TYPEORM_RUN_MIGRATIONS',
  TYPEORM_TRANSACTION = 'TYPEORM_TRANSACTION',
}
