export enum ErEnum { // TODO: check ErEnum references
  // FRONT

  FRONT_RESPONSE_CODE_IS_NOT_201 = 'FRONT_RESPONSE_CODE_IS_NOT_201',
  FRONT_RESPONSE_INFO_STATUS_IS_NOT_OK = 'FRONT_RESPONSE_INFO_STATUS_IS_NOT_OK',

  FRONT_INSTANCE_OF_HTTP_ERROR_RESPONSE = 'FRONT_INSTANCE_OF_HTTP_ERROR_RESPONSE',
  FRONT_INSTANCE_OF_TIMEOUT_ERROR = 'FRONT_INSTANCE_OF_TIMEOUT_ERROR',
  FRONT_API_UNKNOWN_ERROR = 'FRONT_API_UNKNOWN_ERROR',

  FRONT_FORBIDDEN_REPO = 'FRONT_FORBIDDEN_REPO',
  FRONT_BRANCH_DOES_NOT_EXIST = 'FRONT_BRANCH_DOES_NOT_EXIST',
  FRONT_CANNOT_SWITCH_BRANCH_WHILE_SELECTED_REPO_HAS_UNCOMMITTED_CHANGES = 'FRONT_CANNOT_SWITCH_BRANCH_WHILE_SELECTED_REPO_HAS_UNCOMMITTED_CHANGES',
  FRONT_CURRENT_FILE_NOT_FOUND = 'FRONT_CURRENT_FILE_NOT_FOUND',

  //

  INTERNAL_ERROR = 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS_ERROR = 'TOO_MANY_REQUESTS_ERROR',
  THROTTLER_ERROR = 'THROTTLER_ERROR',

  // BACKEND

  BACKEND_APP_TERMINATED = 'BACKEND_APP_TERMINATED',
  BACKEND_UNCAUGHT_EXCEPTION = 'BACKEND_UNCAUGHT_EXCEPTION',
  BACKEND_UNHANDLED_REJECTION_REASON = 'BACKEND_UNHANDLED_REJECTION_REASON',
  BACKEND_UNHANDLED_REJECTION_ERROR = 'BACKEND_UNHANDLED_REJECTION_ERROR',

  BACKEND_WRONG_ENV_VALUES = 'BACKEND_WRONG_ENV_VALUES',

  BACKEND_HASH_SECRET_IS_NOT_DEFINED = 'BACKEND_HASH_SECRET_IS_NOT_DEFINED',
  BACKEND_DCONFIG_IS_NOT_DEFINED = 'BACKEND_DCONFIG_IS_NOT_DEFINED',

  BACKEND_ENCRYPT_METADATA_DOES_NOT_WORK_WITHOUT_ENCRYPT_DB = 'BACKEND_ENCRYPT_METADATA_DOES_NOT_WORK_WITHOUT_ENCRYPT_DB',

  BACKEND_AES_KEY_IS_NOT_DEFINED = 'BACKEND_AES_KEY_IS_NOT_DEFINED',
  BACKEND_AES_KEY_TAG_IS_NOT_DEFINED = 'BACKEND_AES_KEY_TAG_IS_NOT_DEFINED',
  BACKEND_PREV_AES_KEY_IS_DEFINED_BUT_PREV_AES_KEY_TAG_IS_NOT_DEFINED = 'BACKEND_PREV_AES_KEY_IS_DEFINED_BUT_PREV_AES_KEY_TAG_IS_NOT_DEFINED',

  BACKEND_DB_RECORD_IS_DECRYPTED_BUT_HAS_KEY_TAG = 'BACKEND_DB_RECORD_IS_DECRYPTED_BUT_HAS_KEY_TAG',
  BACKEND_DB_RECORD_HAS_BOTH_DECRYPTED_AND_ENCRYPTED_PROPS = 'BACKEND_DB_RECORD_HAS_BOTH_DECRYPTED_AND_ENCRYPTED_PROPS',
  BACKEND_DB_RECORD_HAS_NO_DECRYPTED_AND_NO_ENCRYPTED_PROPS = 'BACKEND_DB_RECORD_HAS_NO_DECRYPTED_AND_NO_ENCRYPTED_PROPS',
  BACKEND_DB_RECORD_KEY_TAG_DOES_NOT_MATCH_CURRENT_OR_PREV = 'BACKEND_DB_RECORD_KEY_TAG_DOES_NOT_MATCH_CURRENT_OR_PREV',
  BACKEND_DB_RECORDS_EXIST_WITH_KEY_TAGS_THAT_DO_NOT_MATCH_CURRENT_OR_PREV = 'BACKEND_DB_RECORDS_EXIST_WITH_KEY_TAGS_THAT_DO_NOT_MATCH_CURRENT_OR_PREV',

  BACKEND_ORG_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP = 'BACKEND_ORG_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP',
  BACKEND_PROJECT_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP = 'BACKEND_PROJECT_ID_FIRST_LETTER_DOES_NOT_MATCH_ANY_GROUP',

  BACKEND_USER_ALIAS_IS_UNDEFINED = 'BACKEND_USER_ALIAS_IS_UNDEFINED',

  BACKEND_WRONG_REQUEST_INFO_NAME = 'BACKEND_WRONG_REQUEST_INFO_NAME',
  BACKEND_WRONG_REQUEST_PARAMS = 'BACKEND_WRONG_REQUEST_PARAMS',

  BACKEND_ERROR_CODE_FROM_BACKEND = 'BACKEND_ERROR_CODE_FROM_BACKEND',

  BACKEND_ERROR_RESPONSE_FROM_DISK = 'BACKEND_ERROR_RESPONSE_FROM_DISK',
  BACKEND_ERROR_RESPONSE_FROM_BLOCKML = 'BACKEND_ERROR_RESPONSE_FROM_BLOCKML',
  BACKEND_ERROR_RESPONSE_FROM_BACKEND = 'BACKEND_ERROR_RESPONSE_FROM_BACKEND',

  BACKEND_USER_ALREADY_REGISTERED = 'BACKEND_USER_ALREADY_REGISTERED',
  BACKEND_USER_IS_NOT_INVITED = 'BACKEND_USER_IS_NOT_INVITED',

  BACKEND_USER_DOES_NOT_EXIST = 'BACKEND_USER_DOES_NOT_EXIST',

  BACKEND_THROTTLER_USER_ID_IS_NOT_DEFINED = 'BACKEND_THROTTLER_USER_ID_IS_NOT_DEFINED',

  BACKEND_DATE_CONVERSION_FAILED = 'BACKEND_DATE_CONVERSION_FAILED',

  BACKEND_USER_IS_ORG_OWNER = 'BACKEND_USER_IS_ORG_OWNER',
  BACKEND_USER_IS_THE_ONLY_PROJECT_ADMIN = 'BACKEND_USER_IS_THE_ONLY_PROJECT_ADMIN',

  BACKEND_REGISTER_TO_SET_PASSWORD = 'BACKEND_REGISTER_TO_SET_PASSWORD',
  BACKEND_WRONG_PASSWORD = 'BACKEND_WRONG_PASSWORD',

  BACKEND_UNAUTHORIZED = 'BACKEND_UNAUTHORIZED',
  BACKEND_NOT_AUTHORIZED = 'BACKEND_NOT_AUTHORIZED',
  BACKEND_WRONG_SPECIAL_KEY = 'BACKEND_WRONG_SPECIAL_KEY',

  BACKEND_UPDATE_PASSWORD_WRONG_TOKEN = 'BACKEND_UPDATE_PASSWORD_WRONG_TOKEN',
  BACKEND_UPDATE_PASSWORD_TOKEN_EXPIRED = 'BACKEND_UPDATE_PASSWORD_TOKEN_EXPIRED',

  BACKEND_TEST_ROUTES_FORBIDDEN = 'BACKEND_TEST_ROUTES_FORBIDDEN',

  BACKEND_ORG_ALREADY_EXISTS = 'BACKEND_ORG_ALREADY_EXISTS',
  BACKEND_ORG_DOES_NOT_EXIST = 'BACKEND_ORG_DOES_NOT_EXIST',
  BACKEND_FORBIDDEN_ORG = 'BACKEND_FORBIDDEN_ORG',
  BACKEND_ONLY_ORG_OWNER_CAN_ACCESS = 'BACKEND_ONLY_ORG_OWNER_CAN_ACCESS',
  BACKEND_NEW_OWNER_NOT_FOUND = 'BACKEND_NEW_OWNER_NOT_FOUND',
  BACKEND_CREATION_OF_ORGANIZATIONS_IS_FORBIDDEN = 'BACKEND_CREATION_OF_ORGANIZATIONS_IS_FORBIDDEN',

  BACKEND_NOTE_DOES_NOT_EXIST = 'BACKEND_NOTE_DOES_NOT_EXIST',

  BACKEND_PROJECT_ALREADY_EXISTS = 'BACKEND_PROJECT_ALREADY_EXISTS',
  BACKEND_PROJECT_DOES_NOT_EXIST = 'BACKEND_PROJECT_DOES_NOT_EXIST',
  BACKEND_RESTRICTED_ORGANIZATION_NAME = 'BACKEND_RESTRICTED_ORGANIZATION_NAME',
  BACKEND_RESTRICTED_ORGANIZATION = 'BACKEND_RESTRICTED_ORGANIZATION',
  BACKEND_RESTRICTED_PROJECT = 'BACKEND_RESTRICTED_PROJECT',
  BACKEND_RESTRICTED_USER = 'BACKEND_RESTRICTED_USER',

  BACKEND_MEMBER_IS_NOT_EXPLORER = 'BACKEND_MEMBER_IS_NOT_EXPLORER',
  BACKEND_MEMBER_IS_NOT_ADMIN = 'BACKEND_MEMBER_IS_NOT_ADMIN',
  BACKEND_MEMBER_IS_NOT_EDITOR = 'BACKEND_MEMBER_IS_NOT_EDITOR',
  BACKEND_MEMBER_IS_NOT_EDITOR_OR_ADMIN = 'BACKEND_MEMBER_IS_NOT_EDITOR_OR_ADMIN',
  BACKEND_MEMBER_ALREADY_EXISTS = 'BACKEND_MEMBER_ALREADY_EXISTS',
  BACKEND_MEMBER_DOES_NOT_EXIST = 'BACKEND_MEMBER_DOES_NOT_EXIST',
  BACKEND_ADMIN_CANNOT_DELETE_HIMSELF = 'BACKEND_ADMIN_CANNOT_DELETE_HIMSELF',
  BACKEND_ADMIN_CANNOT_CHANGE_HIS_ADMIN_STATUS = 'BACKEND_ADMIN_CANNOT_CHANGE_HIS_ADMIN_STATUS',

  BACKEND_CONNECTION_ALREADY_EXISTS = 'BACKEND_CONNECTION_ALREADY_EXISTS',
  BACKEND_CONNECTION_DOES_NOT_EXIST = 'BACKEND_CONNECTION_DOES_NOT_EXIST',

  BACKEND_FORBIDDEN_REPO = 'BACKEND_FORBIDDEN_REPO',

  BACKEND_MANUAL_COMMIT_TO_PRODUCTION_REPO_IS_FORBIDDEN = 'BACKEND_MANUAL_COMMIT_TO_PRODUCTION_REPO_IS_FORBIDDEN',

  BACKEND_BRANCH_ALREADY_EXISTS = 'BACKEND_BRANCH_ALREADY_EXISTS',
  BACKEND_BRANCH_DOES_NOT_EXIST = 'BACKEND_BRANCH_DOES_NOT_EXIST',
  BACKEND_DEFAULT_BRANCH_CANNOT_BE_DELETED = 'BACKEND_DEFAULT_BRANCH_CANNOT_BE_DELETED',

  BACKEND_BRIDGE_BRANCH_ENV_DOES_NOT_EXIST = 'BACKEND_BRIDGE_BRANCH_ENV_DOES_NOT_EXIST',

  BACKEND_ENV_ALREADY_EXISTS = 'BACKEND_ENV_ALREADY_EXISTS',
  BACKEND_ENV_DOES_NOT_EXIST = 'BACKEND_ENV_DOES_NOT_EXIST',
  BACKEND_MEMBER_DOES_NOT_HAVE_ACCESS_TO_ENV = 'BACKEND_MEMBER_DOES_NOT_HAVE_ACCESS_TO_ENV',
  BACKEND_ENV_PROD_CANNOT_BE_DELETED = 'BACKEND_ENV_PROD_CANNOT_BE_DELETED',

  BACKEND_EV_ALREADY_EXISTS = 'BACKEND_EV_ALREADY_EXISTS',
  BACKEND_EV_DOES_NOT_EXIST = 'BACKEND_EV_DOES_NOT_EXIST',

  BACKEND_ENV_USER_ALREADY_EXISTS = 'BACKEND_ENV_USER_ALREADY_EXISTS',

  BACKEND_MODEL_ID_IS_NOT_DEFINED = 'BACKEND_MODEL_ID_IS_NOT_DEFINED',
  BACKEND_MODEL_DOES_NOT_EXIST = 'BACKEND_MODEL_DOES_NOT_EXIST',
  BACKEND_FORBIDDEN_MODEL = 'BACKEND_FORBIDDEN_MODEL',

  BACKEND_CHART_IS_NOT_DRAFT = 'BACKEND_CHART_IS_NOT_DRAFT',
  BACKEND_CHART_CREATOR_ID_MISMATCH = 'BACKEND_CHART_CREATOR_ID_MISMATCH',

  BACKEND_DASHBOARD_DOES_NOT_EXIST = 'BACKEND_DASHBOARD_DOES_NOT_EXIST',
  BACKEND_FORBIDDEN_DASHBOARD = 'BACKEND_FORBIDDEN_DASHBOARD',
  BACKEND_FORBIDDEN_DASHBOARD_PATH = 'BACKEND_FORBIDDEN_DASHBOARD_PATH',
  BACKEND_DASHBOARD_CREATOR_ID_MISMATCH = 'BACKEND_DASHBOARD_CREATOR_ID_MISMATCH',
  BACKEND_MCONFIG_PARENT_ID_MISMATCH = 'BACKEND_MCONFIG_PARENT_ID_MISMATCH',
  BACKEND_TILE_MCONFIG_ID_MISMATCH = 'BACKEND_TILE_MCONFIG_ID_MISMATCH',

  BACKEND_CHART_DOES_NOT_EXIST = 'BACKEND_CHART_DOES_NOT_EXIST',
  BACKEND_FORBIDDEN_CHART_PATH = 'BACKEND_FORBIDDEN_CHART_PATH',

  BACKEND_REPORT_DOES_NOT_EXIST = 'BACKEND_REPORT_DOES_NOT_EXIST',
  BACKEND_FORBIDDEN_REPORT = 'BACKEND_FORBIDDEN_REPORT',
  BACKEND_FORBIDDEN_REPORT_PATH = 'BACKEND_FORBIDDEN_REPORT_PATH',
  BACKEND_REPORT_NOT_FOUND = 'BACKEND_REPORT_NOT_FOUND',
  BACKEND_REPORT_CREATOR_ID_MISMATCH = 'BACKEND_REPORT_CREATOR_ID_MISMATCH',

  BACKEND_MCONFIG_DOES_NOT_EXIST = 'BACKEND_MCONFIG_DOES_NOT_EXIST',

  BACKEND_STRUCT_DOES_NOT_EXIST = 'BACKEND_STRUCT_DOES_NOT_EXIST',

  BACKEND_STRUCT_ID_CHANGED = 'BACKEND_STRUCT_ID_CHANGED',

  BACKEND_WRONG_MOTHERDUCK_DATABASE_CHARACTERS = 'BACKEND_WRONG_MOTHERDUCK_DATABASE_CHARACTERS',

  BACKEND_QUERY_DOES_NOT_EXIST = 'BACKEND_QUERY_DOES_NOT_EXIST',

  BACKEND_QUERIES_DO_NOT_EXIST = 'BACKEND_QUERIES_DO_NOT_EXIST',

  BACKEND_MCONFIG_QUERY_ID_MISMATCH = 'BACKEND_MCONFIG_QUERY_ID_MISMATCH',

  BACKEND_OLD_MCONFIG_MISMATCH = 'BACKEND_OLD_MCONFIG_MISMATCH',

  BACKEND_SCHEDULER_CHECK_BIGQUERY_RUNNING_QUERIES = 'BACKEND_SCHEDULER_CHECK_BIGQUERY_RUNNING_QUERIES',
  BACKEND_SCHEDULER_CHECK_BIGQUERY_RUNNING_QUERY = 'BACKEND_SCHEDULER_CHECK_BIGQUERY_RUNNING_QUERY',
  BACKEND_SCHEDULER_REMOVE_STRUCTS = 'BACKEND_SCHEDULER_REMOVE_STRUCTS',
  BACKEND_SCHEDULER_REMOVE_QUERIES = 'BACKEND_SCHEDULER_REMOVE_QUERIES',
  BACKEND_SCHEDULER_REMOVE_NOTES = 'BACKEND_SCHEDULER_REMOVE_NOTES',

  BACKEND_BIGQUERY_CANCEL_QUERY_JOB_FAIL = 'BACKEND_BIGQUERY_CANCEL_QUERY_JOB_FAIL',

  BACKEND_AVATAR_DOES_NOT_EXIST = 'BACKEND_AVATAR_DOES_NOT_EXIST',

  BACKEND_TRANSACTION_RETRY = 'BACKEND_TRANSACTION_RETRY',
  BACKEND_GET_IDEMP_RESP_RETRY = 'BACKEND_GET_IDEMP_RESP_RETRY',
  BACKEND_GET_IDEMP_RESP_RETRY_FAILED = 'BACKEND_GET_IDEMP_RESP_RETRY_FAILED',

  BACKEND_APP_FILTER_SAVE_IDEMP_ERROR = 'BACKEND_APP_FILTER_SAVE_IDEMP_ERROR',
  BACKEND_APP_FILTER_ERROR = 'BACKEND_APP_FILTER_ERROR',

  BACKEND_GET_DASHBOARD_FAIL = 'BACKEND_GET_DASHBOARD_FAIL',
  BACKEND_CREATE_DRAFT_DASHBOARD_FAILED = 'BACKEND_CREATE_DRAFT_DASHBOARD_FAILED',
  BACKEND_EDIT_DRAFT_DASHBOARD_FAILED = 'BACKEND_EDIT_DRAFT_DASHBOARD_FAILED',
  BACKEND_CREATE_DASHBOARD_FAIL = 'BACKEND_CREATE_DASHBOARD_FAIL',
  BACKEND_MODIFY_DASHBOARD_FAIL = 'BACKEND_MODIFY_DASHBOARD_FAIL',

  BACKEND_CREATE_CHART_FAIL = 'BACKEND_CREATE_CHART_FAIL',
  BACKEND_MODIFY_CHART_FAIL = 'BACKEND_MODIFY_CHART_FAIL',

  BACKEND_CREATE_REPORT_FAIL = 'BACKEND_CREATE_REPORT_FAIL',
  BACKEND_MODIFY_REPORT_FAIL = 'BACKEND_MODIFY_REPORT_FAIL',

  BACKEND_WRONG_TIME_RANGE = 'BACKEND_WRONG_TIME_RANGE',

  BACKEND_SUGGEST_FIELD_NOT_FOUND = 'BACKEND_SUGGEST_FIELD_NOT_FOUND',

  BACKEND_RUN_QUERIES_POOL_ERROR = 'BACKEND_RUN_QUERIES_POOL_ERROR',
  BACKEND_RUN_QUERY_SNOWFLAKE_ERROR = 'BACKEND_RUN_QUERY_SNOWFLAKE_ERROR',
  // BACKEND_RUN_QUERY_CLICKHOUSE_ERROR = 'BACKEND_RUN_QUERY_CLICKHOUSE_ERROR',
  BACKEND_RUN_QUERY_POSTGRES_ERROR = 'BACKEND_RUN_QUERY_POSTGRES_ERROR',
  BACKEND_RUN_QUERY_MYSQL_ERROR = 'BACKEND_RUN_QUERY_MYSQL_ERROR',
  BACKEND_RUN_QUERY_PRESTO_ERROR = 'BACKEND_RUN_QUERY_PRESTO_ERROR',
  BACKEND_RUN_QUERY_TRINO_ERROR = 'BACKEND_RUN_QUERY_TRINO_ERROR',
  BACKEND_RUN_QUERY_DUCKDB_ERROR = 'BACKEND_RUN_QUERY_DUCKDB_ERROR',
  BACKEND_RUN_QUERY_API_ERROR = 'BACKEND_RUN_QUERY_API_ERROR',

  BACKEND_SNOWFLAKE_FAILED_TO_CONNECT = 'BACKEND_SNOWFLAKE_FAILED_TO_CONNECT',
  BACKEND_SNOWFLAKE_FAILED_TO_DESTROY_CONNECTION = 'BACKEND_SNOWFLAKE_FAILED_TO_DESTROY_CONNECTION',

  BACKEND_MALLOY_CONNECTION_CLOSE_ERROR = 'BACKEND_MALLOY_CONNECTION_CLOSE_ERROR',
  BACKEND_MYSQL_CONNECTION_CLOSE_ERROR = 'BACKEND_MYSQL_CONNECTION_CLOSE_ERROR',

  BACKEND_STORE_API_INVALID_URL = 'BACKEND_STORE_API_INVALID_URL',
  BACKEND_STORE_API_PROTOCOL_MUST_BE_HTTPS = 'BACKEND_STORE_API_PROTOCOL_MUST_BE_HTTPS',
  BACKEND_STORE_API_HOST_IS_BLOCKED_BY_LIST = 'BACKEND_STORE_API_HOST_IS_BLOCKED_BY_LIST',
  BACKEND_STORE_API_HOST_IS_BLOCKED_BY_SPEC = 'BACKEND_STORE_API_HOST_IS_BLOCKED_BY_SPEC',
  BACKEND_STORE_API_HOST_IS_BLOCKED_BY_SUFFIX = 'BACKEND_STORE_API_HOST_IS_BLOCKED_BY_SUFFIX',
  BACKEND_STORE_API_HOST_IS_BLOCKED_BY_IP = 'BACKEND_STORE_API_HOST_IS_BLOCKED_BY_IP',
  BACKEND_STORE_API_HOST_DNS_LOOKUP_FAILED = 'BACKEND_STORE_API_HOST_IS_BLOCKED_BY_IP',

  BACKEND_TEST_CONNECTION_RESULT_IS_NOT_DEFINED = 'BACKEND_TEST_CONNECTION_RESULT_IS_NOT_DEFINED',

  BACKEND_FORWARD_TELEMETRY_LOGS_ERROR = 'BACKEND_FORWARD_TELEMETRY_LOGS_ERROR',
  BACKEND_FORWARD_TELEMETRY_METRICS_ERROR = 'BACKEND_FORWARD_TELEMETRY_METRICS_ERROR',
  BACKEND_FORWARD_TELEMETRY_TRACES_ERROR = 'BACKEND_FORWARD_TELEMETRY_TRACES_ERROR',

  // DISK

  DISK_APP_TERMINATED = 'DISK_APP_TERMINATED',
  DISK_UNCAUGHT_EXCEPTION = 'DISK_UNCAUGHT_EXCEPTION',
  DISK_UNHANDLED_REJECTION_REASON = 'DISK_UNHANDLED_REJECTION_REASON',
  DISK_UNHANDLED_REJECTION_ERROR = 'DISK_UNHANDLED_REJECTION_ERROR',

  DISK_WRONG_ENV_VALUES = 'DISK_WRONG_ENV_VALUES',

  DISK_WRONG_REQUEST_INFO_NAME = 'DISK_WRONG_REQUEST_INFO_NAME',
  DISK_WRONG_REQUEST_PARAMS = 'DISK_WRONG_REQUEST_PARAMS',

  DISK_ORG_ALREADY_EXIST = 'DISK_ORG_ALREADY_EXIST',
  DISK_ORG_IS_NOT_EXIST = 'DISK_ORG_IS_NOT_EXIST',

  DISK_PROJECT_ALREADY_EXIST = 'DISK_PROJECT_ALREADY_EXIST',
  DISK_PROJECT_IS_NOT_EXIST = 'DISK_PROJECT_IS_NOT_EXIST',

  DISK_REPO_ALREADY_EXIST = 'DISK_REPO_ALREADY_EXIST',
  DISK_REPO_IS_NOT_EXIST = 'DISK_REPO_IS_NOT_EXIST',

  DISK_REPO_IS_NOT_CLEAN_FOR_CHECKOUT_BRANCH = 'DISK_REPO_IS_NOT_CLEAN_FOR_CHECKOUT_BRANCH',
  DISK_REPO_STATUS_IS_NOT_NEED_PUSH = 'DISK_REPO_STATUS_IS_NOT_NEED_PUSH',

  DISK_DEV_REPO_COMMIT_DOES_NOT_MATCH_LOCAL_COMMIT = 'DISK_DEV_REPO_COMMIT_DOES_NOT_MATCH_LOCAL_COMMIT',

  DISK_BRANCH_ALREADY_EXIST = 'DISK_BRANCH_ALREADY_EXIST',
  DISK_BRANCH_IS_NOT_EXIST = 'DISK_BRANCH_IS_NOT_EXIST',
  DISK_THEIR_BRANCH_IS_NOT_EXIST = 'DISK_THEIR_BRANCH_IS_NOT_EXIST',
  DISK_DEFAULT_BRANCH_CANNOT_BE_DELETED = 'DISK_DEFAULT_BRANCH_CANNOT_BE_DELETED',

  DISK_NEW_PATH_ALREADY_EXIST = 'DISK_NEW_PATH_ALREADY_EXIST',
  DISK_TO_PATH_ALREADY_EXIST = 'DISK_TO_PATH_ALREADY_EXIST',

  DISK_PARENT_PATH_IS_NOT_EXIST = 'DISK_PARENT_PATH_IS_NOT_EXIST',
  DISK_FROM_PATH_IS_NOT_EXIST = 'DISK_FROM_PATH_IS_NOT_EXIST',
  DISK_OLD_PATH_IS_NOT_EXIST = 'DISK_OLD_PATH_IS_NOT_EXIST',

  DISK_FOLDER_ALREADY_EXIST = 'DISK_FOLDER_ALREADY_EXIST',
  DISK_FOLDER_IS_NOT_EXIST = 'DISK_FOLDER_IS_NOT_EXIST',

  DISK_FILE_ALREADY_EXIST = 'DISK_FILE_ALREADY_EXIST',
  DISK_FILE_IS_NOT_EXIST = 'DISK_FILE_IS_NOT_EXIST',

  // BLOCKML

  BLOCKML_APP_TERMINATED = 'BLOCKML_APP_TERMINATED',
  BLOCKML_UNCAUGHT_EXCEPTION = 'BLOCKML_UNCAUGHT_EXCEPTION',
  BLOCKML_UNHANDLED_REJECTION_REASON = 'BLOCKML_UNHANDLED_REJECTION_REASON',
  BLOCKML_UNHANDLED_REJECTION_ERROR = 'BLOCKML_UNHANDLED_REJECTION_ERROR',

  BLOCKML_WRONG_ENV_VALUES = 'BLOCKML_WRONG_ENV_VALUES',

  BLOCKML_WRONG_REQUEST_INFO_NAME = 'BLOCKML_WRONG_REQUEST_INFO_NAME',
  BLOCKML_WRONG_REQUEST_PARAMS = 'BLOCKML_WRONG_REQUEST_PARAMS',

  BLOCKML_MALLOY_CONNECTION_CLOSE_ERROR = 'BLOCKML_MALLOY_CONNECTION_CLOSE_ERROR',

  BLOCKML_LOAD_PRESETS_FAILED = 'BLOCKML_LOAD_PRESETS_FAILED',

  // MCLI

  MCLI_APP_TERMINATED = 'MCLI_APP_TERMINATED',
  MCLI_UNCAUGHT_EXCEPTION = 'MCLI_UNCAUGHT_EXCEPTION',
  MCLI_UNHANDLED_REJECTION_REASON = 'MCLI_UNHANDLED_REJECTION_REASON',
  MCLI_UNHANDLED_REJECTION_ERROR = 'MCLI_UNHANDLED_REJECTION_ERROR',

  MCLI_WRONG_ENV_VALUES = 'MCLI_WRONG_ENV_VALUES',

  MCLI_ERROR_RESPONSE_FROM_BACKEND = 'MCLI_ERROR_RESPONSE_FROM_BACKEND',

  MCLI_DASHBOARD_NOT_FOUND = 'MCLI_DASHBOARD_NOT_FOUND',
  MCLI_CHART_NOT_FOUND = 'MCLI_CHART_NOT_FOUND',

  MCLI_PROJECT_ID_IS_NOT_DEFINED = 'MCLI_PROJECT_ID_IS_NOT_DEFINED',
  MCLI_DASHBOARD_ID_CHART_ID_AND_REPORT_ID_ARE_NOT_DEFINED = 'MCLI_DASHBOARD_ID_CHART_ID_AND_REPORT_ID_ARE_NOT_DEFINED',
  MCLI_MUTUALLY_EXCLUSIVE_FLAGS = 'MCLI_MUTUALLY_EXCLUSIVE_FLAGS',
  MCLI_SLEEP_SECONDS_DOES_NOT_WORK_WITHOUT_WAIT = 'MCLI_SLEEP_SECONDS_DOES_NOT_WORK_WITHOUT_WAIT',
  MCLI_TILE_INDEX_DOES_NOT_WORK_WITHOUT_DASHBOARD_ID = 'MCLI_TILE_INDEX_DOES_NOT_WORK_WITHOUT_DASHBOARD_ID',
  MCLI_ROW_ID_DOES_NOT_WORK_WITHOUT_REPORT_ID = 'MCLI_ROW_ID_DOES_NOT_WORK_WITHOUT_REPORT_ID',
  MCLI_SYNC_FAILED = 'MCLI_SYNC_FAILED',

  MCLI_TEST_RETRY = 'MCLI_TEST_RETRY',

  // NODE COMMON

  FILE_SIZE_IS_TOO_BIG = 'FILE_SIZE_IS_TOO_BIG',
  MALLOY_TO_QUERY_FAILED = 'MALLOY_TO_QUERY_FAILED',

  // COMMON

  ENV_VAR_VALUE_MUST_BE_TRUE_OR_FALSE = 'ENV_VAR_VALUE_MUST_BE_TRUE_OR_FALSE'
}
