arrowParens: avoid
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: strict
# jsxBracketSameLine: false
# jsxSingleQuote: false
# parser: babylon
printWidth: 80
proseWrap: preserve
semi: true
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false

# see vscode settings https://github.com/prettier/prettier-vscode

# prettier.eslintIntegration
# prettier.tslintIntegration
# prettier.stylelintIntegration
# prettier.requireConfig
# prettier.ignorePath
# prettier.disableLanguages - used in vscode settings