version: '3.7'
services:
  rabbit:
    image: rabbitmq:3-management
    # volumes:
    #   - type: bind
    #     source: ./.docker/rabbitmq/etc/
    #     target: /etc/rabbitmq/   
    #   - type: bind
    #     source: ./.docker/rabbitmq/data/
    #     target: /var/lib/rabbitmq/  
    #   - type: bind
    #     source: ./.docker/rabbitmq/logs/
    #     target: /var/log/rabbitmq/    
    environment:
      RABBITMQ_ERLANG_COOKIE: $RABBITMQ_ERLANG_COOKIE
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    ports:
      - 5672:5672
      - 15672:15672

  m-backend:
    image: mprove/mprove-base-m-backend:$MPROVE_BASE_RELEASE_TAG 
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS     
    ports:
      - 3000:3000 

  m-disk:
    image: mprove/mprove-base-m-disk:$MPROVE_BASE_RELEASE_TAG
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
      MPROVE_M_DATA_ORGANIZATIONS_PATH: $MPROVE_M_DATA_ORGANIZATIONS_PATH     
    volumes:
      - type: bind
        source: $MPROVE_M_DATA_ORGANIZATIONS_PATH
        target: $MPROVE_M_DATA_ORGANIZATIONS_PATH

    
      

