version: '3.7'

secrets:
  fluent_key:
    file: $MPROVE_M_DATA_FLUENT_KEY_PATH

services:
  fluent:
    container_name: fluent
    image: mprove/mprove-base-m-fluent:$MPROVE_BASE_RELEASE_TAG
    env_file:
      - $ENV_FILE_PATH    
    secrets:
      - fluent_key
    volumes:
      - type: bind
        source: $MPROVE_M_DATA_FLUENT_LOG_PATH
        target: /fluentd/log      
    ports:
      - 24224:24224

  db:
    image: mysql:8
    env_file:
      - $ENV_FILE_PATH    
    command: ['--default-authentication-plugin=mysql_native_password', '--max_allowed_packet=128M']
    volumes:
      - type: bind
        source: $MPROVE_M_DATA_MYSQL_PATH
        target: /var/lib/mysql      
    ports:
      - 3306:3306         
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: db   

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    env_file:
      - $ENV_FILE_PATH    
    volumes:
    #   - type: bind
    #     source: ./.docker/rabbitmq/etc/
    #     target: /etc/rabbitmq/      
      - type: bind
        source: $MPROVE_M_DATA_RABBIT_DATA_PATH
        target:  /var/lib/rabbitmq/  
      - type: bind
        source: $MPROVE_M_DATA_RABBIT_LOG_PATH
        target: /var/log/rabbitmq/     
    ports:
      - 5672:5672
      - 15672:15672
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: rabbit

  m-backend:
    container_name: m-backend
    image: mprove/mprove-base-m-backend:$MPROVE_BASE_RELEASE_TAG 
    env_file:
      - $ENV_FILE_PATH    
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: $ENV_FILE_PATH
        target: $ENV_FILE_PATH      
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: m-backend    

  m-blockml:
    container_name: m-blockml
    image: mprove/mprove-base-m-blockml:$MPROVE_BASE_RELEASE_TAG 
    env_file:
      - $ENV_FILE_PATH    
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: m-blockml

  m-blockml-worker:
    image: mprove/mprove-base-m-blockml:$MPROVE_BASE_RELEASE_TAG 
    env_file:
      - $ENV_FILE_PATH    
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: m-blockml-worker

  m-disk:
    container_name: m-disk
    image: mprove/mprove-base-m-disk:$MPROVE_BASE_RELEASE_TAG
    env_file:
      - $ENV_FILE_PATH    
    volumes:
      - type: bind
        source: $MPROVE_M_DATA_ORGANIZATIONS_PATH
        target: $MPROVE_M_DATA_ORGANIZATIONS_PATH
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: m-disk      


    
      

