import { ngrxType } from '@app/ngrx/ngrx-type';

export const COMMIT_REPO = ngrxType('COMMIT_REPO');
export const COMMIT_REPO_SUCCESS = ngrxType('COMMIT_REPO_SUCCESS');
export const COMMIT_REPO_FAIL = ngrxType('COMMIT_REPO_FAIL');

export const PULL_REPO = ngrxType('PULL_REPO');
export const PULL_REPO_SUCCESS = ngrxType('PULL_REPO_SUCCESS');
export const PULL_REPO_FAIL = ngrxType('PULL_REPO_FAIL');

export const PUSH_REPO = ngrxType('PUSH_REPO');
export const PUSH_REPO_SUCCESS = ngrxType('PUSH_REPO_SUCCESS');
export const PUSH_REPO_FAIL = ngrxType('PUSH_REPO_FAIL');

export const REGENERATE_REPO_REMOTE_PUBLIC_KEY = ngrxType(
  'REGENERATE_REPO_REMOTE_PUBLIC_KEY'
);
export const REGENERATE_REPO_REMOTE_PUBLIC_KEY_SUCCESS = ngrxType(
  'REGENERATE_REPO_REMOTE_PUBLIC_KEY_SUCCESS'
);
export const REGENERATE_REPO_REMOTE_PUBLIC_KEY_FAIL = ngrxType(
  'REGENERATE_REPO_REMOTE_PUBLIC_KEY_FAIL'
);

export const REGENERATE_REPO_REMOTE_WEBHOOK = ngrxType(
  'REGENERATE_REPO_REMOTE_WEBHOOK'
);
export const REGENERATE_REPO_REMOTE_WEBHOOK_SUCCESS = ngrxType(
  'REGENERATE_REPO_REMOTE_WEBHOOK_SUCCESS'
);
export const REGENERATE_REPO_REMOTE_WEBHOOK_FAIL = ngrxType(
  'REGENERATE_REPO_REMOTE_WEBHOOK_FAIL'
);

export const REVERT_REPO_TO_PRODUCTION = ngrxType('REVERT_REPO_TO_PRODUCTION');
export const REVERT_REPO_TO_PRODUCTION_SUCCESS = ngrxType(
  'REVERT_REPO_TO_PRODUCTION_SUCCESS'
);
export const REVERT_REPO_TO_PRODUCTION_FAIL = ngrxType(
  'REVERT_REPO_TO_PRODUCTION_FAIL'
);

export const REVERT_REPO_TO_LAST_COMMIT = ngrxType(
  'REVERT_REPO_TO_LAST_COMMIT'
);
export const REVERT_REPO_TO_LAST_COMMIT_SUCCESS = ngrxType(
  'REVERT_REPO_TO_LAST_COMMIT_SUCCESS'
);
export const REVERT_REPO_TO_LAST_COMMIT_FAIL = ngrxType(
  'REVERT_REPO_TO_LAST_COMMIT_FAIL'
);

export const SET_REPO_REMOTE_URL = ngrxType('SET_REPO_REMOTE_URL');
export const SET_REPO_REMOTE_URL_SUCCESS = ngrxType(
  'SET_REPO_REMOTE_URL_SUCCESS'
);
export const SET_REPO_REMOTE_URL_FAIL = ngrxType('SET_REPO_REMOTE_URL_FAIL');
