apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.certProdSecretName }}
  namespace: istio-system
spec:
  secretName: {{ .Values.ingress.certProdSecretName }}
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
{{- if .Values.ingress.routeGrafana.enabled }}
  - {{ .Values.ingress.routeGrafana.host }}
{{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io  

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.certStagingSecretName }}
  namespace: istio-system
spec:
  secretName: {{ .Values.ingress.certStagingSecretName }}
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
{{- if .Values.ingress.routeGrafana.enabled }}
  - {{ .Values.ingress.routeGrafana.host }}
{{- end }}   
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io 