apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.ingress.host }}
{{- if .Values.ingress.routeGrafana.enabled }}
    - {{ .Values.ingress.routeGrafana.host }}
{{- end }}    
    port:
      name: http
      number: 80
      protocol: HTTP2
    tls:
      httpsRedirect: false
  - hosts:
    - {{ .Values.ingress.host }}
{{- if .Values.ingress.routeGrafana.enabled }}
    - {{ .Values.ingress.routeGrafana.host }}
{{- end }}    
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.ingress.certProdSecretName }}
