{{- if .Values.ingress.routeGrafana.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route-grafana
spec:
  hosts:
  - {{ .Values.ingress.routeGrafana.host }}
  gateways:
  - istio-system/gateway
  http:
  - route:
    - destination:
        host: {{ .Values.ingress.routeGrafana.destination }}
        port:
          number: 80
{{- end }}          