apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route-integra
spec:
  hosts:
  - front
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: backend
        port:
          number: 3000 
  - route:
    - destination:
        host: front
        port:
          number: 80