// Auto-generated by build-docs.mjs. Do not edit by hand.

export const toc: readonly string[] = [
  'about.mdx',
  'access-roles.mdx',
  'builder/builder.mdx',
  'builder/editor-ai-session.mdx',
  'builder/mcp-server.mdx',
  'builder/openai-codex-setup.mdx',
  'builder/skills.mdx',
  'connections.mdx',
  'docs-for-ai.mdx',
  'dwh-schema.mdx',
  'environments.mdx',
  'quickstart.mdx',
  'reference/chart.mdx',
  'reference/dashboard.mdx',
  'reference/filter-conditions.mdx',
  'reference/format-number.mdx',
  'reference/model-malloy.mdx',
  'reference/model-store.mdx',
  'reference/parameters.mdx',
  'reference/project-config.mdx',
  'reference/report.mdx',
  'user-roles.mdx',
  'version-control.mdx'
];
