export enum schedulerErrorsEnum {
  SCHEDULER_DELETE_SESSIONS = 'SCHEDULER_DELETE_SESSIONS',
  SCHEDULER_DELETE_PROJECTS = 'SCHEDULER_DELETE_PROJECTS',
  SCHEDULER_DELETE_QUERIES = 'SCHEDULER_DELETE_QUERIES',
  SCHEDULER_DELETE_PDTS = 'SCHEDULER_DELETE_PDTS',
  SCHEDULER_DELETE_MEMBERS = 'SCHEDULER_DELETE_MEMBERS',
  SCHEDULER_DELETE_USERS = 'SCHEDULER_DELETE_USERS',
  SCHEDULER_PING = 'SCHEDULER_PING',
  SCHEDULER_RESEND_MESSAGE = 'SCHEDULER_RESEND_MESSAGE',
  SCHEDULER_CHECK_QUERIES = 'SCHEDULER_CHECK_QUERIES',
  SCHEDULER_CHECK_PDT_TIME = 'SCHEDULER_CHECK_PDT_TIME',
  SCHEDULER_START_TRIGGER_SQL_JOB = 'SCHEDULER_START_TRIGGER_SQL_JOB',
  SCHEDULER_CHECK_TRIGGER_SQL_JOB_BIGQUERY = 'SCHEDULER_CHECK_TRIGGER_SQL_JOB_BIGQUERY',
  SCHEDULER_START_PDT = 'SCHEDULER_START_PDT',
  SCHEDULER_CHECK_CHUNKS = 'SCHEDULER_CHECK_CHUNKS'
}
