import { ngrxType } from '@app/ngrx/ngrx-type';

export const DELETE_PROJECT_CREDENTIALS = ngrxType(
  'DELETE_PROJECT_CREDENTIALS'
);
export const DELETE_PROJECT_CREDENTIALS_SUCCESS = ngrxType(
  'DELETE_PROJECT_CREDENTIALS_SUCCESS'
);
export const DELETE_PROJECT_CREDENTIALS_FAIL = ngrxType(
  'DELETE_PROJECT_CREDENTIALS_FAIL'
);
