#!/usr/bin/env bash
set -euo pipefail

trap 'echo "ERROR: Script failed at line $LINENO (exit code: $?). Command: $BASH_COMMAND" >&2; exit 1' ERR

FILE_PATH="${1:-.env}"

if [[ -f "$FILE_PATH" ]]; then
  echo "Error: $FILE_PATH file already exists!" >&2
  exit 1
fi

random_alnum() {
  local length="${1:-32}"  
  LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$length"
  echo 
}

# Generate 32 random bytes and encode as base64
random_base64_32() {
  openssl rand -base64 32 | tr -d '\n'
}

AES256_KEY_BASE64=$(random_base64_32)

DB_PASSWORD=$(random_alnum 32)

CALC_POSTGRES_PASS=$(random_alnum 32)
CALC_PASSWORD=$(random_alnum 32)
DWH_POSTGRES_PASS=$(random_alnum 32)
DWH_POSTGRES_READ_PASS=$(random_alnum 32)
DWH_MYSQL_ROOT_PASS=$(random_alnum 32)

VALKEY_PASS=$(random_alnum 32)

JWT_SECRET=$(random_alnum 32)
SPECIAL_KEY=$(random_alnum 32)
USER_PASS=$(random_alnum 9)

OPENCODE_SERVER_PASSWORD=$(random_alnum 32)

DB_DB="mprove_main"
DB_USER="mprove_user"
USER_EMAIL="user@example.com"

CALC_USER="calc_user"
DWH_POSTGRES_READ_USER="dwh_postgres_read_user"

cat > "$FILE_PATH" << EOF
COMPOSE_ENV_FILE_SOURCE_PATH=.env
COMPOSE_ENV_FILE_TARGET_PATH=/usr/src/app/.env

# set most recent release tag from https://github.com/mprove-io/mprove/releases
MPROVE_RELEASE_TAG=$(jq -r '.version' package.json)
MPROVE_DWH_POSTGRES_TAG=18.1-m3
MPROVE_DWH_MYSQL_TAG=8.4.6-m2

TURBO_TELEMETRY_DISABLED=1
IS_TELEMETRY_ENABLED=FALSE
TELEMETRY_ENDPOINT=http://localhost:4318
TELEMETRY_HYPERDX_INGEST_API_KEY=
OTEL_LOG_LEVEL=info
COMPOSE_OPENCODE_SERVER_PASSWORD=${OPENCODE_SERVER_PASSWORD}
COMPOSE_ZEN_API_KEY=
COMPOSE_ANTHROPIC_API_KEY=
COMPOSE_OPENAI_API_KEY=

DOCKER_CLIENT_TIMEOUT=180
COMPOSE_HTTP_TIMEOUT=180

NODE_ENV=production

COMPOSE_DB_POSTGRES_DB=${DB_DB}
COMPOSE_DB_POSTGRES_USER=${DB_USER}
COMPOSE_DB_POSTGRES_PASSWORD=${DB_PASSWORD}
COMPOSE_DB_VOLUME_SOURCE_PATH=mprove_data/db-main

COMPOSE_CLICKSTACK_HYPERDX_APP_URL=http://localhost
COMPOSE_CLICKSTACK_DB_VOLUME_SOURCE_PATH=mprove_data/clickstack-db
COMPOSE_CLICKSTACK_CH_DATA_VOLUME_SOURCE_PATH=mprove_data/clickstack-ch-data
COMPOSE_CLICKSTACK_CH_LOGS_VOLUME_SOURCE_PATH=mprove_data/clickstack-ch-logs

COMPOSE_VALKEY_PASSWORD=${VALKEY_PASS}

COMPOSE_BACKEND_DEMO_PROJECT_BIGQUERY_CREDENTIALS_SOURCE_PATH=secrets/demo-project-bigquery-credentials.json
COMPOSE_BACKEND_DEMO_PROJECT_BIGQUERY_CREDENTIALS_PATH=/usr/src/app/secrets/demo-project-bigquery-credentials.json

COMPOSE_BACKEND_DEMO_PROJECT_REMOTE_PRIVATE_KEY_ENCRYPTED_SOURCE_PATH=secrets/demo-project-remote-private-key-encrypted.pem
COMPOSE_BACKEND_DEMO_PROJECT_REMOTE_PRIVATE_KEY_ENCRYPTED_PATH=/usr/src/app/secrets/demo-project-remote-private-key-encrypted.pem

COMPOSE_BACKEND_DEMO_PROJECT_REMOTE_PUBLIC_KEY_SOURCE_PATH=secrets/demo-project-remote-public-key.pem
COMPOSE_BACKEND_DEMO_PROJECT_REMOTE_PUBLIC_KEY_PATH=/usr/src/app/secrets/demo-project-remote-public-key.pem

COMPOSE_DISK_ORGANIZATIONS_VOLUME_SOURCE_PATH=mprove_data/organizations
COMPOSE_DISK_ORGANIZATIONS_VOLUME_PATH=/mprove/mprove_data/organizations

COMPOSE_CALC_POSTGRES_PASSWORD=${CALC_POSTGRES_PASS}
COMPOSE_CALC_USER=${CALC_USER}
COMPOSE_CALC_PASSWORD=${CALC_PASSWORD}

COMPOSE_DWH_POSTGRES_PASSWORD=${DWH_POSTGRES_PASS}
COMPOSE_DWH_POSTGRES_READ_USER=${DWH_POSTGRES_READ_USER}
COMPOSE_DWH_POSTGRES_READ_PASSWORD=${DWH_POSTGRES_READ_PASS}
COMPOSE_DWH_POSTGRES_VOLUME_SOURCE_PATH=mprove_data/dwh-postgres

COMPOSE_DWH_MYSQL_ROOT_PASSWORD=${DWH_MYSQL_ROOT_PASS}
COMPOSE_DWH_MYSQL_VOLUME_SOURCE_PATH=mprove_data/dwh-mysql

COMPOSE_DWH_TRINO_CATALOG_VOLUME_SOURCE_PATH=secrets/trino/catalog
COMPOSE_DWH_TRINO_CONFIG_VOLUME_SOURCE_PATH=secrets/trino/config.properties

COMPOSE_DWH_PRESTO_CATALOG_VOLUME_SOURCE_PATH=secrets/presto/catalog
COMPOSE_DWH_PRESTO_CONFIG_VOLUME_SOURCE_PATH=secrets/presto/config.properties

# dist paths are for docker compose debug config only
COMPOSE_DIST_APPS_DISK_SOURCE_PATH=dist/apps/disk
COMPOSE_DIST_APPS_BACKEND_SOURCE_PATH=dist/apps/backend
COMPOSE_DIST_APPS_BLOCKML_SOURCE_PATH=dist/apps/blockml

BACKEND_ENV=PROD
BACKEND_IS_ENCRYPT_DB=TRUE
BACKEND_IS_ENCRYPT_METADATA=FALSE
BACKEND_AES_KEY="${AES256_KEY_BASE64}"
BACKEND_AES_KEY_TAG=1
BACKEND_PREV_AES_KEY=
BACKEND_PREV_AES_KEY_TAG=
BACKEND_TOTAL_DISK_SHARDS=1
BACKEND_RPC_DISK_TIMEOUT_MS=60000
BACKEND_RPC_BLOCKML_TIMEOUT_MS=30000
BACKEND_IS_FORWARD_TELEMETRY_ENABLED=FALSE
BACKEND_VALKEY_HOST=valkey
BACKEND_VALKEY_PASSWORD=${VALKEY_PASS}
BACKEND_IS_SCHEDULER=FALSE
BACKEND_JWT_SECRET=${JWT_SECRET}
BACKEND_SPECIAL_KEY=${SPECIAL_KEY}
BACKEND_OPENCODE_SERVER_URL=http://opencode:14096
BACKEND_OPENCODE_SERVER_PASSWORD=${OPENCODE_SERVER_PASSWORD}
BACKEND_E2B_PUBLIC_TEMPLATE=1ue00hhhae2iqnjv34mh
BACKEND_ALLOW_TEST_ROUTES=FALSE
BACKEND_REGISTER_ONLY_INVITED_USERS=TRUE
BACKEND_ALLOW_USERS_TO_CREATE_ORGANIZATIONS=FALSE
# set email that will be used for Mprove Login
BACKEND_MPROVE_ADMIN_EMAIL=${USER_EMAIL}
# set password that will be used for Mprove Login
BACKEND_MPROVE_ADMIN_INITIAL_PASSWORD=${USER_PASS}
BACKEND_POSTGRES_DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_DB}
BACKEND_IS_POSTGRES_TLS=FALSE
BACKEND_CALC_POSTGRES_HOST=calc-postgres
BACKEND_CALC_POSTGRES_PORT=5437
BACKEND_CALC_POSTGRES_USERNAME=${CALC_USER}
BACKEND_CALC_POSTGRES_PASSWORD=${CALC_PASSWORD}
# replace value of BACKEND_HOST_URL with your real host (for links in transactional emails and CORS)
BACKEND_HOST_URL="http://localhost:3003,http://localhost:4200"
BACKEND_SEND_EMAIL_FROM_NAME=Example
BACKEND_SEND_EMAIL_FROM_ADDRESS=no-reply@example.com
BACKEND_EMAIL_TRANSPORT=SMTP
BACKEND_SMTP_PORT=465
BACKEND_SMTP_SECURE=TRUE
BACKEND_SMTP_HOST=
BACKEND_SMTP_AUTH_USER=
BACKEND_SMTP_AUTH_PASSWORD=
BACKEND_STORE_API_BLOCK_HOSTS=
BACKEND_STORE_API_ALLOW_HOSTS=
BACKEND_SEED_DEMO_ORG_AND_PROJECT=FALSE
BACKEND_DEMO_ORG_ID=
BACKEND_DEMO_PROJECT_ID=
BACKEND_DEMO_PROJECT_NAME=
BACKEND_DEMO_PROJECT_REMOTE_TYPE=GitClone
BACKEND_DEMO_PROJECT_GIT_URL=
BACKEND_DEMO_PROJECT_PRIVATE_KEY_ENCRYPTED_PATH=
BACKEND_DEMO_PROJECT_PUBLIC_KEY_PATH=
BACKEND_DEMO_PROJECT_PASS_PHRASE=
BACKEND_DEMO_PROJECT_DWH_POSTGRES_HOST=
BACKEND_DEMO_PROJECT_DWH_POSTGRES_USER=
BACKEND_DEMO_PROJECT_DWH_POSTGRES_PASSWORD=
BACKEND_DEMO_PROJECT_DWH_MYSQL_HOST=
BACKEND_DEMO_PROJECT_DWH_MYSQL_PORT=
BACKEND_DEMO_PROJECT_DWH_MYSQL_DATABASE=
BACKEND_DEMO_PROJECT_DWH_MYSQL_USER=
BACKEND_DEMO_PROJECT_DWH_MYSQL_PASSWORD=
BACKEND_DEMO_PROJECT_DWH_TRINO_USER=
BACKEND_DEMO_PROJECT_DWH_TRINO_PASSWORD=
BACKEND_DEMO_PROJECT_DWH_PRESTO_USER=
BACKEND_DEMO_PROJECT_DWH_PRESTO_PASSWORD=
BACKEND_DEMO_PROJECT_DWH_SNOWFLAKE_ACCOUNT=
BACKEND_DEMO_PROJECT_DWH_SNOWFLAKE_WAREHOUSE=
BACKEND_DEMO_PROJECT_DWH_SNOWFLAKE_USERNAME=
BACKEND_DEMO_PROJECT_DWH_SNOWFLAKE_PASSWORD=
BACKEND_DEMO_PROJECT_DWH_MOTHERDUCK_TOKEN=
BACKEND_DEMO_PROJECT_DWH_BIGQUERY_CREDENTIALS_PATH=
BACKEND_DEMO_PROJECT_DWH_GOOGLE_API_CREDENTIALS_PATH=
BACKEND_DEMO_PROJECT_E2B_API_KEY=
BACKEND_DEMO_PROJECT_ZEN_API_KEY=
BACKEND_DEMO_PROJECT_ANTHROPIC_API_KEY=
BACKEND_DEMO_PROJECT_OPENAI_API_KEY=
BACKEND_REQUEST_IP_HEADER_A=
BACKEND_REQUEST_IP_HEADER_B=
BACKEND_THROTTLE_PUBLIC_ROUTES_BY_IP=FALSE
BACKEND_THROTTLE_PRIVATE_ROUTES_BY_USER_ID=TRUE
BACKEND_LOG_THROTTLE_TRACKER=FALSE
BACKEND_LOG_DRIZZLE_POSTGRES=FALSE
BACKEND_LOG_IS_JSON=FALSE
BACKEND_LOG_RESPONSE_ERROR=TRUE
BACKEND_LOG_RESPONSE_OK=FALSE

BLOCKML_ENV=PROD
BLOCKML_AES_KEY="${AES256_KEY_BASE64}"
BLOCKML_VALKEY_HOST=valkey
BLOCKML_VALKEY_PASSWORD=${VALKEY_PASS}
BLOCKML_DATA=/mprove/mprove_data/blockml-data
BLOCKML_TESTS_DWH_POSTGRES_HOST=dwh-postgres
BLOCKML_TESTS_DWH_POSTGRES_PORT=5436
BLOCKML_TESTS_DWH_POSTGRES_USERNAME=${DWH_POSTGRES_READ_USER}
BLOCKML_TESTS_DWH_POSTGRES_PASSWORD=${DWH_POSTGRES_PASS}
BLOCKML_TESTS_DWH_POSTGRES_DATABASE_NAME=p_db
BLOCKML_LOG_IO=FALSE
BLOCKML_LOG_FUNC=ALL
BLOCKML_COPY_LOGS_TO_MODELS=FALSE
BLOCKML_LOGS_PATH=/mprove/mprove_data/blockml-logs
BLOCKML_CONCURRENCY_LIMIT=0
BLOCKML_LOG_IS_JSON=FALSE
BLOCKML_LOG_RESPONSE_ERROR=FALSE
BLOCKML_LOG_RESPONSE_OK=FALSE

DISK_ENV=PROD
DISK_AES_KEY="${AES256_KEY_BASE64}"
DISK_SHARD=shard-0
DISK_CONCURRENCY=1
DISK_ORGANIZATIONS_PATH=/mprove/mprove_data/organizations
DISK_VALKEY_HOST=valkey
DISK_VALKEY_PASSWORD=${VALKEY_PASS}
DISK_LOG_IS_JSON=FALSE
DISK_LOG_RESPONSE_ERROR=FALSE
DISK_LOG_RESPONSE_OK=FALSE

MPROVE_CLI_PROJECT_ID=DXYE72ODCP5LWPWH2EXQ
MPROVE_CLI_TEST_REPOS_PATH=/mprove/mprove_data/mcli-repos
MPROVE_CLI_TEST_REMOTE_GIT_URL=https://github.com/mprove-io/mp6.git
MPROVE_CLI_TEST_DESTINATION_URL=/mprove/mprove_data/mcli-repos/mp6
MPROVE_CLI_TEST_LOCAL_SOURCE_GIT_URL=/mprove/mprove_data/mcli-repos/mp6
MPROVE_CLI_TEST_DEV_SOURCE_GIT_URL=/mprove/mprove_data/mcli-repos/mp6
MPROVE_CLI_TEST_PUBLIC_KEY_PATH=/mprove/secrets/demo-project-remote-public-key.pem
MPROVE_CLI_TEST_PRIVATE_KEY_ENCRYPTED_PATH=/mprove/secrets/demo-project-remote-private-key-encrypted.pem
MPROVE_CLI_TEST_PASS_PHRASE=
MPROVE_CLI_TEST_DWH_POSTGRES_USER=${DWH_POSTGRES_READ_USER}
MPROVE_CLI_TEST_DWH_POSTGRES_PASSWORD=${DWH_POSTGRES_PASS}
MPROVE_CLI_EMAIL=${USER_EMAIL}
MPROVE_CLI_PASSWORD=${USER_PASS}
MPROVE_CLI_HOST=http://localhost:3000

EOF

echo "file \"$FILE_PATH\" created successfully!"