export enum ErTitleEnum {
  // yaml
  DUPLICATE_FILE_NAMES = 'DUPLICATE_FILE_NAMES',

  FILE_IS_EMPTY = 'FILE_IS_EMPTY',
  PARSED_YAML_IS_EMPTY = 'PARSED_YAML_IS_EMPTY',
  FILE_CONTENT_IS_NOT_YAML = 'FILE_CONTENT_IS_NOT_YAML',
  PROCESSED_CONTENT_IS_NOT_YAML = 'PROCESSED_CONTENT_IS_NOT_YAML',
  TOP_LEVEL_IS_NOT_DICTIONARY = 'TOP_LEVEL_IS_NOT_DICTIONARY',

  UNDEFINED_VALUE = 'UNDEFINED_VALUE',
  ARRAY_ELEMENT_IS_NULL = 'ARRAY_ELEMENT_IS_NULL',
  DUPLICATE_PARAMETERS = 'DUPLICATE_PARAMETERS',

  UNKNOWN_UDF_PARAMETER = 'UNKNOWN_UDF_PARAMETER',
  UNKNOWN_VIEW_PARAMETER = 'UNKNOWN_VIEW_PARAMETER',
  UNKNOWN_MODEL_PARAMETER = 'UNKNOWN_MODEL_PARAMETER',
  UNKNOWN_DASHBOARD_PARAMETER = 'UNKNOWN_DASHBOARD_PARAMETER',
  UNKNOWN_CHART_PARAMETER = 'UNKNOWN_CHART_PARAMETER',
  UNKNOWN_REPORT_PARAMETER = 'UNKNOWN_REPORT_PARAMETER',
  UNKNOWN_API_PARAMETER = 'UNKNOWN_API_PARAMETER',
  UNKNOWN_METRIC_PARAMETER = 'UNKNOWN_METRIC_PARAMETER',
  UNKNOWN_MPROVE_CONFIG_PARAMETER = 'UNKNOWN_MPROVE_CONFIG_PARAMETER',
  UNEXPECTED_LIST = 'UNEXPECTED_LIST',
  UNEXPECTED_DICTIONARY = 'UNEXPECTED_DICTIONARY',
  PARAMETER_IS_NOT_A_LIST = 'PARAMETER_IS_NOT_A_LIST',

  WRONG_HIDDEN = 'WRONG_HIDDEN',
  WRONG_CHAR_IN_PARAMETER_VALUE = 'WRONG_CHAR_IN_PARAMETER_VALUE',

  MISSING_CONNECTION = 'MISSING_CONNECTION',
  CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND',

  UDFS_ARE_NOT_SUPPORTED_FOR_CONNECTION = 'UDFS_ARE_NOT_SUPPORTED_FOR_CONNECTION',

  WRONG_UDF_NAME = 'WRONG_UDF_NAME',
  WRONG_VIEW_NAME = 'WRONG_VIEW_NAME',
  WRONG_MODEL_NAME = 'WRONG_MODEL_NAME',
  WRONG_DASHBOARD_NAME = 'WRONG_DASHBOARD_NAME',
  WRONG_REPORT_NAME = 'WRONG_REPORT_NAME',
  WRONG_API_NAME = 'WRONG_API_NAME',
  WRONG_METRIC_NAME = 'WRONG_METRIC_NAME',
  WRONG_CHART_NAME = 'WRONG_CHART_NAME',

  MPROVE_CONFIG_NOT_FOUND = 'MPROVE_CONFIG_NOT_FOUND',

  MISSING_MPROVE_DIR = 'MISSING_MPROVE_DIR',
  MPROVE_DIR_FOLDER_NAME_HAS_A_DOT = 'MPROVE_DIR_FOLDER_NAME_HAS_A_DOT',
  MPROVE_DIR_PATH_DOES_NOT_EXIST = 'MPROVE_DIR_PATH_DOES_NOT_EXIST',

  WRONG_ALLOW_TIMEZONES = 'WRONG_ALLOW_TIMEZONES',
  WRONG_PROJECT_CONFIG_PARAMETER = 'WRONG_PROJECT_CONFIG_PARAMETER',
  WRONG_SIMPLIFY_SAFE_AGGREGATES = 'WRONG_SIMPLIFY_SAFE_AGGREGATES',
  WRONG_CASE_SENSITIVE_STRING_FILTERS = 'WRONG_CASE_SENSITIVE_STRING_FILTERS',
  WRONG_WEEK_START = 'WRONG_WEEK_START',
  WRONG_DEFAULT_TIMEZONE = 'WRONG_DEFAULT_TIMEZONE',

  // fields
  MISSING_FIELDS = 'MISSING_FIELDS',

  FIELD_IS_NOT_A_DICTIONARY = 'FIELD_IS_NOT_A_DICTIONARY',
  PARAMETER_IS_NOT_A_DICTIONARY = 'PARAMETER_IS_NOT_A_DICTIONARY',

  MISSING_FIELD_DECLARATION = 'MISSING_FIELD_DECLARATION',
  MISSING_PARAMETER_DECLARATION = 'MISSING_PARAMETER_DECLARATION',

  TOO_MANY_DECLARATIONS_FOR_ONE_FIELD = 'TOO_MANY_DECLARATIONS_FOR_ONE_FIELD',
  TOO_MANY_DECLARATIONS_FOR_ONE_PARAMETER = 'TOO_MANY_DECLARATIONS_FOR_ONE_PARAMETER',

  FIELD_DECLARATION_WRONG_VALUE = 'FIELD_DECLARATION_WRONG_VALUE',
  PARAMETER_DECLARATION_WRONG_VALUE = 'PARAMETER_DECLARATION_WRONG_VALUE',

  // DASHBOARD_FIELD_MUST_BE_A_FILTER = 'DASHBOARD_FIELD_MUST_BE_A_FILTER',

  UNEXPECTED_SQL_IN_FILTER = 'UNEXPECTED_SQL_IN_FILTER',
  MISSING_SQL = 'MISSING_SQL',

  DUPLICATE_FIELD_NAMES = 'DUPLICATE_FIELD_NAMES',

  WRONG_FIELD_HIDDEN = 'WRONG_FIELD_HIDDEN',
  UNKNOWN_DIMENSION_PARAMETER = 'UNKNOWN_DIMENSION_PARAMETER',
  UNKNOWN_TIME_PARAMETER = 'UNKNOWN_TIME_PARAMETER',
  UNKNOWN_MEASURE_PARAMETER = 'UNKNOWN_MEASURE_PARAMETER',
  UNKNOWN_CALCULATION_PARAMETER = 'UNKNOWN_CALCULATION_PARAMETER',
  UNKNOWN_FILTER_PARAMETER = 'UNKNOWN_FILTER_PARAMETER',
  UNEXPECTED_LIST_IN_FIELD_PARAMETERS = 'UNEXPECTED_LIST_IN_FIELD_PARAMETERS',
  UNEXPECTED_DICTIONARY_IN_FIELD_PARAMETERS = 'UNEXPECTED_DICTIONARY_IN_FIELD_PARAMETERS',
  FIELD_PARAMETER_IS_NOT_A_LIST = 'FIELD_PARAMETER_IS_NOT_A_LIST',

  WRONG_DIMENSION_TYPE = 'WRONG_DIMENSION_TYPE',
  UNNEST_IS_NOT_SUPPORTED_FOR_CONNECTION = 'UNNEST_IS_NOT_SUPPORTED_FOR_CONNECTION',

  MISSING_TYPE_FOR_MEASURE = 'MISSING_TYPE_FOR_MEASURE',
  WRONG_MEASURE_TYPE = 'WRONG_MEASURE_TYPE',
  MISSING_SQL_KEY = 'MISSING_SQL_KEY',
  MEASURE_TYPE_IS_NOT_SUPPORTED_FOR_CONNECTION = 'MEASURE_TYPE_IS_NOT_SUPPORTED_FOR_CONNECTION',
  PERCENTILE_IS_NOT_SUPPORTED_FOR_CONNECTION = 'PERCENTILE_IS_NOT_SUPPORTED_FOR_CONNECTION',
  MISSING_PERCENTILE = 'MISSING_PERCENTILE',
  WRONG_PERCENTILE = 'WRONG_PERCENTILE',
  MEASURE_SQL_MISSING_BLOCKML_REFERENCE = 'MEASURE_SQL_MISSING_BLOCKML_REFERENCE',
  MEASURE_SQL_KEY_MISSING_BLOCKML_REFERENCE = 'MEASURE_SQL_KEY_MISSING_BLOCKML_REFERENCE',

  CALCULATION_SQL_MISSING_BLOCKML_REFERENCE = 'CALCULATION_SQL_MISSING_BLOCKML_REFERENCE',

  MISSING_FILTER_RESULT = 'MISSING_FILTER_RESULT',
  WRONG_DIMENSION_RESULT = 'WRONG_DIMENSION_RESULT',
  WRONG_MEASURE_RESULT = 'WRONG_MEASURE_RESULT',
  WRONG_CALCULATION_RESULT = 'WRONG_CALCULATION_RESULT',
  WRONG_FILTER_RESULT = 'WRONG_FILTER_RESULT',

  WRONG_FORMAT_NUMBER = 'WRONG_FORMAT_NUMBER',
  MISUSE_OF_FORMAT_NUMBER = 'MISUSE_OF_FORMAT_NUMBER',
  MISUSE_OF_CURRENCY_PREFIX = 'MISUSE_OF_CURRENCY_PREFIX',
  MISUSE_OF_CURRENCY_SUFFIX = 'MISUSE_OF_CURRENCY_SUFFIX',

  WRONG_TIME_SOURCE = 'WRONG_TIME_SOURCE',
  WRONG_TIMEFRAMES_ELEMENT = 'WRONG_TIMEFRAMES_ELEMENT',

  WRONG_CHARS_IN_ALIAS = 'WRONG_CHARS_IN_ALIAS',
  WRONG_CHARS_IN_VIEW_FIELDS_REFS = 'WRONG_CHARS_IN_VIEW_FIELDS_REFS',
  WRONG_CHARS_IN_MODEL_FIELDS_REFS = 'WRONG_CHARS_IN_MODEL_FIELDS_REFS',

  REFERENCE_TO_NOT_VALID_FIELD = 'REFERENCE_TO_NOT_VALID_FIELD',
  FIELD_SELF_REFERENCE = 'FIELD_SELF_REFERENCE',
  FIELD_REFS_FILTER = 'FIELD_REFS_FILTER',
  DIMENSION_REFS_MEASURE = 'DIMENSION_REFS_MEASURE',
  DIMENSION_REFS_CALCULATION = 'DIMENSION_REFS_CALCULATION',
  MEASURE_REFS_MEASURE = 'MEASURE_REFS_MEASURE',
  MEASURE_REFS_CALCULATION = 'MEASURE_REFS_CALCULATION',

  CYCLE_IN_REFERENCES = 'CYCLE_IN_REFERENCES',

  // udf

  // view
  MISSING_TABLE = 'MISSING_TABLE',

  TABLE_REFERENCES_MISSING_ENV_VAR = 'TABLE_REFERENCES_MISSING_ENV_VAR',
  DERIVED_TABLE_REFERENCES_MISSING_ENV_VAR = 'DERIVED_TABLE_REFERENCES_MISSING_ENV_VAR',

  WRONG_UDF = 'WRONG_UDF',

  APPLY_FILTER_REFS_MISSING_FILTER = 'APPLY_FILTER_REFS_MISSING_FILTER',
  APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  DERIVED_TABLE_VIEW_SELF_REFERENCE = 'DERIVED_TABLE_VIEW_SELF_REFERENCE',
  DERIVED_TABLE_SAME_ALIAS_FOR_DIFFERENT_VIEWS = 'DERIVED_TABLE_SAME_ALIAS_FOR_DIFFERENT_VIEWS',
  DERIVED_TABLE_NO_VIEW_REFERENCE = 'DERIVED_TABLE_NO_VIEW_REFERENCE',

  DERIVED_TABLE_CYCLE_IN_VIEW_REFERENCES = 'DERIVED_TABLE_CYCLE_IN_VIEW_REFERENCES',

  DERIVED_TABLE_REFERENCES_MISSING_VIEW = 'DERIVED_TABLE_REFERENCES_MISSING_VIEW',
  DERIVED_TABLE_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION = 'DERIVED_TABLE_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION',
  DERIVED_TABLE_REFERENCED_VIEW_HAS_APPLY_FILTER = 'DERIVED_TABLE_REFERENCED_VIEW_HAS_APPLY_FILTER',
  DERIVED_TABLE_REFERENCES_MISSING_FIELD = 'DERIVED_TABLE_REFERENCES_MISSING_FIELD',
  DERIVED_TABLE_REFERENCES_FILTER = 'DERIVED_TABLE_REFERENCES_FILTER',

  // model
  MODEL_NAME_STARTS_WITH_VIEW = 'MODEL_NAME_STARTS_WITH_VIEW',

  WRONG_MODEL_UDF = 'WRONG_MODEL_UDF',

  MISSING_JOINS = 'MISSING_JOINS',

  FROM_VIEW_AND_JOIN_VIEW = 'FROM_VIEW_AND_JOIN_VIEW',
  MISSING_FROM_VIEW_OR_JOIN_VIEW = 'MISSING_FROM_VIEW_OR_JOIN_VIEW',
  MISSING_FROM_VIEW_ELEMENT = 'MISSING_FROM_VIEW_ELEMENT',
  TOO_MANY_FROM_VIEW = 'TOO_MANY_FROM_VIEW',

  MISSING_AS = 'MISSING_AS',
  DUPLICATE_ALIASES = 'DUPLICATE_ALIASES',

  JOIN_CALLS_MISSING_VIEW = 'JOIN_CALLS_MISSING_VIEW',
  JOIN_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION = 'JOIN_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION',

  MODEL_FIELD_WRONG_ALIAS_IN_REFERENCE = 'MODEL_FIELD_WRONG_ALIAS_IN_REFERENCE',
  MODEL_FIELD_REFS_NOT_VALID_FIELD = 'MODEL_FIELD_REFS_NOT_VALID_FIELD',
  MODEL_FIELD_REFS_FILTER = 'MODEL_FIELD_REFS_FILTER',
  MODEL_DIMENSION_REFS_MEASURE = 'MODEL_DIMENSION_REFS_MEASURE',
  MODEL_DIMENSION_REFS_CALCULATION = 'MODEL_DIMENSION_REFS_CALCULATION',
  MODEL_MEASURE_REFS_MEASURE = 'MODEL_MEASURE_REFS_MEASURE',
  MODEL_MEASURE_REFS_CALCULATION = 'MODEL_MEASURE_REFS_CALCULATION',

  // join
  JOIN_WRONG_HIDDEN = 'JOIN_WRONG_HIDDEN',
  JOIN_UNKNOWN_PARAMETER_FOR_FROM_VIEW = 'JOIN_UNKNOWN_PARAMETER_FOR_FROM_VIEW',
  JOIN_UNKNOWN_PARAMETER_FOR_JOIN_VIEW = 'JOIN_UNKNOWN_PARAMETER_FOR_JOIN_VIEW',
  JOIN_UNEXPECTED_LIST = 'JOIN_UNEXPECTED_LIST',
  JOIN_UNEXPECTED_DICTIONARY = 'JOIN_UNEXPECTED_DICTIONARY',
  JOIN_PARAMETER_IS_NOT_A_LIST = 'JOIN_PARAMETER_IS_NOT_A_LIST',

  JOIN_WRONG_TYPE = 'JOIN_WRONG_TYPE',
  JOIN_WRONG_RELATIONSHIP = 'JOIN_WRONG_RELATIONSHIP',

  JOIN_MISSING_SQL_ON = 'JOIN_MISSING_SQL_ON',
  JOIN_MISSING_RELATIONSHIP = 'JOIN_MISSING_RELATIONSHIP',

  JOIN_HIDE_AND_SHOW_FIELDS = 'JOIN_HIDE_AND_SHOW_FIELDS',
  JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_REFERENCE = 'JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_REFERENCE',
  JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_ALIAS = 'JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_ALIAS',
  JOIN_HIDE_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD = 'JOIN_HIDE_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD',
  JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_REFERENCE = 'JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_REFERENCE',
  JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_ALIAS = 'JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_ALIAS',
  JOIN_SHOW_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD = 'JOIN_SHOW_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD',

  // join-sql-on
  JOIN_WRONG_CHARS_IN_SQL_ON_REFS = 'JOIN_WRONG_CHARS_IN_SQL_ON_REFS',

  JOIN_WRONG_ALIAS_IN_SQL_ON_REFERENCE = 'JOIN_WRONG_ALIAS_IN_SQL_ON_REFERENCE',
  JOIN_SQL_ON_REFS_MISSING_FIELD = 'JOIN_SQL_ON_REFS_MISSING_FIELD',
  JOIN_SQL_ON_REFS_FILTER = 'JOIN_SQL_ON_REFS_FILTER',
  JOIN_SQL_ON_REFS_MEASURE = 'JOIN_SQL_ON_REFS_MEASURE',
  JOIN_SQL_ON_REFS_CALCULATION = 'JOIN_SQL_ON_REFS_CALCULATION',

  JOIN_SQL_ON_REFS_MODEL_MISSING_FIELD = 'JOIN_SQL_ON_REFS_MODEL_MISSING_FIELD',
  JOIN_SQL_ON_REFS_MODEL_FILTER = 'JOIN_SQL_ON_REFS_MODEL_FILTER',
  JOIN_SQL_ON_REFS_MODEL_MEASURE = 'JOIN_SQL_ON_REFS_MODEL_MEASURE',
  JOIN_SQL_ON_REFS_MODEL_CALCULATION = 'JOIN_SQL_ON_REFS_MODEL_CALCULATION',

  // join-sql-where
  JOIN_WRONG_CHARS_IN_SQL_WHERE_REFS = 'JOIN_WRONG_CHARS_IN_SQL_WHERE_REFS',

  JOIN_WRONG_ALIAS_IN_SQL_WHERE_REFERENCE = 'JOIN_WRONG_ALIAS_IN_SQL_WHERE_REFERENCE',
  JOIN_SQL_WHERE_REFS_MISSING_FIELD = 'JOIN_SQL_WHERE_REFS_MISSING_FIELD',
  JOIN_SQL_WHERE_REFS_FILTER = 'JOIN_SQL_WHERE_REFS_FILTER',
  JOIN_SQL_WHERE_REFS_MEASURE = 'JOIN_SQL_WHERE_REFS_MEASURE',
  JOIN_SQL_WHERE_REFS_CALCULATION = 'JOIN_SQL_WHERE_REFS_CALCULATION',

  JOIN_SQL_WHERE_REFS_MODEL_MISSING_FIELD = 'JOIN_SQL_WHERE_REFS_MODEL_MISSING_FIELD',
  JOIN_SQL_WHERE_REFS_MODEL_FILTER = 'JOIN_SQL_WHERE_REFS_MODEL_FILTER',
  JOIN_SQL_WHERE_REFS_MODEL_MEASURE = 'JOIN_SQL_WHERE_REFS_MODEL_MEASURE',
  JOIN_SQL_WHERE_REFS_MODEL_CALCULATION = 'JOIN_SQL_WHERE_REFS_MODEL_CALCULATION',

  JOIN_SQL_WHERE_APPLY_FILTER_REFS_MISSING_FILTER = 'JOIN_SQL_WHERE_APPLY_FILTER_REFS_MISSING_FILTER',
  JOIN_SQL_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'JOIN_SQL_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  // sort-joins
  CYCLE_IN_JOINS_SQL_ON_OR_SQL_WHERE = 'CYCLE_IN_JOINS_SQL_ON_OR_SQL_WHERE',

  ALWAYS_JOIN_REFS_MISSING_JOIN = 'ALWAYS_JOIN_REFS_MISSING_JOIN',
  WRONG_ALWAYS_JOIN = 'WRONG_ALWAYS_JOIN',

  // sql-always-where
  WRONG_CHARS_IN_SQL_ALWAYS_WHERE_REFS = 'WRONG_CHARS_IN_SQL_ALWAYS_WHERE_REFS',

  WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_REFERENCE = 'WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_REFERENCE',
  SQL_ALWAYS_WHERE_REFS_MISSING_FIELD = 'SQL_ALWAYS_WHERE_REFS_MISSING_FIELD',
  SQL_ALWAYS_WHERE_REFS_FILTER = 'SQL_ALWAYS_WHERE_REFS_FILTER',
  SQL_ALWAYS_WHERE_REFS_MEASURE = 'SQL_ALWAYS_WHERE_REFS_MEASURE',
  SQL_ALWAYS_WHERE_REFS_CALCULATION = 'SQL_ALWAYS_WHERE_REFS_CALCULATION',

  SQL_ALWAYS_WHERE_REFS_MODEL_MISSING_FIELD = 'SQL_ALWAYS_WHERE_REFS_MODEL_MISSING_FIELD',
  SQL_ALWAYS_WHERE_REFS_MODEL_FILTER = 'SQL_ALWAYS_WHERE_REFS_MODEL_FILTER',
  SQL_ALWAYS_WHERE_REFS_MODEL_MEASURE = 'SQL_ALWAYS_WHERE_REFS_MODEL_MEASURE',
  SQL_ALWAYS_WHERE_REFS_MODEL_CALCULATION = 'SQL_ALWAYS_WHERE_REFS_MODEL_CALCULATION',

  SQL_ALWAYS_WHERE_APPLY_FILTER_REFS_MISSING_FILTER = 'SQL_ALWAYS_WHERE_APPLY_FILTER_REFS_MISSING_FILTER',
  SQL_ALWAYS_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'SQL_ALWAYS_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  // sql-always-where-calc
  WRONG_CHARS_IN_SQL_ALWAYS_WHERE_CALC_REFS = 'WRONG_CHARS_IN_SQL_ALWAYS_WHERE_CALC_REFS',

  WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_CALC_REFERENCE = 'WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_CALC_REFERENCE',
  SQL_ALWAYS_WHERE_CALC_REFS_MISSING_FIELD = 'SQL_ALWAYS_WHERE_CALC_REFS_MISSING_FIELD',
  SQL_ALWAYS_WHERE_CALC_REFS_FILTER = 'SQL_ALWAYS_WHERE_CALC_REFS_FILTER',

  SQL_ALWAYS_WHERE_CALC_REFS_MODEL_MISSING_FIELD = 'SQL_ALWAYS_WHERE_CALC_REFS_MODEL_MISSING_FIELD',
  SQL_ALWAYS_WHERE_CALC_REFS_MODEL_FILTER = 'SQL_ALWAYS_WHERE_CALC_REFS_MODEL_FILTER',

  SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_REFS_MISSING_FILTER = 'SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_REFS_MISSING_FILTER',
  SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  // build_metrics
  BUILD_METRICS_UNKNOWN_PARAMETER = 'BUILD_METRICS_UNKNOWN_PARAMETER',
  TIME_UNEXPECTED_LIST = 'TIME_UNEXPECTED_LIST',
  TIME_UNEXPECTED_DICTIONARY = 'TIME_UNEXPECTED_DICTIONARY',
  WRONG_TIME_FIELD = 'WRONG_TIME_FIELD',
  WRONG_TIME_MODEL_FIELD = 'WRONG_TIME_MODEL_FIELD',
  WRONG_TIME_ALIAS = 'WRONG_TIME_ALIAS',
  WRONG_TIME_VIEW_FIELD = 'WRONG_TIME_VIEW_FIELD',

  // row
  UNKNOWN_ROW_PARAMETER = 'UNKNOWN_ROW_PARAMETER',
  UNEXPECTED_LIST_IN_ROW_PARAMETERS = 'UNEXPECTED_LIST_IN_ROW_PARAMETERS',
  UNEXPECTED_DICTIONARY_IN_ROW_PARAMETERS = 'UNEXPECTED_DICTIONARY_IN_ROW_PARAMETERS',
  ROW_PARAMETER_MUST_BE_A_LIST = 'ROW_PARAMETER_MUST_BE_A_LIST',
  ROW_WRONG_PARAMETER_VALUE = 'ROW_WRONG_PARAMETER_VALUE',

  MISSING_ROW_ID = 'MISSING_ROW_ID',
  MISSING_ROW_TYPE = 'MISSING_ROW_TYPE',
  WRONG_ROW_TYPE = 'WRONG_ROW_TYPE',
  MISSING_ROW_NAME = 'MISSING_ROW_NAME',
  MISSING_ROW_METRIC = 'MISSING_ROW_METRIC',
  ROW_REFS_MISSING_METRIC = 'ROW_REFS_MISSING_METRIC',
  MISSING_ROW_PARAMETERS = 'MISSING_ROW_PARAMETERS',
  MISSING_ROW_FORMULA = 'MISSING_ROW_FORMULA',
  MISSING_FILTER = 'MISSING_FILTER',
  MISSING_CONDITIONS_OR_FORMULA = 'MISSING_CONDITIONS_OR_FORMULA',

  DUPLICATE_ROW_IDS = 'DUPLICATE_ROW_IDS',
  WRONG_CHARS_IN_ROW_ID = 'WRONG_CHARS_IN_ROW_ID',

  DUPLICATE_FILTERS = 'DUPLICATE_FILTERS',
  ROW_FILTER_WRONG_REFERENCE = 'ROW_FILTER_WRONG_REFERENCE',
  ROW_FILTER_REFS_MISSING_MODEL_FIELD = 'ROW_FILTER_REFS_MISSING_MODEL_FIELD',
  ROW_FILTER_REFS_MISSING_ALIAS = 'ROW_FILTER_REFS_MISSING_ALIAS',
  ROW_FILTER_REFS_MISSING_VIEW_FIELD = 'ROW_FILTER_REFS_MISSING_VIEW_FIELD',
  ROW_FILTER_WRONG_CONDITIONS = 'ROW_FILTER_WRONG_CONDITIONS',
  ROW_FILTER_CONDITIONS_IS_EMPTY = 'ROW_FILTER_CONDITIONS_IS_EMPTY',

  // parameter
  UNKNOWN_PARAMETER = 'UNKNOWN_PARAMETER',
  UNEXPECTED_LIST_IN_PARAMETERS = 'UNEXPECTED_LIST_IN_PARAMETERS',
  UNEXPECTED_DICTIONARY_IN_PARAMETERS = 'UNEXPECTED_DICTIONARY_IN_PARAMETERS',
  PARAMETER_MUST_BE_A_LIST = 'PARAMETER_MUST_BE_A_LIST',

  // chart
  CHART_MISSING_TILES = 'CHART_MISSING_TILES',
  CHART_TOO_MANY_TILES = 'CHART_TOO_MANY_TILES',

  // rep
  MISSING_REPORT_TITLE = 'MISSING_REPORT_TITLE',
  MISSING_REPORT_ROWS = 'MISSING_REPORT_ROWS',

  // tile
  TILE_IS_NOT_A_DICTIONARY = 'TILE_IS_NOT_A_DICTIONARY',

  UNKNOWN_TILE_PARAMETER = 'UNKNOWN_TILE_PARAMETER',
  UNEXPECTED_LIST_IN_TILE_PARAMETERS = 'UNEXPECTED_LIST_IN_TILE_PARAMETERS',
  UNEXPECTED_DICTIONARY_IN_TILE_PARAMETERS = 'UNEXPECTED_DICTIONARY_IN_TILE_PARAMETERS',
  TILE_PARAMETER_MUST_BE_A_LIST = 'TILE_PARAMETER_MUST_BE_A_LIST',
  TILE_PARAMETER_MUST_BE_A_DICTIONARY = 'TILE_PARAMETER_MUST_BE_A_DICTIONARY',

  MISSING_TILE_TITLE = 'MISSING_TILE_TITLE',
  DUPLICATE_TILE_TITLE = 'DUPLICATE_TILE_TITLE',
  MISSING_TILE_MODEL = 'MISSING_TILE_MODEL',
  WRONG_TILE_MODEL = 'WRONG_TILE_MODEL',
  MISSING_TILE_SELECT = 'MISSING_TILE_SELECT',

  TILE_WRONG_SELECT_ELEMENT = 'TILE_WRONG_SELECT_ELEMENT',
  TILE_WRONG_SELECT_MODEL_FIELD = 'TILE_WRONG_SELECT_MODEL_FIELD',
  TILE_WRONG_SELECT_ALIAS = 'TILE_WRONG_SELECT_ALIAS',
  TILE_WRONG_SELECT_VIEW_FIELD = 'TILE_WRONG_SELECT_VIEW_FIELD',

  TILE_WRONG_SORTS_SYNTAX = 'TILE_WRONG_SORTS_SYNTAX',
  TILE_SORTS_REFS_UNSELECTED_FIELD = 'TILE_SORTS_REFS_UNSELECTED_FIELD',

  TILE_WRONG_LIMIT = 'TILE_WRONG_LIMIT',

  CHART_TILE_CAN_NOT_HAVE_LISTEN_FILTERS = 'CHART_TILE_CAN_NOT_HAVE_LISTEN_FILTERS',
  TILE_LISTENS_MISSING_DASHBOARD_FILTER = 'TILE_LISTENS_MISSING_DASHBOARD_FILTER',
  TILE_WRONG_LISTENER = 'TILE_WRONG_LISTENER',
  TILE_WRONG_LISTENER_MODEL_FIELD = 'TILE_WRONG_LISTENER_MODEL_FIELD',
  TILE_MODEL_FIELD_LISTENS_MORE_THAN_ONE_FILTER = 'TILE_MODEL_FIELD_LISTENS_MORE_THAN_ONE_FILTER',
  TILE_FILTER_AND_MODEL_FIELD_RESULTS_MISMATCH = 'TILE_FILTER_AND_MODEL_FIELD_RESULTS_MISMATCH',
  TILE_WRONG_LISTENER_ALIAS = 'TILE_WRONG_LISTENER_ALIAS',
  TILE_WRONG_LISTENER_VIEW_FIELD = 'TILE_WRONG_LISTENER_VIEW_FIELD',
  TILE_VIEW_FIELD_LISTENS_MORE_THAN_ONE_FILTER = 'TILE_VIEW_FIELD_LISTENS_MORE_THAN_ONE_FILTER',
  TILE_FILTER_AND_VIEW_FIELD_RESULTS_MISMATCH = 'TILE_FILTER_AND_VIEW_FIELD_RESULTS_MISMATCH',

  TILE_DEFAULT_FILTER_WRONG_REFERENCE = 'TILE_DEFAULT_FILTER_WRONG_REFERENCE',
  TILE_DEFAULT_FILTER_REFS_MISSING_MODEL_FIELD = 'TILE_DEFAULT_FILTER_REFS_MISSING_MODEL_FIELD',
  TILE_DEFAULT_FILTER_REFS_MISSING_ALIAS = 'TILE_DEFAULT_FILTER_REFS_MISSING_ALIAS',
  TILE_DEFAULT_FILTER_REFS_MISSING_VIEW_FIELD = 'TILE_DEFAULT_FILTER_REFS_MISSING_VIEW_FIELD',
  TILE_SAME_FIELD_IN_DEFAULT_AND_LISTEN_FILTERS = 'TILE_SAME_FIELD_IN_DEFAULT_AND_LISTEN_FILTERS',
  TILE_DEFAULT_FILTER_MUST_BE_A_LIST = 'TILE_DEFAULT_FILTER_MUST_BE_A_LIST',
  TILE_DEFAULT_FILTER_WRONG_FILTER_EXPRESSION = 'TILE_DEFAULT_FILTER_WRONG_FILTER_EXPRESSION',

  // tile
  TILE_MISSING_TYPE = 'TILE_MISSING_TYPE',
  TILE_WRONG_TYPE = 'TILE_WRONG_TYPE',

  TILE_DATA_UNKNOWN_PARAMETER = 'TILE_DATA_UNKNOWN_PARAMETER',
  TILE_DATA_UNEXPECTED_LIST = 'TILE_DATA_UNEXPECTED_LIST',
  TILE_DATA_UNEXPECTED_DICTIONARY = 'TILE_DATA_UNEXPECTED_DICTIONARY',

  TILE_DATA_MISSING_X_FIELD = 'TILE_DATA_MISSING_X_FIELD',
  TILE_DATA_MISSING_Y_FIELD = 'TILE_DATA_MISSING_Y_FIELD',
  TILE_DATA_MISSING_SIZE_FIELD = 'TILE_DATA_MISSING_SIZE_FIELD', // TODO: test
  TILE_DATA_MISSING_Y_FIELDS = 'TILE_DATA_MISSING_Y_FIELDS',
  TILE_DATA_MISSING_VALUE_FIELD = 'TILE_DATA_MISSING_VALUE_FIELD',
  TILE_DATA_WRONG_X_FIELD = 'TILE_DATA_WRONG_X_FIELD',
  TILE_DATA_WRONG_X_FIELD_CLASS = 'TILE_DATA_WRONG_X_FIELD_CLASS',
  TILE_DATA_WRONG_Y_FIELD_CLASS = 'TILE_DATA_WRONG_Y_FIELD_CLASS',
  TILE_DATA_WRONG_SIZE_FIELD_CLASS = 'TILE_DATA_WRONG_SIZE_FIELD_CLASS', // TODO: test
  TILE_DATA_WRONG_MULTI_FIELD_CLASS = 'TILE_DATA_WRONG_MULTI_FIELD_CLASS',
  TILE_DATA_WRONG_VALUE_FIELD_CLASS = 'TILE_DATA_WRONG_VALUE_FIELD_CLASS',
  TILE_DATA_WRONG_PREVIOUS_VALUE_FIELD_CLASS = 'TILE_DATA_WRONG_PREVIOUS_VALUE_FIELD_CLASS',
  TILE_DATA_WRONG_Y_FIELDS_ELEMENT_FIELD_CLASS = 'TILE_DATA_WRONG_Y_FIELDS_ELEMENT_FIELD_CLASS',
  TILE_DATA_WRONG_Y_FIELD = 'TILE_DATA_WRONG_Y_FIELD',
  TILE_DATA_WRONG_SIZE_FIELD = 'TILE_DATA_WRONG_SIZE_FIELD', // TODO: test
  TILE_DATA_WRONG_MULTI_FIELD = 'TILE_DATA_WRONG_MULTI_FIELD',
  TILE_DATA_WRONG_VALUE_FIELD = 'TILE_DATA_WRONG_VALUE_FIELD',
  TILE_DATA_WRONG_PREVIOUS_VALUE_FIELD = 'TILE_DATA_WRONG_PREVIOUS_VALUE_FIELD',
  TILE_DATA_Y_FIELDS_MUST_BE_A_LIST = 'TILE_DATA_Y_FIELDS_MUST_BE_A_LIST',
  TILE_DATA_WRONG_Y_FIELDS_ELEMENT = 'TILE_DATA_WRONG_Y_FIELDS_ELEMENT',
  TILE_DATA_HIDE_COLUMNS_MUST_BE_A_LIST = 'TILE_DATA_HIDE_COLUMNS_MUST_BE_A_LIST',
  TILE_DATA_WRONG_HIDE_COLUMNS_ELEMENT = 'TILE_DATA_WRONG_HIDE_COLUMNS_ELEMENT',

  TILE_AXIS_UNKNOWN_PARAMETER = 'TILE_AXIS_UNKNOWN_PARAMETER',
  TILE_AXIS_UNEXPECTED_LIST = 'TILE_AXIS_UNEXPECTED_LIST',
  TILE_AXIS_UNEXPECTED_DICTIONARY = 'TILE_AXIS_UNEXPECTED_DICTIONARY',
  TILE_AXIS_WRONG_PARAMETER_VALUE = 'TILE_AXIS_WRONG_PARAMETER_VALUE',

  TILE_OPTIONS_UNKNOWN_PARAMETER = 'TILE_OPTIONS_UNKNOWN_PARAMETER',
  TILE_OPTIONS_UNEXPECTED_LIST = 'TILE_OPTIONS_UNEXPECTED_LIST',
  TILE_OPTIONS_UNEXPECTED_DICTIONARY = 'TILE_OPTIONS_UNEXPECTED_DICTIONARY',
  TILE_OPTIONS_WRONG_PARAMETER_VALUE = 'TILE_OPTIONS_WRONG_PARAMETER_VALUE',
  TILE_OPTIONS_WRONG_INTERPOLATION = 'TILE_OPTIONS_WRONG_INTERPOLATION',
  TILE_OPTIONS_WRONG_COLOR_SCHEME = 'TILE_OPTIONS_WRONG_COLOR_SCHEME',
  TILE_OPTIONS_WRONG_SCHEME_TYPE = 'TILE_OPTIONS_WRONG_SCHEME_TYPE',
  TILE_OPTIONS_PARAMETER_MUST_BE_A_POSITIVE_INTEGER = 'TILE_OPTIONS_PARAMETER_MUST_BE_A_POSITIVE_INTEGER',
  TILE_OPTIONS_PARAMETER_MUST_BE_A_NUMBER = 'TILE_OPTIONS_PARAMETER_MUST_BE_A_NUMBER',
  TILE_OPTIONS_PARAMETER_MUST_BE_AN_INTEGER = 'TILE_OPTIONS_PARAMETER_MUST_BE_AN_INTEGER',
  TILE_OPTIONS_WRONG_COLOR = 'TILE_OPTIONS_WRONG_COLOR',

  TILE_PLATE_UNKNOWN_PARAMETER = 'TILE_PLATE_UNKNOWN_PARAMETER',
  TILE_PLATE_UNEXPECTED_LIST = 'TILE_PLATE_UNEXPECTED_LIST',
  TILE_PLATE_UNEXPECTED_DICTIONARY = 'TILE_PLATE_UNEXPECTED_DICTIONARY',
  TILE_PLATE_WRONG_PLATE_WIDTH = 'TILE_PLATE_WRONG_PLATE_WIDTH',
  TILE_PLATE_WRONG_PLATE_HEIGHT = 'TILE_PLATE_WRONG_PLATE_HEIGHT',
  TILE_PLATE_PARAMETER_MUST_BE_A_POSITIVE_INTEGER = 'TILE_PLATE_PARAMETER_MUST_BE_A_POSITIVE_INTEGER',

  // special
  WRONG_FILTER_EXPRESSION = 'WRONG_FILTER_EXPRESSION',
  WRONG_ACCESS_USERS_ELEMENT = 'WRONG_ACCESS_USERS_ELEMENT',
  WRONG_ACCESS_ROLES_ELEMENT = 'WRONG_ACCESS_ROLES_ELEMENT',

  WRONG_SUGGEST_MODEL_DIMENSION = 'WRONG_SUGGEST_MODEL_DIMENSION',
  SUGGEST_MODEL_DIMENSION_WITH_WRONG_RESULT = 'SUGGEST_MODEL_DIMENSION_WITH_WRONG_RESULT',
  SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL = 'SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL',
  SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL_FIELD = 'SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL_FIELD',
  SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_JOIN_ALIAS = 'SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_JOIN_ALIAS',
  SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_JOIN_VIEW_FIELD = 'SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_JOIN_VIEW_FIELD',
  SUGGEST_MODEL_DIMENSION_DOES_NOT_REF_TO_A_DIMENSION = 'SUGGEST_MODEL_DIMENSION_DOES_NOT_REF_TO_A_DIMENSION',
  SUGGEST_MODEL_DIMENSION_REF_RESULT_IS_NOT_A_STRING = 'SUGGEST_MODEL_DIMENSION_REF_RESULT_IS_NOT_A_STRING'
}
