export enum ErTitleEnum { // TODO: check ErTitleEnum references
  // yaml
  DUPLICATE_FILE_NAMES = 'DUPLICATE_FILE_NAMES',

  FILE_IS_EMPTY = 'FILE_IS_EMPTY',
  PARSED_YAML_IS_EMPTY = 'PARSED_YAML_IS_EMPTY',
  FILE_CONTENT_IS_NOT_YAML = 'FILE_CONTENT_IS_NOT_YAML',
  PROCESSED_CONTENT_IS_NOT_YAML = 'PROCESSED_CONTENT_IS_NOT_YAML',
  TOP_LEVEL_IS_NOT_DICTIONARY = 'TOP_LEVEL_IS_NOT_DICTIONARY',

  UNDEFINED_VALUE = 'UNDEFINED_VALUE',
  ARRAY_ELEMENT_IS_NULL = 'ARRAY_ELEMENT_IS_NULL',
  DUPLICATE_PARAMETERS = 'DUPLICATE_PARAMETERS',

  UNKNOWN_UDF_PARAMETER = 'UNKNOWN_UDF_PARAMETER',
  UNKNOWN_VIEW_PARAMETER = 'UNKNOWN_VIEW_PARAMETER',
  UNKNOWN_MODEL_PARAMETER = 'UNKNOWN_MODEL_PARAMETER',
  UNKNOWN_STORE_PARAMETER = 'UNKNOWN_STORE_PARAMETER',
  UNKNOWN_DASHBOARD_PARAMETER = 'UNKNOWN_DASHBOARD_PARAMETER',
  UNKNOWN_CHART_PARAMETER = 'UNKNOWN_CHART_PARAMETER',
  UNKNOWN_REPORT_PARAMETER = 'UNKNOWN_REPORT_PARAMETER',
  UNKNOWN_API_PARAMETER = 'UNKNOWN_API_PARAMETER',
  UNKNOWN_METRIC_PARAMETER = 'UNKNOWN_METRIC_PARAMETER',
  UNKNOWN_MPROVE_CONFIG_PARAMETER = 'UNKNOWN_MPROVE_CONFIG_PARAMETER',
  UNEXPECTED_LIST = 'UNEXPECTED_LIST',
  UNEXPECTED_DICTIONARY = 'UNEXPECTED_DICTIONARY',
  PARAMETER_IS_NOT_A_LIST = 'PARAMETER_IS_NOT_A_LIST',

  WRONG_CHARS_IN_PARAMETER_VALUE = 'WRONG_CHARS_IN_PARAMETER_VALUE',

  MISSING_CONNECTION = 'MISSING_CONNECTION',
  CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND',
  WRONG_STORE_NAME = 'WRONG_STORE_NAME',
  WRONG_REPORT_NAME = 'WRONG_REPORT_NAME',
  WRONG_DASHBOARD_NAME = 'WRONG_DASHBOARD_NAME',
  WRONG_CHART_NAME = 'WRONG_CHART_NAME',

  MPROVE_CONFIG_NOT_FOUND = 'MPROVE_CONFIG_NOT_FOUND',

  MISSING_MPROVE_DIR = 'MISSING_MPROVE_DIR',
  MPROVE_DIR_MUST_START_WITH_DOT_SLASH = 'MPROVE_DIR_MUST_START_WITH_DOT_SLASH',
  MPROVE_DIR_HAS_DOT_AFTER_SLASH = 'MPROVE_DIR_HAS_DOT_AFTER_SLASH',
  MPROVE_DIR_PATH_DOES_NOT_EXIST = 'MPROVE_DIR_PATH_DOES_NOT_EXIST',

  WRONG_ALLOW_TIMEZONES = 'WRONG_ALLOW_TIMEZONES',
  WRONG_PROJECT_CONFIG_PARAMETER = 'WRONG_PROJECT_CONFIG_PARAMETER',
  WRONG_CASE_SENSITIVE_STRING_FILTERS = 'WRONG_CASE_SENSITIVE_STRING_FILTERS',
  WRONG_WEEK_START = 'WRONG_WEEK_START',
  WRONG_DEFAULT_TIMEZONE = 'WRONG_DEFAULT_TIMEZONE',

  // mod
  IMPORT_FROM_NON_MALLOY_FILE = 'IMPORT_FROM_NON_MALLOY_FILE',
  WRONG_IMPORT_PATH_FOR_MALLOY_FILE = 'WRONG_IMPORT_PATH_FOR_MALLOY_FILE',
  FAILED_TO_COMPILE_MALLOY = 'FAILED_TO_COMPILE_MALLOY',

  // store presets
  WRONG_PRESET = 'WRONG_PRESET',

  // store top
  MISSING_METHOD = 'MISSING_METHOD',
  MISSING_REQUEST = 'MISSING_REQUEST',
  MISSING_RESPONSE = 'MISSING_RESPONSE',
  WRONG_METHOD = 'WRONG_METHOD',
  WRONG_DATE_RANGE_INCLUDES_RIGHT_SIDE = 'WRONG_DATE_RANGE_INCLUDES_RIGHT_SIDE',

  // store field_groups
  FIELD_GROUP_IS_NOT_A_DICTIONARY = 'FIELD_GROUP_IS_NOT_A_DICTIONARY',
  UNKNOWN_FIELD_GROUP_PARAMETER = 'UNKNOWN_FIELD_GROUP_PARAMETER',
  MISSING_GROUP = 'MISSING_GROUP',
  DUPLICATE_GROUPS = 'DUPLICATE_GROUPS',

  // store field_time_groups
  FIELD_TIME_GROUP_IS_NOT_A_DICTIONARY = 'FIELD_TIME_GROUP_IS_NOT_A_DICTIONARY',
  UNKNOWN_FIELD_TIME_GROUP_PARAMETER = 'UNKNOWN_FIELD_TIME_GROUP_PARAMETER',
  WRONG_GROUP = 'WRONG_GROUP',

  // store results
  MISSING_RESULTS = 'MISSING_RESULTS',
  RESULTS_ELEMENT_IS_NOT_A_DICTIONARY = 'RESULTS_ELEMENT_IS_NOT_A_DICTIONARY',
  UNKNOWN_RESULTS_ELEMENT_PARAMETER = 'UNKNOWN_RESULTS_ELEMENT_PARAMETER',
  MISSING_RESULT = 'MISSING_RESULT',
  MISSING_FRACTION_TYPES = 'MISSING_FRACTION_TYPES',
  DUPLICATE_RESULTS = 'DUPLICATE_RESULTS',

  // store fraction_types
  FRACTION_TYPES_ELEMENT_IS_NOT_A_DICTIONARY = 'FRACTION_TYPES_ELEMENT_IS_NOT_A_DICTIONARY',
  UNKNOWN_FRACTION_TYPES_ELEMENT_PARAMETER = 'UNKNOWN_FRACTION_TYPES_ELEMENT_PARAMETER',
  MISSING_TYPE = 'MISSING_TYPE',
  MISSING_CONTROLS = 'MISSING_CONTROLS',
  CONTROLS_IS_EMPTY = 'CONTROLS_IS_EMPTY',
  DUPLICATE_TYPES = 'DUPLICATE_TYPES',

  // store fraction_controls
  CONTROLS_ELEMENT_IS_NOT_A_DICTIONARY = 'CONTROLS_ELEMENT_IS_NOT_A_DICTIONARY',
  UNKNOWN_CONTROLS_ELEMENT_PARAMETER = 'UNKNOWN_CONTROLS_ELEMENT_PARAMETER',
  MISSING_OPTIONS = 'MISSING_OPTIONS',
  OPTIONS_WITHOUT_SELECTOR = 'OPTIONS_WITHOUT_SELECTOR',
  MISSING_CONTROL_DECLARATION = 'MISSING_CONTROL_DECLARATION',
  TOO_MANY_DECLARATIONS_FOR_ONE_CONTROL = 'TOO_MANY_DECLARATIONS_FOR_ONE_CONTROL',
  DUPLICATE_CONTROL_NAMES = 'DUPLICATE_CONTROL_NAMES',

  FRACTION_CONTROL_REFS_MISSING_STORE_CONTROL = 'FRACTION_CONTROL_REFS_MISSING_STORE_CONTROL',
  FRACTION_CONTROL_CLASS_MISMATCH = 'FRACTION_CONTROL_CLASS_MISMATCH',
  FRACTION_CONTROL_SELECTOR_VALUE_MISSING_OPTION = 'FRACTION_CONTROL_SELECTOR_VALUE_MISSING_OPTION',
  FRACTION_CONTROL_WRONG_SWITCH_VALUE = 'FRACTION_CONTROL_WRONG_SWITCH_VALUE',

  // store control options
  OPTIONS_ELEMENT_IS_NOT_A_DICTIONARY = 'OPTIONS_ELEMENT_IS_NOT_A_DICTIONARY',
  UNKNOWN_OPTIONS_ELEMENT_PARAMETER = 'UNKNOWN_OPTIONS_ELEMENT_PARAMETER',
  MISSING_OPTION_VALUE = 'MISSING_OPTION_VALUE',
  DUPLICATE_OPTION_VALUES = 'DUPLICATE_OPTION_VALUES',

  // store build_metrics
  BUILD_METRICS_AND_REQUIRED_FIELDS_DO_NOT_WORK_TOGETHER = 'BUILD_METRICS_AND_REQUIRED_FIELDS_DO_NOT_WORK_TOGETHER',
  BUILD_METRICS_ELEMENT_IS_NOT_A_DICTIONARY = 'BUILD_METRICS_ELEMENT_IS_NOT_A_DICTIONARY',
  UNKNOWN_BUILD_METRIC_PARAMETER = 'UNKNOWN_BUILD_METRIC_PARAMETER',
  MISSING_TIME = 'MISSING_TIME', // there are no other properties in time to test missing_time
  WRONG_TIME = 'WRONG_TIME',
  DUPLICATE_TIME_NAMES = 'DUPLICATE_TIME_NAMES',

  // store details
  DETAIL_IS_NOT_A_DICTIONARY = 'DETAIL_IS_NOT_A_DICTIONARY',
  UNKNOWN_DETAIL_PARAMETER = 'UNKNOWN_DETAIL_PARAMETER',
  MISSING_DETAIL_UNIT = 'MISSING_DETAIL_UNIT',
  MISSING_DETAIL_DIMENSION = 'MISSING_DETAIL_DIMENSION',
  WRONG_DETAIL_UNIT = 'WRONG_DETAIL_UNIT',
  DUPLICATE_DETAIL = 'DUPLICATE_DETAIL',

  // fields
  MISSING_FIELDS = 'MISSING_FIELDS',

  FIELD_IS_NOT_A_DICTIONARY = 'FIELD_IS_NOT_A_DICTIONARY',
  PARAMETER_IS_NOT_A_DICTIONARY = 'PARAMETER_IS_NOT_A_DICTIONARY',

  MISSING_FIELD_DECLARATION = 'MISSING_FIELD_DECLARATION',
  WRONG_FIELD_DECLARATION = 'WRONG_FIELD_DECLARATION',
  MISSING_PARAMETER_DECLARATION = 'MISSING_PARAMETER_DECLARATION',

  TOO_MANY_DECLARATIONS_FOR_ONE_FIELD = 'TOO_MANY_DECLARATIONS_FOR_ONE_FIELD',
  TOO_MANY_DECLARATIONS_FOR_ONE_PARAMETER = 'TOO_MANY_DECLARATIONS_FOR_ONE_PARAMETER',

  FIELD_DECLARATION_WRONG_VALUE = 'FIELD_DECLARATION_WRONG_VALUE',
  PARAMETER_DECLARATION_WRONG_VALUE = 'PARAMETER_DECLARATION_WRONG_VALUE',

  MISSING_STORE_FIELD_RESULT = 'MISSING_STORE_FIELD_RESULT',
  WRONG_STORE_FIELD_RESULT = 'WRONG_STORE_FIELD_RESULT',

  WRONG_STORE_FIELD_GROUP = 'WRONG_STORE_FIELD_GROUP',
  WRONG_STORE_FIELD_TIME_GROUP = 'WRONG_STORE_FIELD_TIME_GROUP',
  STORE_FIELD_MULTIPLE_GROUPS = 'STORE_FIELD_MULTIPLE_GROUPS',

  STORE_FIELD_WRONG_DETAIL = 'STORE_FIELD_WRONG_DETAIL',
  STORE_FIELD_DETAIL_WITHOUT_TIME_GROUP = 'STORE_FIELD_DETAIL_WITHOUT_TIME_GROUP',
  STORE_FIELD_DUPLICATE_PAIR_OF_DETAIL_AND_TIME_GROUP = 'STORE_FIELD_DUPLICATE_PAIR_OF_DETAIL_AND_TIME_GROUP',

  UNEXPECTED_SQL_IN_FILTER = 'UNEXPECTED_SQL_IN_FILTER',
  MISSING_SQL = 'MISSING_SQL',

  DUPLICATE_FIELD_NAMES = 'DUPLICATE_FIELD_NAMES',

  WRONG_FIELD_HIDDEN = 'WRONG_FIELD_HIDDEN',
  UNKNOWN_DIMENSION_PARAMETER = 'UNKNOWN_DIMENSION_PARAMETER',
  UNKNOWN_TIME_PARAMETER = 'UNKNOWN_TIME_PARAMETER',
  UNKNOWN_MEASURE_PARAMETER = 'UNKNOWN_MEASURE_PARAMETER',
  UNKNOWN_CALCULATION_PARAMETER = 'UNKNOWN_CALCULATION_PARAMETER',
  UNKNOWN_FILTER_PARAMETER = 'UNKNOWN_FILTER_PARAMETER',

  WRONG_DIMENSION_TYPE = 'WRONG_DIMENSION_TYPE',
  UNNEST_IS_NOT_SUPPORTED_FOR_CONNECTION = 'UNNEST_IS_NOT_SUPPORTED_FOR_CONNECTION',

  MISSING_TYPE_FOR_MEASURE = 'MISSING_TYPE_FOR_MEASURE',
  WRONG_MEASURE_TYPE = 'WRONG_MEASURE_TYPE',
  MISSING_SQL_KEY = 'MISSING_SQL_KEY',
  MEASURE_TYPE_IS_NOT_SUPPORTED_FOR_CONNECTION = 'MEASURE_TYPE_IS_NOT_SUPPORTED_FOR_CONNECTION',
  PERCENTILE_IS_NOT_SUPPORTED_FOR_CONNECTION = 'PERCENTILE_IS_NOT_SUPPORTED_FOR_CONNECTION',
  MISSING_PERCENTILE = 'MISSING_PERCENTILE',
  WRONG_PERCENTILE = 'WRONG_PERCENTILE',
  MEASURE_SQL_MISSING_BLOCKML_REFERENCE = 'MEASURE_SQL_MISSING_BLOCKML_REFERENCE',
  MEASURE_SQL_KEY_MISSING_BLOCKML_REFERENCE = 'MEASURE_SQL_KEY_MISSING_BLOCKML_REFERENCE',

  CALCULATION_SQL_MISSING_BLOCKML_REFERENCE = 'CALCULATION_SQL_MISSING_BLOCKML_REFERENCE',

  MISSING_FILTER_RESULT = 'MISSING_FILTER_RESULT',
  WRONG_DIMENSION_RESULT = 'WRONG_DIMENSION_RESULT',
  WRONG_MEASURE_RESULT = 'WRONG_MEASURE_RESULT',
  WRONG_CALCULATION_RESULT = 'WRONG_CALCULATION_RESULT',
  WRONG_FILTER_RESULT = 'WRONG_FILTER_RESULT',

  WRONG_FORMAT_NUMBER = 'WRONG_FORMAT_NUMBER',
  MISUSE_OF_FORMAT_NUMBER = 'MISUSE_OF_FORMAT_NUMBER',
  MISUSE_OF_CURRENCY_PREFIX = 'MISUSE_OF_CURRENCY_PREFIX',
  MISUSE_OF_CURRENCY_SUFFIX = 'MISUSE_OF_CURRENCY_SUFFIX',

  WRONG_TIME_SOURCE = 'WRONG_TIME_SOURCE',
  WRONG_TIMEFRAMES_ELEMENT = 'WRONG_TIMEFRAMES_ELEMENT',

  WRONG_CHARS_IN_ALIAS = 'WRONG_CHARS_IN_ALIAS',
  WRONG_CHARS_IN_GROUP = 'WRONG_CHARS_IN_GROUP',
  WRONG_CHARS_IN_TIME_NAME = 'WRONG_CHARS_IN_TIME_NAME',
  WRONG_CHARS_IN_RESULT = 'WRONG_CHARS_IN_RESULT',
  WRONG_CHARS_IN_TYPE = 'WRONG_CHARS_IN_TYPE',
  WRONG_CHARS_IN_CONTROL_NAME = 'WRONG_CHARS_IN_CONTROL_NAME',
  WRONG_CHARS_IN_VIEW_FIELDS_REFS = 'WRONG_CHARS_IN_VIEW_FIELDS_REFS',
  WRONG_CHARS_IN_MODEL_FIELDS_REFS = 'WRONG_CHARS_IN_MODEL_FIELDS_REFS',

  REFERENCE_TO_NOT_VALID_FIELD = 'REFERENCE_TO_NOT_VALID_FIELD',
  FIELD_SELF_REFERENCE = 'FIELD_SELF_REFERENCE',
  FIELD_REFS_FILTER = 'FIELD_REFS_FILTER',
  DIMENSION_REFS_MEASURE = 'DIMENSION_REFS_MEASURE',
  DIMENSION_REFS_CALCULATION = 'DIMENSION_REFS_CALCULATION',
  MEASURE_REFS_MEASURE = 'MEASURE_REFS_MEASURE',
  MEASURE_REFS_CALCULATION = 'MEASURE_REFS_CALCULATION',

  CYCLE_IN_REFERENCES = 'CYCLE_IN_REFERENCES',

  // view
  MISSING_TABLE = 'MISSING_TABLE',

  TABLE_REFERENCES_MISSING_ENV_VAR = 'TABLE_REFERENCES_MISSING_ENV_VAR',
  DERIVED_TABLE_REFERENCES_MISSING_ENV_VAR = 'DERIVED_TABLE_REFERENCES_MISSING_ENV_VAR',

  WRONG_UDF = 'WRONG_UDF',

  APPLY_FILTER_REFS_MISSING_FILTER = 'APPLY_FILTER_REFS_MISSING_FILTER',
  APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  DERIVED_TABLE_VIEW_SELF_REFERENCE = 'DERIVED_TABLE_VIEW_SELF_REFERENCE',
  DERIVED_TABLE_SAME_ALIAS_FOR_DIFFERENT_VIEWS = 'DERIVED_TABLE_SAME_ALIAS_FOR_DIFFERENT_VIEWS',
  DERIVED_TABLE_NO_VIEW_REFERENCE = 'DERIVED_TABLE_NO_VIEW_REFERENCE',

  DERIVED_TABLE_CYCLE_IN_VIEW_REFERENCES = 'DERIVED_TABLE_CYCLE_IN_VIEW_REFERENCES',

  DERIVED_TABLE_REFERENCES_MISSING_VIEW = 'DERIVED_TABLE_REFERENCES_MISSING_VIEW',
  DERIVED_TABLE_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION = 'DERIVED_TABLE_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION',
  DERIVED_TABLE_REFERENCED_VIEW_HAS_APPLY_FILTER = 'DERIVED_TABLE_REFERENCED_VIEW_HAS_APPLY_FILTER',
  DERIVED_TABLE_REFERENCES_MISSING_FIELD = 'DERIVED_TABLE_REFERENCES_MISSING_FIELD',
  DERIVED_TABLE_REFERENCES_FILTER = 'DERIVED_TABLE_REFERENCES_FILTER',

  // model
  MODEL_NAME_STARTS_WITH_VIEW = 'MODEL_NAME_STARTS_WITH_VIEW',

  WRONG_MODEL_UDF = 'WRONG_MODEL_UDF',

  MISSING_JOINS = 'MISSING_JOINS',

  FROM_VIEW_AND_JOIN_VIEW = 'FROM_VIEW_AND_JOIN_VIEW',
  MISSING_FROM_VIEW_OR_JOIN_VIEW = 'MISSING_FROM_VIEW_OR_JOIN_VIEW',
  MISSING_FROM_VIEW_ELEMENT = 'MISSING_FROM_VIEW_ELEMENT',
  TOO_MANY_FROM_VIEW = 'TOO_MANY_FROM_VIEW',

  MISSING_AS = 'MISSING_AS',
  DUPLICATE_ALIASES = 'DUPLICATE_ALIASES',

  JOIN_CALLS_MISSING_VIEW = 'JOIN_CALLS_MISSING_VIEW',
  JOIN_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION = 'JOIN_REFERENCED_VIEW_HAS_DIFFERENT_CONNECTION',

  MODEL_FIELD_WRONG_ALIAS_IN_REFERENCE = 'MODEL_FIELD_WRONG_ALIAS_IN_REFERENCE',
  MODEL_FIELD_REFS_NOT_VALID_FIELD = 'MODEL_FIELD_REFS_NOT_VALID_FIELD',
  MODEL_FIELD_REFS_FILTER = 'MODEL_FIELD_REFS_FILTER',
  MODEL_DIMENSION_REFS_MEASURE = 'MODEL_DIMENSION_REFS_MEASURE',
  MODEL_DIMENSION_REFS_CALCULATION = 'MODEL_DIMENSION_REFS_CALCULATION',
  MODEL_MEASURE_REFS_MEASURE = 'MODEL_MEASURE_REFS_MEASURE',
  MODEL_MEASURE_REFS_CALCULATION = 'MODEL_MEASURE_REFS_CALCULATION',

  // join
  JOIN_WRONG_HIDDEN = 'JOIN_WRONG_HIDDEN',
  JOIN_UNKNOWN_PARAMETER_FOR_FROM_VIEW = 'JOIN_UNKNOWN_PARAMETER_FOR_FROM_VIEW',
  JOIN_UNKNOWN_PARAMETER_FOR_JOIN_VIEW = 'JOIN_UNKNOWN_PARAMETER_FOR_JOIN_VIEW',
  JOIN_UNEXPECTED_LIST = 'JOIN_UNEXPECTED_LIST',
  JOIN_UNEXPECTED_DICTIONARY = 'JOIN_UNEXPECTED_DICTIONARY',
  JOIN_PARAMETER_IS_NOT_A_LIST = 'JOIN_PARAMETER_IS_NOT_A_LIST',

  JOIN_WRONG_TYPE = 'JOIN_WRONG_TYPE',
  JOIN_WRONG_RELATIONSHIP = 'JOIN_WRONG_RELATIONSHIP',

  JOIN_MISSING_SQL_ON = 'JOIN_MISSING_SQL_ON',
  JOIN_MISSING_RELATIONSHIP = 'JOIN_MISSING_RELATIONSHIP',

  JOIN_HIDE_AND_SHOW_FIELDS = 'JOIN_HIDE_AND_SHOW_FIELDS',
  JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_REFERENCE = 'JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_REFERENCE',
  JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_ALIAS = 'JOIN_HIDE_FIELDS_ELEMENT_HAS_WRONG_ALIAS',
  JOIN_HIDE_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD = 'JOIN_HIDE_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD',
  JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_REFERENCE = 'JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_REFERENCE',
  JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_ALIAS = 'JOIN_SHOW_FIELDS_ELEMENT_HAS_WRONG_ALIAS',
  JOIN_SHOW_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD = 'JOIN_SHOW_FIELDS_ELEMENT_REFS_MISSING_VIEW_FIELD',

  // join-sql-on
  JOIN_WRONG_CHARS_IN_SQL_ON_REFS = 'JOIN_WRONG_CHARS_IN_SQL_ON_REFS',

  JOIN_WRONG_ALIAS_IN_SQL_ON_REFERENCE = 'JOIN_WRONG_ALIAS_IN_SQL_ON_REFERENCE',
  JOIN_SQL_ON_REFS_MISSING_FIELD = 'JOIN_SQL_ON_REFS_MISSING_FIELD',
  JOIN_SQL_ON_REFS_FILTER = 'JOIN_SQL_ON_REFS_FILTER',
  JOIN_SQL_ON_REFS_MEASURE = 'JOIN_SQL_ON_REFS_MEASURE',
  JOIN_SQL_ON_REFS_CALCULATION = 'JOIN_SQL_ON_REFS_CALCULATION',

  JOIN_SQL_ON_REFS_MODEL_MISSING_FIELD = 'JOIN_SQL_ON_REFS_MODEL_MISSING_FIELD',
  JOIN_SQL_ON_REFS_MODEL_FILTER = 'JOIN_SQL_ON_REFS_MODEL_FILTER',
  JOIN_SQL_ON_REFS_MODEL_MEASURE = 'JOIN_SQL_ON_REFS_MODEL_MEASURE',
  JOIN_SQL_ON_REFS_MODEL_CALCULATION = 'JOIN_SQL_ON_REFS_MODEL_CALCULATION',

  // join-sql-where
  JOIN_WRONG_CHARS_IN_SQL_WHERE_REFS = 'JOIN_WRONG_CHARS_IN_SQL_WHERE_REFS',

  JOIN_WRONG_ALIAS_IN_SQL_WHERE_REFERENCE = 'JOIN_WRONG_ALIAS_IN_SQL_WHERE_REFERENCE',
  JOIN_SQL_WHERE_REFS_MISSING_FIELD = 'JOIN_SQL_WHERE_REFS_MISSING_FIELD',
  JOIN_SQL_WHERE_REFS_FILTER = 'JOIN_SQL_WHERE_REFS_FILTER',
  JOIN_SQL_WHERE_REFS_MEASURE = 'JOIN_SQL_WHERE_REFS_MEASURE',
  JOIN_SQL_WHERE_REFS_CALCULATION = 'JOIN_SQL_WHERE_REFS_CALCULATION',

  JOIN_SQL_WHERE_REFS_MODEL_MISSING_FIELD = 'JOIN_SQL_WHERE_REFS_MODEL_MISSING_FIELD',
  JOIN_SQL_WHERE_REFS_MODEL_FILTER = 'JOIN_SQL_WHERE_REFS_MODEL_FILTER',
  JOIN_SQL_WHERE_REFS_MODEL_MEASURE = 'JOIN_SQL_WHERE_REFS_MODEL_MEASURE',
  JOIN_SQL_WHERE_REFS_MODEL_CALCULATION = 'JOIN_SQL_WHERE_REFS_MODEL_CALCULATION',

  JOIN_SQL_WHERE_APPLY_FILTER_REFS_MISSING_FILTER = 'JOIN_SQL_WHERE_APPLY_FILTER_REFS_MISSING_FILTER',
  JOIN_SQL_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'JOIN_SQL_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  // sort-joins
  CYCLE_IN_JOINS_SQL_ON_OR_SQL_WHERE = 'CYCLE_IN_JOINS_SQL_ON_OR_SQL_WHERE',

  ALWAYS_JOIN_REFS_MISSING_JOIN = 'ALWAYS_JOIN_REFS_MISSING_JOIN',
  WRONG_ALWAYS_JOIN = 'WRONG_ALWAYS_JOIN',

  // sql-always-where
  WRONG_CHARS_IN_SQL_ALWAYS_WHERE_REFS = 'WRONG_CHARS_IN_SQL_ALWAYS_WHERE_REFS',

  WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_REFERENCE = 'WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_REFERENCE',
  SQL_ALWAYS_WHERE_REFS_MISSING_FIELD = 'SQL_ALWAYS_WHERE_REFS_MISSING_FIELD',
  SQL_ALWAYS_WHERE_REFS_FILTER = 'SQL_ALWAYS_WHERE_REFS_FILTER',
  SQL_ALWAYS_WHERE_REFS_MEASURE = 'SQL_ALWAYS_WHERE_REFS_MEASURE',
  SQL_ALWAYS_WHERE_REFS_CALCULATION = 'SQL_ALWAYS_WHERE_REFS_CALCULATION',

  SQL_ALWAYS_WHERE_REFS_MODEL_MISSING_FIELD = 'SQL_ALWAYS_WHERE_REFS_MODEL_MISSING_FIELD',
  SQL_ALWAYS_WHERE_REFS_MODEL_FILTER = 'SQL_ALWAYS_WHERE_REFS_MODEL_FILTER',
  SQL_ALWAYS_WHERE_REFS_MODEL_MEASURE = 'SQL_ALWAYS_WHERE_REFS_MODEL_MEASURE',
  SQL_ALWAYS_WHERE_REFS_MODEL_CALCULATION = 'SQL_ALWAYS_WHERE_REFS_MODEL_CALCULATION',

  SQL_ALWAYS_WHERE_APPLY_FILTER_REFS_MISSING_FILTER = 'SQL_ALWAYS_WHERE_APPLY_FILTER_REFS_MISSING_FILTER',
  SQL_ALWAYS_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'SQL_ALWAYS_WHERE_APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  // sql-always-where-calc
  WRONG_CHARS_IN_SQL_ALWAYS_WHERE_CALC_REFS = 'WRONG_CHARS_IN_SQL_ALWAYS_WHERE_CALC_REFS',

  WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_CALC_REFERENCE = 'WRONG_ALIAS_IN_SQL_ALWAYS_WHERE_CALC_REFERENCE',
  SQL_ALWAYS_WHERE_CALC_REFS_MISSING_FIELD = 'SQL_ALWAYS_WHERE_CALC_REFS_MISSING_FIELD',
  SQL_ALWAYS_WHERE_CALC_REFS_FILTER = 'SQL_ALWAYS_WHERE_CALC_REFS_FILTER',

  SQL_ALWAYS_WHERE_CALC_REFS_MODEL_MISSING_FIELD = 'SQL_ALWAYS_WHERE_CALC_REFS_MODEL_MISSING_FIELD',
  SQL_ALWAYS_WHERE_CALC_REFS_MODEL_FILTER = 'SQL_ALWAYS_WHERE_CALC_REFS_MODEL_FILTER',

  SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_REFS_MISSING_FILTER = 'SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_REFS_MISSING_FILTER',
  SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_MUST_REFERENCE_A_FILTER = 'SQL_ALWAYS_WHERE_CALC_APPLY_FILTER_MUST_REFERENCE_A_FILTER',

  // build_metrics
  BUILD_METRICS_UNKNOWN_PARAMETER = 'BUILD_METRICS_UNKNOWN_PARAMETER',
  TIME_UNEXPECTED_LIST = 'TIME_UNEXPECTED_LIST',
  TIME_UNEXPECTED_DICTIONARY = 'TIME_UNEXPECTED_DICTIONARY',
  WRONG_TIME_FIELD = 'WRONG_TIME_FIELD',
  WRONG_TIME_MODEL_FIELD = 'WRONG_TIME_MODEL_FIELD',
  WRONG_TIME_ALIAS = 'WRONG_TIME_ALIAS',
  WRONG_TIME_VIEW_FIELD = 'WRONG_TIME_VIEW_FIELD',

  // row
  UNKNOWN_ROW_PARAMETER = 'UNKNOWN_ROW_PARAMETER',
  UNEXPECTED_LIST_IN_ROW_PARAMETERS = 'UNEXPECTED_LIST_IN_ROW_PARAMETERS',
  UNEXPECTED_DICTIONARY_IN_ROW_PARAMETERS = 'UNEXPECTED_DICTIONARY_IN_ROW_PARAMETERS',
  ROW_PARAMETER_MUST_BE_A_LIST = 'ROW_PARAMETER_MUST_BE_A_LIST',
  ROW_WRONG_PARAMETER_VALUE = 'ROW_WRONG_PARAMETER_VALUE',

  MISSING_ROW_ID = 'MISSING_ROW_ID',
  MISSING_ROW_TYPE = 'MISSING_ROW_TYPE',
  WRONG_ROW_TYPE = 'WRONG_ROW_TYPE',
  MISSING_ROW_NAME = 'MISSING_ROW_NAME',
  MISSING_ROW_METRIC = 'MISSING_ROW_METRIC',
  ROW_REFS_MISSING_METRIC = 'ROW_REFS_MISSING_METRIC',
  MISSING_ROW_PARAMETERS = 'MISSING_ROW_PARAMETERS',
  MISSING_ROW_FORMULA = 'MISSING_ROW_FORMULA',
  MISSING_APPLY_TO = 'MISSING_APPLY_TO',
  MISSING_LISTEN_OR_CONDITIONS = 'MISSING_LISTEN_OR_CONDITIONS',
  MISSING_LISTEN_OR_FRACTIONS = 'MISSING_LISTEN_OR_FRACTIONS',

  DUPLICATE_ROW_IDS = 'DUPLICATE_ROW_IDS',
  WRONG_CHARS_IN_ROW_ID = 'WRONG_CHARS_IN_ROW_ID',

  // top parameter
  TOP_PARAMETERS_RESULT_AND_STORE = 'TOP_PARAMETERS_RESULT_AND_STORE',
  TOP_PARAMETERS_RESULT_AND_STORE_FILTER = 'TOP_PARAMETERS_RESULT_AND_STORE_FILTER',
  TOP_PARAMETERS_RESULT_AND_STORE_RESULT = 'TOP_PARAMETERS_RESULT_AND_STORE_RESULT',
  TOP_PARAMETERS_STORE_FILTER_AND_STORE_RESULT = 'TOP_PARAMETERS_STORE_FILTER_AND_STORE_RESULT',

  TOP_PARAMETERS_STORE_FILTER_WITHOUT_STORE = 'TOP_PARAMETERS_STORE_FILTER_WITHOUT_STORE',
  TOP_PARAMETERS_STORE_RESULT_WITHOUT_STORE = 'TOP_PARAMETERS_STORE_RESULT_WITHOUT_STORE',
  TOP_PARAMETERS_STORE_ONLY = 'TOP_PARAMETERS_STORE_ONLY',

  TOP_PARAMETER_REFS_MISSING_STORE = 'TOP_PARAMETER_REFS_MISSING_STORE',
  TOP_PARAMETER_REFS_MISSING_STORE_FILTER = 'TOP_PARAMETER_REFS_MISSING_STORE_FILTER',
  TOP_PARAMETER_REFS_MISSING_STORE_RESULT = 'TOP_PARAMETER_REFS_MISSING_STORE_RESULT',

  // parameter
  DUPLICATE_APPLY_TO = 'DUPLICATE_APPLY_TO',
  APPLY_TO_WRONG_REFERENCE = 'APPLY_TO_WRONG_REFERENCE',
  APPLY_TO_REFS_MISSING_MODEL_FIELD = 'APPLY_TO_REFS_MISSING_MODEL_FIELD',
  APPLY_TO_REFS_MISSING_ALIAS = 'APPLY_TO_REFS_MISSING_ALIAS',
  APPLY_TO_REFS_MISSING_VIEW_FIELD = 'APPLY_TO_REFS_MISSING_VIEW_FIELD',

  APPLY_TO_REFS_MISSING_STORE_FIELD = 'APPLY_TO_REFS_MISSING_STORE_FIELD',
  PARAMETER_WRONG_COMBINATION_STORE = 'PARAMETER_WRONG_COMBINATION_STORE',
  APPLY_TO_AND_LISTEN_STORE_FILTER_MISMATCH = 'APPLY_TO_AND_LISTEN_STORE_FILTER_MISMATCH',
  APPLY_TO_AND_LISTEN_STORE_RESULT_MISMATCH = 'APPLY_TO_AND_LISTEN_STORE_RESULT_MISMATCH',

  PARAMETER_WRONG_COMBINATION = 'PARAMETER_WRONG_COMBINATION',
  APPLY_TO_CONDITIONS_IS_EMPTY = 'APPLY_TO_CONDITIONS_IS_EMPTY',
  APPLY_TO_WRONG_CONDITIONS = 'APPLY_TO_WRONG_CONDITIONS',

  ROW_PARAMETER_LISTENS_TO_MISSING_REPORT_FILTER = 'ROW_PARAMETER_LISTENS_TO_MISSING_REPORT_FILTER',
  ROW_PARAMETER_AND_LISTEN_RESULT_MISMATCH = 'ROW_PARAMETER_AND_LISTEN_RESULT_MISMATCH',

  TILE_PARAMETER_LISTENS_TO_MISSING_DASHBOARD_FILTER = 'TILE_PARAMETER_LISTENS_TO_MISSING_DASHBOARD_FILTER',
  TILE_PARAMETER_AND_LISTEN_RESULT_MISMATCH = 'TILE_PARAMETER_AND_LISTEN_RESULT_MISMATCH',

  UNKNOWN_PARAMETER = 'UNKNOWN_PARAMETER',
  UNEXPECTED_LIST_IN_PARAMETERS = 'UNEXPECTED_LIST_IN_PARAMETERS',
  UNEXPECTED_DICTIONARY_IN_PARAMETERS = 'UNEXPECTED_DICTIONARY_IN_PARAMETERS',
  PARAMETER_MUST_BE_A_LIST = 'PARAMETER_MUST_BE_A_LIST',

  // fractions
  MISSING_FRACTIONS = 'MISSING_FRACTIONS',
  FRACTIONS_LIST_IS_EMPTY = 'FRACTIONS_LIST_IS_EMPTY',
  MAX_FRACTIONS_EXCEEDED = 'MAX_FRACTIONS_EXCEEDED',

  // parameter fraction
  FRACTIONS_ELEMENT_IS_NOT_A_DICTIONARY = 'FRACTIONS_ELEMENT_IS_NOT_A_DICTIONARY',
  UNKNOWN_FRACTIONS_ELEMENT_PARAMETER = 'UNKNOWN_FRACTIONS_ELEMENT_PARAMETER',
  FRACTION_MISSING_LOGIC = 'FRACTION_MISSING_LOGIC',
  FRACTION_MISSING_TYPE = 'FRACTION_MISSING_TYPE',
  FRACTION_MISSING_CONTROLS = 'FRACTION_MISSING_CONTROLS',
  FRACTION_CANNOT_USE_LOGIC_PARAMETER_WITH_STORE_FILTER = 'FRACTION_CANNOT_USE_LOGIC_PARAMETER_WITH_STORE_FILTER',
  FRACTION_CANNOT_USE_TYPE_PARAMETER_WITH_STORE_FILTER = 'FRACTION_CANNOT_USE_TYPE_PARAMETER_WITH_STORE_FILTER',
  FRACTION_WRONG_LOGIC = 'WRONG_LOGIC',
  FRACTION_WRONG_TYPE = 'WRONG_TYPE',
  FRACTION_CONTROLS_LENGTH_DOES_NOT_MATCH_STORE_RESULT = 'FRACTION_CONTROLS_LENGTH_DOES_NOT_MATCH_STORE_RESULT',
  FRACTION_CONTROLS_LENGTH_DOES_NOT_MATCH_STORE_FILTER = 'FRACTION_CONTROLS_LENGTH_DOES_NOT_MATCH_STORE_FILTER',

  // chart
  CHART_MISSING_TILES = 'CHART_MISSING_TILES',
  CHART_TOO_MANY_TILES = 'CHART_TOO_MANY_TILES',

  // rep
  MISSING_REPORT_TITLE = 'MISSING_REPORT_TITLE',
  MISSING_REPORT_ROWS = 'MISSING_REPORT_ROWS',

  // tile
  TILE_IS_NOT_A_DICTIONARY = 'TILE_IS_NOT_A_DICTIONARY',

  UNKNOWN_TILE_PARAMETER = 'UNKNOWN_TILE_PARAMETER',
  UNEXPECTED_LIST_IN_TILE_PARAMETERS = 'UNEXPECTED_LIST_IN_TILE_PARAMETERS',
  UNEXPECTED_DICTIONARY_IN_TILE_PARAMETERS = 'UNEXPECTED_DICTIONARY_IN_TILE_PARAMETERS',
  TILE_PARAMETER_MUST_BE_A_LIST = 'TILE_PARAMETER_MUST_BE_A_LIST',
  TILE_PARAMETER_MUST_BE_A_DICTIONARY = 'TILE_PARAMETER_MUST_BE_A_DICTIONARY',

  MISSING_TILE_TITLE = 'MISSING_TILE_TITLE',
  DUPLICATE_TILE_TITLE = 'DUPLICATE_TILE_TITLE',
  MISSING_TILE_MODEL = 'MISSING_TILE_MODEL',
  WRONG_TILE_MODEL = 'WRONG_TILE_MODEL',
  MISSING_TILE_SELECT = 'MISSING_TILE_SELECT',

  TILE_WRONG_SELECT_ELEMENT = 'TILE_WRONG_SELECT_ELEMENT',
  TILE_WRONG_SELECT_MODEL_FIELD = 'TILE_WRONG_SELECT_MODEL_FIELD',
  TILE_WRONG_SELECT_ALIAS = 'TILE_WRONG_SELECT_ALIAS',
  TILE_WRONG_SELECT_VIEW_FIELD = 'TILE_WRONG_SELECT_VIEW_FIELD',

  TILE_WRONG_SORTS_SYNTAX = 'TILE_WRONG_SORTS_SYNTAX',
  TILE_SORTS_REFS_UNSELECTED_FIELD = 'TILE_SORTS_REFS_UNSELECTED_FIELD',

  TILE_WRONG_LIMIT = 'TILE_WRONG_LIMIT',

  CHART_TILE_PARAMETER_CANNOT_HAVE_LISTEN = 'CHART_TILE_PARAMETER_CANNOT_HAVE_LISTEN',
  TILE_LISTENS_MISSING_DASHBOARD_FILTER = 'TILE_LISTENS_MISSING_DASHBOARD_FILTER',
  TILE_WRONG_LISTENER = 'TILE_WRONG_LISTENER',
  TILE_WRONG_LISTENER_MODEL_FIELD = 'TILE_WRONG_LISTENER_MODEL_FIELD',
  TILE_MODEL_FIELD_LISTENS_MORE_THAN_ONE_FILTER = 'TILE_MODEL_FIELD_LISTENS_MORE_THAN_ONE_FILTER',
  TILE_FILTER_AND_MODEL_FIELD_RESULTS_MISMATCH = 'TILE_FILTER_AND_MODEL_FIELD_RESULTS_MISMATCH',
  TILE_WRONG_LISTENER_ALIAS = 'TILE_WRONG_LISTENER_ALIAS',
  TILE_WRONG_LISTENER_VIEW_FIELD = 'TILE_WRONG_LISTENER_VIEW_FIELD',
  TILE_VIEW_FIELD_LISTENS_MORE_THAN_ONE_FILTER = 'TILE_VIEW_FIELD_LISTENS_MORE_THAN_ONE_FILTER',
  TILE_FILTER_AND_VIEW_FIELD_RESULTS_MISMATCH = 'TILE_FILTER_AND_VIEW_FIELD_RESULTS_MISMATCH',

  // tile
  TILE_MISSING_TYPE = 'TILE_MISSING_TYPE',
  TILE_WRONG_TYPE = 'TILE_WRONG_TYPE',

  // tile data
  TILE_DATA_UNKNOWN_PARAMETER = 'TILE_DATA_UNKNOWN_PARAMETER',
  TILE_DATA_UNEXPECTED_LIST = 'TILE_DATA_UNEXPECTED_LIST',
  TILE_DATA_UNEXPECTED_DICTIONARY = 'TILE_DATA_UNEXPECTED_DICTIONARY',

  TILE_DATA_MISSING_X_FIELD = 'TILE_DATA_MISSING_X_FIELD',
  TILE_DATA_WRONG_X_FIELD = 'TILE_DATA_WRONG_X_FIELD',
  TILE_DATA_WRONG_X_FIELD_CLASS = 'TILE_DATA_WRONG_X_FIELD_CLASS',

  TILE_DATA_MISSING_Y_FIELDS = 'TILE_DATA_MISSING_Y_FIELDS',
  TILE_DATA_Y_FIELDS_MUST_BE_A_LIST = 'TILE_DATA_Y_FIELDS_MUST_BE_A_LIST',
  TILE_DATA_TOO_MANY_Y_FIELDS = 'TILE_DATA_TOO_MANY_Y_FIELDS',
  TILE_DATA_WRONG_Y_FIELDS_ELEMENT_FIELD_CLASS = 'TILE_DATA_WRONG_Y_FIELDS_ELEMENT_FIELD_CLASS',
  TILE_DATA_WRONG_Y_FIELDS_ELEMENT = 'TILE_DATA_WRONG_Y_FIELDS_ELEMENT',

  TILE_DATA_WRONG_SIZE_FIELD_RESULT = 'TILE_DATA_WRONG_SIZE_FIELD_RESULT',
  TILE_DATA_WRONG_SIZE_FIELD = 'TILE_DATA_WRONG_SIZE_FIELD',
  TILE_DATA_WRONG_MULTI_FIELD_CLASS = 'TILE_DATA_WRONG_MULTI_FIELD_CLASS',
  TILE_DATA_WRONG_MULTI_FIELD = 'TILE_DATA_WRONG_MULTI_FIELD',

  TILE_PLATE_UNKNOWN_PARAMETER = 'TILE_PLATE_UNKNOWN_PARAMETER',
  TILE_PLATE_UNEXPECTED_LIST = 'TILE_PLATE_UNEXPECTED_LIST',
  TILE_PLATE_UNEXPECTED_DICTIONARY = 'TILE_PLATE_UNEXPECTED_DICTIONARY',
  TILE_PLATE_WRONG_PLATE_WIDTH = 'TILE_PLATE_WRONG_PLATE_WIDTH',
  TILE_PLATE_WRONG_PLATE_HEIGHT = 'TILE_PLATE_WRONG_PLATE_HEIGHT',
  TILE_PLATE_PARAMETER_MUST_BE_A_POSITIVE_INTEGER = 'TILE_PLATE_PARAMETER_MUST_BE_A_POSITIVE_INTEGER',

  // options
  OPTIONS_UNKNOWN_PARAMETER = 'OPTIONS_UNKNOWN_PARAMETER',
  OPTIONS_UNEXPECTED_LIST = 'OPTIONS_UNEXPECTED_LIST',
  OPTIONS_UNEXPECTED_DICTIONARY = 'OPTIONS_UNEXPECTED_DICTIONARY',
  OPTIONS_WRONG_PARAMETER_VALUE = 'OPTIONS_WRONG_PARAMETER_VALUE',

  // options x_axis
  OPTIONS_X_AXIS_UNKNOWN_PARAMETER = 'OPTIONS_X_AXIS_UNKNOWN_PARAMETER',
  OPTIONS_X_AXIS_UNEXPECTED_LIST = 'OPTIONS_X_AXIS_UNEXPECTED_LIST',
  OPTIONS_X_AXIS_UNEXPECTED_DICTIONARY = 'OPTIONS_X_AXIS_UNEXPECTED_DICTIONARY',
  OPTIONS_X_AXIS_WRONG_PARAMETER_VALUE = 'OPTIONS_X_AXIS_WRONG_PARAMETER_VALUE',

  // options y_axis
  OPTIONS_TOO_MANY_Y_AXIS_ELEMENTS = 'OPTIONS_TOO_MANY_Y_AXIS_ELEMENTS',
  OPTIONS_Y_AXIS_UNKNOWN_PARAMETER = 'OPTIONS_Y_AXIS_UNKNOWN_PARAMETER',
  OPTIONS_Y_AXIS_UNEXPECTED_LIST = 'OPTIONS_Y_AXIS_UNEXPECTED_LIST',
  OPTIONS_Y_AXIS_UNEXPECTED_DICTIONARY = 'OPTIONS_Y_AXIS_UNEXPECTED_DICTIONARY',
  OPTIONS_Y_AXIS_WRONG_PARAMETER_VALUE = 'OPTIONS_Y_AXIS_WRONG_PARAMETER_VALUE',

  // options series
  OPTIONS_SERIES_UNKNOWN_PARAMETER = 'OPTIONS_SERIES_UNKNOWN_PARAMETER',
  OPTIONS_SERIES_UNEXPECTED_LIST = 'OPTIONS_SERIES_UNEXPECTED_LIST',
  OPTIONS_SERIES_UNEXPECTED_DICTIONARY = 'OPTIONS_SERIES_UNEXPECTED_DICTIONARY',
  OPTIONS_SERIES_WRONG_Y_AXIS_INDEX = 'OPTIONS_SERIES_WRONG_Y_AXIS_INDEX',
  OPTIONS_SERIES_WRONG_TYPE = 'OPTIONS_SERIES_WRONG_TYPE',
  OPTIONS_SERIES_MISSING_DATA_FIELD = 'OPTIONS_SERIES_MISSING_DATA_FIELD',
  OPTIONS_SERIES_MISSING_DATA_ROW_ID = 'OPTIONS_SERIES_MISSING_DATA_ROW_ID',
  OPTIONS_SERIES_WRONG_DATA_FIELD = 'OPTIONS_SERIES_WRONG_DATA_FIELD',
  OPTIONS_SERIES_WRONG_DATA_ROW_ID = 'OPTIONS_SERIES_WRONG_DATA_ROW_ID',
  OPTIONS_SERIES_WRONG_USE_OF_DATA_ROW_ID = 'OPTIONS_SERIES_WRONG_USE_OF_DATA_ROW_ID',
  OPTIONS_SERIES_WRONG_USE_OF_DATA_FIELD = 'OPTIONS_SERIES_WRONG_USE_OF_DATA_FIELD',

  // special
  WRONG_FILTER_EXPRESSION = 'WRONG_FILTER_EXPRESSION',
  WRONG_ACCESS_ROLES_ELEMENT = 'WRONG_ACCESS_ROLES_ELEMENT',

  WRONG_SUGGEST_MODEL_DIMENSION = 'WRONG_SUGGEST_MODEL_DIMENSION',
  SUGGEST_MODEL_DIMENSION_WITH_WRONG_RESULT = 'SUGGEST_MODEL_DIMENSION_WITH_WRONG_RESULT',
  SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL = 'SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL',
  SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL_FIELD = 'SUGGEST_MODEL_DIMENSION_REFS_NOT_VALID_MODEL_FIELD',
  SUGGEST_MODEL_DIMENSION_DOES_NOT_REF_TO_A_DIMENSION = 'SUGGEST_MODEL_DIMENSION_DOES_NOT_REF_TO_A_DIMENSION',
  SUGGEST_MODEL_DIMENSION_REF_RESULT_IS_NOT_A_STRING = 'SUGGEST_MODEL_DIMENSION_REF_RESULT_IS_NOT_A_STRING'
}
