export enum FuncEnum {
  ALL = 'ALL',

  CollectFiles = '01-yaml/01-collect-files',
  RemoveWrongExt = '01-yaml/02-remove-wrong-ext',
  DeduplicateFileNames = '01-yaml/03-deduplicate-file-names',
  YamlToObjects = '01-yaml/04-yaml-to-objects',
  MakeLineNumbers = '01-yaml/05-make-line-numbers',
  CheckTopUnknownParameters = '01-yaml/06-check-top-unknown-parameters',
  CheckTopValues = '01-yaml/07-check-top-values',
  CheckConnections = '01-yaml/08-check-connections',
  CheckSupportUdfs = '01-yaml/09-check-support-udfs',
  SplitFiles = '01-yaml/10-split-files',
  CheckProjectConfig = '01-yaml/11-check-project-config',

  CheckFieldsExist = '02-field/01-check-fields-exist',
  CheckFieldIsObject = '02-field/02-check-field-is-object',
  CheckFieldDeclaration = '02-field/03-check-field-declaration',
  CheckSqlExist = '02-field/04-check-sql-exist',
  CheckFieldNameDuplicates = '02-field/05-check-field-name-duplicates',
  CheckFieldUnknownParameters = '02-field/06-check-field-unknown-parameters',
  SetImplicitLabel = '02-field/07-set-implicit-label',
  CheckDimensions = '02-field/08-check-dimensions',
  TransformYesNoDimensions = '02-field/09-transform-yesno-dimensions',
  CheckMeasures = '02-field/10-check-measures',
  CheckCalculations = '02-field/11-check-calculations',
  CheckAndSetImplicitResult = '02-field/12-check-and-set-implicit-result',
  CheckAndSetImplicitFormatNumber = '02-field/13-check-and-set-implicit-format-number',
  TransformTimes = '02-field/14-transform-times',
  MakeFieldsDeps = '02-field/15-make-fields-deps',
  CheckFieldsDeps = '02-field/16-check-fields-deps',
  CheckCycles = '02-field/17-check-cycles',
  SubstituteSingleRefs = '02-field/18-substitute-single-refs',

  MakeUdfsDict = '03-udf/01-make-udfs-dict',

  CheckTable = '04-view/01-check-table',
  CheckTableEnvRefs = '04-view/01a-check-table-env-refs',
  CheckDerivedTableEnvRefs = '04-view/01b-check-derived-table-env-refs',
  CheckViewUdfs = '04-view/02-check-view-udfs',
  CheckViewFilterDefaults = '04-view/03-check-view-filter-defaults',
  CheckDerivedTableApplyFilter = '04-view/04-check-derived-table-apply-filter',
  MakeViewAsDeps = '04-view/05-make-view-as-deps',
  CheckViewCycles = '04-view/06-check-view-cycles',
  CheckViewAsDeps = '04-view/07-check-view-as-deps',
  PickUdfsFromAsDeps = '04-view/08-pick-udfs-from-as-deps',
  ProcessViewRefs = '04-view/09-process-view-refs',

  CheckModelAccess = '05-model/01-check-model-access',
  CheckModelUdfs = '05-model/02-check-model-udfs',
  CheckJoinsExist = '05-model/03-check-joins-exist',
  CheckJoinsFromView = '05-model/04-check-joins-from-view',
  CheckAliases = '05-model/05-check-aliases',
  MakeJoins = '05-model/06-make-joins',
  MakeFieldsDoubleDeps = '05-model/07-make-fields-double-deps',
  CheckFieldsDoubleDeps = '05-model/08-check-fields-double-deps',
  MakeFieldsDoubleDepsAfterSingles = '05-model/09-make-fields-double-deps-after-singles',
  CheckModelFilterDefaults = '05-model/10-check-model-filter-defaults',

  CheckJoinUnknownParameters = '06-join/01-check-join-unknown-parameters',
  CheckJoinType = '06-join/02-check-join-type',
  CheckSqlOnExist = '06-join/03-check-sql-on-exist',
  CheckJoinHideShowFields = '06-join/04-check-join-hide-show-fields',

  JsoCheckCharsInRefs = '07-join-sql-on/01-jso-check-chars-in-refs',
  JsoMakeDoubleDeps = '07-join-sql-on/02-jso-make-double-deps',
  JsoCheckDoubleDeps = '07-join-sql-on/03-jso-check-double-deps',
  JsoCheckSingleRefs = '07-join-sql-on/04-jso-check-single-refs',
  JsoSubstituteSingleRefs = '07-join-sql-on/05-jso-substitute-single-refs',
  JsoMakeJoinsDoubleDepsAfterSingles = '07-join-sql-on/06-jso-make-joins-double-deps-after-singles',

  JswCheckCharsInRefs = '08-join-sql-where/01-jsw-check-chars-in-refs',
  JswMakeDoubleDeps = '08-join-sql-where/02-jsw-make-double-deps',
  JswCheckDoubleDeps = '08-join-sql-where/03-jsw-check-double-deps',
  JswCheckSingleRefs = '08-join-sql-where/04-jsw-check-single-refs',
  JswSubstituteSingleRefs = '08-join-sql-where/05-jsw-substitute-single-refs',
  JswUpdateJoinsDoubleDepsAfterSingles = '08-join-sql-where/06-jsw-update-joins-double-deps-after-singles',
  JswCheckApplyFilter = '08-join-sql-where/07-jsw-check-apply-filter',

  CheckJoinsCyclesAndToposort = '09-sort-joins/01-check-joins-cycles-and-toposort',
  CheckAlwaysJoin = '09-sort-joins/02-check-always-join',

  SawCheckCharsInRefs = '10-sql-always-where/01-saw-check-chars-in-refs',
  SawMakeDoubleDeps = '10-sql-always-where/02-saw-make-double-deps',
  SawCheckDoubleDeps = '10-sql-always-where/03-saw-check-double-deps',
  SawCheckSingleRefs = '10-sql-always-where/04-saw-check-single-refs',
  SawSubstituteSingleRefs = '10-sql-always-where/05-saw-substitute-single-refs',
  SawMakeDoubleDepsAfterSingles = '10-sql-always-where/06-saw-make-double-deps-after-singles',
  SawCheckApplyFilter = '10-sql-always-where/07-saw-check-apply-filter',
  SawUpdateAlwaysJoinUnique = '10-sql-always-where/08-saw-update-always-join-unique',

  AwcCheckCharsInRefs = '11-sql-always-where-calc/01-awc-check-chars-in-refs',
  AwcMakeDoubleDeps = '11-sql-always-where-calc/02-awc-make-double-deps',
  AwcCheckDoubleDeps = '11-sql-always-where-calc/03-awc-check-double-deps',
  AwcCheckSingleRefs = '11-sql-always-where-calc/04-awc-check-single-refs',
  AwcSubstituteSingleRefs = '11-sql-always-where-calc/05-awc-substitute-single-refs',
  AwcMakeDoubleDepsAfterSubstitutions = '11-sql-always-where-calc/06-awc-make-double-deps-after-substitutions',
  AwcCheckApplyFilter = '11-sql-always-where-calc/07-awc-check-apply-filter',
  AwcUpdateAlwaysJoinUnique = '11-sql-always-where-calc/08-awc-update-always-join-unique',

  CheckBuildMetrics = '11.1-model-metric/01-check-build-metrics',
  CreateModelMetrics = '11.1-model-metric/02-create-model-metrics',

  CheckDashboardAccess = '12-dashboard/01-check-dashboard-access',
  CheckDashboardFilterDefaults = '12-dashboard/02-check-dashboard-filter-defaults',
  CheckDashboardTilesExist = '12-dashboard/03-check-dashboard-tiles-exist',

  CheckChartAccess = '13-chart/01-check-chart-access',
  CheckChartTilesExist = '13-chart/02-check-chart-tiles-exist',

  CheckTileIsObject = '14-tile/01-check-tile-is-object',
  CheckTileUnknownParameters = '14-tile/02-check-tile-unknown-parameters',
  CheckTileTitleModelSelect = '14-tile/03-check-tile-title-model-select',
  CheckSelectElements = '14-tile/04-check-select-elements',
  CheckSorts = '14-tile/05-check-sorts',
  CheckTimezone = '14-tile/06-check-timezone',
  CheckLimit = '14-tile/07-check-limit',
  CheckListenFilters = '14-tile/08-check-listen-filters',
  CheckDefaultFilters = '14-tile/09-check-default-filters',
  CombineTileFilters = '14-tile/10-combine-tile-filters',
  FetchSql = '14-tile/11-fetch-sql',

  CheckChartType = '15-mconfig-chart/01-check-chart-type',
  CheckChartData = '15-mconfig-chart/02-check-chart-data',
  CheckChartDataParameters = '15-mconfig-chart/03-check-chart-data-parameters',
  CheckChartAxisParameters = '15-mconfig-chart/04-check-chart-axis-parameters',
  CheckChartOptionsParameters = '15-mconfig-chart/05-check-chart-options-parameters',
  CheckChartPlateParameters = '15-mconfig-chart/06-check-chart-plate-parameters',

  CheckReport = '17-report/01-check-report',
  CheckReportAccess = '17-report/02-check-report-access',
  CheckReportRowUnknownParameters = '17-report/03-check-report-row-unknown-parameters',
  CheckReportRowUnknownParams = '17-report/04-check-report-row-unknown-params',
  CheckReportRow = '17-report/05-check-report-row',
  CheckReportRowIds = '17-report/06-check-report-row-ids',
  CheckReportRowParameters = '17-report/07-check-report-row-parameters',

  CheckAccess = 'special/check-access',
  CheckVmdFilterDefaults = 'special/check-vmd-filter-defaults',
  LogStruct = 'special/log-struct',

  SubMakeDepMeasuresAndDimensions = 'special-1-sub/01-sub-make-dep-measures-and-dimensions',
  SubMakeMainText = 'special-1-sub/02-sub-make-main-text',
  SubMakeNeedsAll = 'special-1-sub/03-sub-make-needs-all',
  SubMakeWith = 'special-1-sub/04-sub-make-with',
  SubComposeMain = 'special-1-sub/05-sub-compose-main',
  SubComposeCalc = 'special-1-sub/06-sub-compose-calc',

  MakeDepMeasuresAndDimensions = 'special-2-sql/01-make-dep-measures-and-dimensions',
  MakeMainText = 'special-2-sql/02-make-main-text',
  MakeNeedsDoubles = 'special-2-sql/03-make-needs-doubles',
  FindJoinsUsingJoinsDeps = 'special-2-sql/04-find-joins-using-joins-deps',
  MakeNeedsAll = 'special-2-sql/05-make-needs-all',
  MakeFilters = 'special-2-sql/06-make-filters',
  MakeWith = 'special-2-sql/07-make-with',
  MakeTop = 'special-2-sql/08-make-top',
  ComposeMain = 'special-2-sql/09-compose-main',
  ProcessTimezone = 'special-2-sql/10-process-timezone',
  ComposeCalc = 'special-2-sql/11-compose-calc'
}
