export enum FuncEnum {
  ALL = 'ALL',

  CheckChartAccess = 'build-chart/check-chart-access',
  CheckChartTilesExist = 'build-chart/check-chart-tiles-exist',

  CheckDashboardAccess = 'build-dashboard/check-dashboard-access',
  CheckDashboardTopParameters = 'build-dashboard/check-dashboard-top-parameters',
  CheckDashboardFilterConditions = 'build-dashboard/check-dashboard-filter-conditions',
  CheckDashboardTilesExist = 'build-dashboard/check-dashboard-tiles-exist',

  CheckFieldsExist = 'build-field/check-fields-exist',
  CheckParametersExist = 'build-field/check-parameters-exist',
  CheckFieldIsObject = 'build-field/check-field-is-object',
  CheckFieldDeclaration = 'build-field/check-field-declaration',
  CheckSqlExist = 'build-field/check-sql-exist',
  CheckFieldNameDuplicates = 'build-field/check-field-name-duplicates',
  CheckFieldUnknownParameters = 'build-field/check-field-unknown-parameters',
  SetImplicitLabel = 'build-field/set-implicit-label',
  CheckDimensions = 'build-field/check-dimensions',
  TransformYesNoDimensions = 'build-field/transform-yesno-dimensions',
  CheckMeasures = 'build-field/check-measures',
  CheckCalculations = 'build-field/check-calculations',
  CheckAndSetImplicitResult = 'build-field/check-and-set-implicit-result',
  CheckStoreFieldGroup = 'build-field/check-store-field-group',
  CheckStoreFieldDetail = 'build-field/check-store-field-detail',
  CheckAndSetImplicitFormatNumber = 'build-field/check-and-set-implicit-format-number',
  TransformTimes = 'build-field/transform-times',
  MakeFieldsDeps = 'build-field/make-fields-deps',
  CheckFieldsDeps = 'build-field/check-fields-deps',
  CheckCycles = 'build-field/check-cycles',
  SubstituteSingleRefs = 'build-field/substitute-single-refs',

  CheckChartType = 'build-mconfig-chart/check-chart-type',
  CheckChartData = 'build-mconfig-chart/check-chart-data',
  CheckChartDataParameters = 'build-mconfig-chart/check-chart-data-parameters',
  CheckChartPlateParameters = 'build-mconfig-chart/check-chart-plate-parameters',
  CheckChartOptionsParameters = 'build-mconfig-chart/check-chart-options-parameters',
  CheckChartOptionsXAxisParameters = 'build-mconfig-chart/check-chart-options-x-axis-parameters',
  CheckChartOptionsYAxisParameters = 'build-mconfig-chart/check-chart-options-y-axis-parameters',
  CheckChartOptionsSeriesParameters = 'build-mconfig-chart/check-chart-options-series-parameters',

  CreateModelMetrics = 'build-metrics-next/create-model-metrics',

  BuildMalloyModel = 'build-mod-start/build-malloy-model',
  BuildMods = 'build-mod-start/build-mods',

  CheckReport = 'build-report/check-report',
  CheckReportAccess = 'build-report/check-report-access',
  CheckReportTopParameters = 'build-report/check-report-top-parameters',
  CheckReportFilterConditions = 'build-report/check-report-filter-conditions',
  CheckReportRowUnknownParameters = 'build-report/check-report-row-unknown-parameters',
  CheckReportRowUnknownParams = 'build-report/check-report-row-unknown-params',
  CheckReportRow = 'build-report/check-report-row',
  CheckReportRowIds = 'build-report/check-report-row-ids',
  CheckReportRowParameters = 'build-report/check-report-row-parameters',
  BuildReportRowParameterFractions = 'build-report/build-report-row-parameter-fractions',

  CheckStoreBuildMetrics = 'build-store-next/check-store-build-metrics',
  CheckStoreBuildMetricDetails = 'build-store-next/check-store-build-metric-details',
  CheckStoreRequiredParameters = 'build-store-next/check-store-required-parameters',

  ApplyStorePresets = 'build-store-start/apply-store-presets',
  CheckStoreFieldGroups = 'build-store-start/check-store-field-groups',
  CheckStoreFieldTimeGroups = 'build-store-start/check-store-field-time-groups',
  CheckStoreResults = 'build-store-start/check-store-results',
  CheckResultFractionTypes = 'build-store-start/check-result-fraction-types',

  CheckTileIsObject = 'build-tile/check-tile-is-object',
  CheckTileUnknownParameters = 'build-tile/check-tile-unknown-parameters',
  CheckTileTitleModelSelect = 'build-tile/check-tile-title-model-select',
  CheckSelectElements = 'build-tile/check-select-elements',
  CheckSorts = 'build-tile/check-sorts',
  CheckLimit = 'build-tile/check-limit',
  CheckTileParameters = 'build-tile/check-tile-parameters',
  FetchSql = 'build-tile/fetch-sql',

  CollectFiles = 'build-yaml/collect-files',
  RemoveWrongExt = 'build-yaml/remove-wrong-ext',
  DeduplicateFileNames = 'build-yaml/deduplicate-file-names',
  YamlToObjects = 'build-yaml/yaml-to-objects',
  MakeLineNumbers = 'build-yaml/make-line-numbers',
  CheckTopUnknownParameters = 'build-yaml/check-top-unknown-parameters',
  CheckTopValues = 'build-yaml/check-top-values',
  CheckConnections = 'build-yaml/check-connections',
  CheckSupportUdfs = 'build-yaml/check-support-udfs',
  SplitFiles = 'build-yaml/split-files',
  CheckProjectConfig = 'build-yaml/check-project-config',

  BuildMalloyQuery = 'extra/build-malloy-query',
  CheckAccess = 'extra/check-access',
  CheckVmdrFilterConditions = 'extra/check-vmdr-filter-conditions',
  CheckStoreFraction = 'extra/check-store-fraction',
  CheckStoreFractionControls = 'extra/check-store-fraction-controls',
  CheckStoreFractionControlsUse = 'extra/check-store-fraction-controls-use',
  CheckStoreFractionControlOptions = 'extra/check-store-fraction-control-options',
  CheckVmdrSuggestModelDimension = 'extra/check-vmdr-suggest-model-dimension',
  CheckModelName = 'extra/check-model-name',
  BuildViewModel = 'extra/build-view-model',
  LogStruct = 'extra/log-struct'
}
