export enum postgresErrorsEnum {
  POSTGRES_CREATE_SCHEMA = 'POSTGRES_CREATE_SCHEMA',
  POSTGRES_DROP_TABLE = 'POSTGRES_DROP_TABLE',
  POSTGRES_RENAME_TABLE = 'POSTGRES_RENAME_TABLE',
  POSTGRES_GET_TABLES = 'POSTGRES_GET_TABLES'
}
