export enum ErEnum {
  // FRONT

  FRONT_RESPONSE_CODE_IS_NOT_201 = 'FRONT_RESPONSE_CODE_IS_NOT_201',
  FRONT_RESPONSE_INFO_STATUS_IS_NOT_OK = 'FRONT_RESPONSE_INFO_STATUS_IS_NOT_OK',

  FRONT_INSTANCE_OF_HTTP_ERROR_RESPONSE = 'FRONT_INSTANCE_OF_HTTP_ERROR_RESPONSE',
  FRONT_INSTANCE_OF_TIMEOUT_ERROR = 'FRONT_INSTANCE_OF_TIMEOUT_ERROR',
  FRONT_API_UNKNOWN_ERROR = 'FRONT_API_UNKNOWN_ERROR',

  FRONT_FORBIDDEN_REPO = 'FRONT_FORBIDDEN_REPO',
  BRANCH_DOES_NOT_EXIST = 'BRANCH_DOES_NOT_EXIST'
}
