// Generated by "pnpm fetch:anthropic-model-fixture". Do not edit by hand.
import type Anthropic from '@anthropic-ai/sdk';

export let ANTHROPIC_MODEL_INFO: Anthropic.Models.ModelInfo = {
  type: 'model',
  id: 'claude-sonnet-4-5-20250929',
  display_name: 'Claude Sonnet 4.5',
  created_at: '2025-09-29T00:00:00Z',
  max_input_tokens: 1000000,
  max_tokens: 64000,
  capabilities: {
    batch: {
      supported: true
    },
    citations: {
      supported: true
    },
    code_execution: {
      supported: true
    },
    context_management: {
      supported: true,
      clear_tool_uses_20250919: {
        supported: true
      },
      clear_thinking_20251015: {
        supported: true
      },
      compact_20260112: {
        supported: false
      }
    },
    effort: {
      supported: false,
      low: {
        supported: false
      },
      medium: {
        supported: false
      },
      high: {
        supported: false
      },
      xhigh: {
        supported: false
      },
      max: {
        supported: false
      }
    },
    image_input: {
      supported: true
    },
    pdf_input: {
      supported: true
    },
    structured_outputs: {
      supported: true
    },
    thinking: {
      supported: true,
      types: {
        enabled: {
          supported: true
        },
        adaptive: {
          supported: false
        }
      }
    }
  }
};
