// Generated by "pnpm fetch:openai-model-fixture". Do not edit by hand.
import type { Model } from '@opencode-ai/models';
import type OpenAI from 'openai';

type OpenAiModelInfo = {
  modelsDev: Model;
  modelsDevProvider: {
    api?: string;
    name: string;
    env: string[];
    id: string;
    npm: string;
  };
  openAi: OpenAI.Models.Model;
};

export let OPENAI_MODEL_INFO: OpenAiModelInfo = {
  modelsDev: {
    id: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol',
    description:
      'Frontier GPT-5.6 model for complex professional work, coding, and agentic workflows',
    family: 'gpt-sol',
    attachment: true,
    reasoning: true,
    reasoning_options: [
      {
        type: 'effort',
        values: ['none', 'low', 'medium', 'high', 'xhigh', 'max']
      }
    ],
    tool_call: true,
    structured_output: true,
    temperature: false,
    knowledge: '2026-02-16',
    release_date: '2026-07-09',
    last_updated: '2026-07-09',
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text']
    },
    open_weights: false,
    limit: {
      context: 1050000,
      input: 922000,
      output: 128000
    },
    experimental: {
      modes: {
        fast: {
          cost: {
            input: 8,
            output: 40,
            cache_read: 0.8,
            cache_write: 10
          },
          provider: {
            body: {
              service_tier: 'priority'
            }
          }
        },
        pro: {
          provider: {
            body: {
              reasoning: {
                mode: 'pro'
              }
            }
          }
        }
      }
    },
    cost: {
      input: 4,
      output: 20,
      cache_read: 0.4,
      cache_write: 5,
      tiers: [
        {
          input: 8,
          output: 30,
          cache_read: 0.8,
          cache_write: 10,
          tier: {
            type: 'context',
            size: 272000
          }
        }
      ],
      context_over_200k: {
        input: 8,
        output: 30,
        cache_read: 0.8,
        cache_write: 10
      }
    }
  },
  modelsDevProvider: {
    name: 'OpenAI',
    env: ['OPENAI_API_KEY'],
    id: 'openai',
    npm: '@ai-sdk/openai'
  },
  openAi: {
    id: 'gpt-5.6-sol',
    object: 'model',
    created: 1782228018,
    owned_by: 'system',
    shutdown_date: null
  }
};
