import type { FieldClass } from '#common/types/blockml/parts/field/field-class';
import type { FieldResult } from '#common/types/blockml/parts/field/field-result';

export type FieldDimension = {
  hidden?: string;
  hidden_line_num?: number;
  label?: string;
  label_line_num?: number;
  description?: string;
  description_line_num?: number;
  sql?: string;
  sql_line_num?: number;
  result?: FieldResult;
  result_line_num?: number;
  suggest_model_dimension?: string;
  suggest_model_dimension_line_num?: number;
  unnest?: string;
  unnest_line_num?: number;
  format_number?: string;
  format_number_line_num?: number;
  currency_prefix?: string;
  currency_prefix_line_num?: number;
  currency_suffix?: string;
  currency_suffix_line_num?: number;
  group_label?: string;
  group_label_line_num?: number;
  group_description?: string;
  group_description_line_num?: number;
  groupId?: string;
  name?: string;
  name_line_num?: number;
  fieldClass?: FieldClass;
  sqlReal?: string;
  sqlTimestampReal?: string;
  sqlTimestampName?: string;
  sqlTimestamp?: string;
};
