import type { FieldClassEnum } from '#common/enums/field-class.enum';
import type { FieldResultEnum } from '#common/enums/field-result.enum';
import type { Fraction } from '#common/types/blockml/parts/fraction';
import type { FileFraction } from '#common/types/blockml/parts/internal/file-fraction';
import type { EnumValues } from '#common/types/enum-values';

export type FieldFilter = {
  hidden?: string;
  hidden_line_num?: number;
  label?: string;
  label_line_num?: number;
  description?: string;
  description_line_num?: number;
  result?: EnumValues<typeof FieldResultEnum>;
  result_line_num?: number;
  store_model?: string;
  store_model_line_num?: number;
  store_result?: string;
  store_result_line_num?: number;
  store_filter?: string;
  store_filter_line_num?: number;
  suggest_model_dimension?: string;
  suggest_model_dimension_line_num?: number;
  conditions?: string[];
  conditions_line_num?: number;
  fractions?: FileFraction[];
  fractions_line_num?: number;
  apiFractions?: Fraction[];
  filter?: string;
  name?: string;
  name_line_num?: number;
  fieldClass?: EnumValues<typeof FieldClassEnum>;
};
