import type { FieldClass } from '#common/types/blockml/parts/field/field-class';
import type { FieldResult } from '#common/types/blockml/parts/field/field-result';
import type { FieldType } from '#common/types/blockml/parts/field/field-type';

export type FieldMeasure = {
  hidden?: string;
  hidden_line_num?: number;
  label?: string;
  label_line_num?: number;
  description?: string;
  description_line_num?: number;
  sql?: string;
  sql_line_num?: number;
  type?: FieldType;
  type_line_num?: number;
  result?: FieldResult;
  result_line_num?: number;
  format_number?: string;
  format_number_line_num?: number;
  currency_prefix?: string;
  currency_prefix_line_num?: number;
  currency_suffix?: string;
  currency_suffix_line_num?: number;
  sql_key?: string;
  sql_key_line_num?: number;
  percentile?: string;
  percentile_line_num?: number;
  name?: string;
  name_line_num?: number;
  fieldClass?: FieldClass;
  sqlReal?: string;
  sqlKeyReal?: string;
};
