version: '3.7'
services:
  mprove-dwh-clickhouse-nodeport-service:
    image: yandex/clickhouse-server:21.10.5.3
    env_file:
      - $CLICKHOUSE_ENV_FILE_PATH    
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - type: bind
        source: $M_DATA_CLICKHOUSE_PATH
        target: /var/lib/clickhouse

  tabix:
      image: spoonest/clickhouse-tabix-web-client
      ports:
        - 8124:80 

  mprove-dwh-postgres-nodeport-service:
    image: postgres:13.5
    env_file:
      - $PG_ENV_FILE_PATH
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: $M_DATA_PG_PATH
        target: /var/lib/postgresql/data
        
  db:
    image: mysql:8
    env_file:
      - $DB_ENV_FILE_PATH
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--max_allowed_packet=128M',
        '--innodb-buffer-pool-size=1G'
      ]
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: $M_DATA_MYSQL_PATH
        target: /var/lib/mysql

  rabbit:
    image: rabbitmq:3-management
    env_file:
      - $RABBIT_ENV_FILE_PATH
    ports:
      - 5672:5672
      - 15672:15672

  backend:
    build:
      context: ../../../
      dockerfile: tools/docker/backend.dev.Dockerfile
    image: mprove/mprove-base-m-backend:$MPROVE_BASE_RELEASE_TAG
    env_file:
      - $BACKEND_ENV_FILE_PATH
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: $BACKEND_ENV_FILE_PATH
        target: $BACKEND_ENV_FILE_PATH

  backend-scheduler:
    build:
      context: ../../../
      dockerfile: tools/docker/backend.dev.Dockerfile
    image: mprove/mprove-base-m-backend:$MPROVE_BASE_RELEASE_TAG
    env_file:
      - $BACKEND_SCHEDULER_ENV_FILE_PATH
    volumes:
      - type: bind
        source: $BACKEND_SCHEDULER_ENV_FILE_PATH
        target: $BACKEND_SCHEDULER_ENV_FILE_PATH

  blockml-main:
    build:
      context: ../../../
      dockerfile: tools/docker/blockml.dev.Dockerfile
    image: mprove/mprove-base-m-blockml:$MPROVE_BASE_RELEASE_TAG
    env_file:
      - $BLOCKML_MAIN_ENV_FILE_PATH
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: $BLOCKML_MAIN_ENV_FILE_PATH
        target: $BLOCKML_MAIN_ENV_FILE_PATH

  blockml-worker:
    build:
      context: ../../../
      dockerfile: tools/docker/blockml.dev.Dockerfile
    image: mprove/mprove-base-m-blockml:$MPROVE_BASE_RELEASE_TAG
    env_file:
      - $BLOCKML_WORKER_ENV_FILE_PATH
    volumes:
      - type: bind
        source: $BLOCKML_WORKER_ENV_FILE_PATH
        target: $BLOCKML_WORKER_ENV_FILE_PATH

  disk:
    build:
      context: ../../../
      dockerfile: tools/docker/disk.dev.Dockerfile
    image: mprove/mprove-base-m-disk:$MPROVE_BASE_RELEASE_TAG
    env_file:
      - $DISK_ENV_FILE_PATH
    ports:
      - 3002:3002
    volumes:
      - type: bind
        source: $DISK_ENV_FILE_PATH
        target: $DISK_ENV_FILE_PATH
      - type: bind
        source: $M_DATA_ORG_PATH
        target: $M_DATA_ORG_PATH

  front:
    build:
      context: ../../../
      dockerfile: tools/docker/front.dev.Dockerfile
    image: mprove/mprove-base-m-front:$MPROVE_BASE_RELEASE_TAG
    ports:
      - 3003:80
