version: '3.7'

secrets:
  fluent_key:
    file: $M_DATA_FLUENT_KEY_PATH

services:
  # fluent:
  #   build:
  #     context: ../../../
  #     dockerfile: tools/docker/fluent.dev.Dockerfile  
  #   # container_name: fluent
  #   image: mprove/mprove-base-m-fluent:$MPROVE_BASE_RELEASE_TAG
  #   env_file:
  #     - $FLUENT_ENV_FILE_PATH    
  #   secrets:
  #     - fluent_key
  #   ports:
  #     - 24224:24224
  #   volumes:
  #     - type: bind
  #       source: $M_DATA_FLUENT_LOG_PATH
  #       target: /fluentd/log      

  pg:
    image: postgres
    env_file:
      - $PG_ENV_FILE_PATH    
    ports:
      - 5432:5432        

  db:
    image: mysql:8
    env_file:
      - $DB_ENV_FILE_PATH    
    command: ['--default-authentication-plugin=mysql_native_password', '--max_allowed_packet=128M']
    ports:
      - 3306:3306         
    volumes:
      - type: bind
        source: $M_DATA_MYSQL_PATH
        target: /var/lib/mysql      
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: db   

  rabbit:
    # container_name: rabbit
    image: rabbitmq:3-management
    env_file:
      - $RABBIT_ENV_FILE_PATH    
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   # - type: bind
    #   #   source: 
    #   #   target: /etc/rabbitmq/      
    #   - type: bind
    #     source: $M_DATA_RABBIT_DATA_PATH
    #     target:  /var/lib/rabbitmq/  
    #   - type: bind
    #     source: $M_DATA_RABBIT_LOG_PATH
    #     target: /var/log/rabbitmq/     
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: rabbit

  backend:
    build:
      context: ../../../
      dockerfile: tools/docker/backend.dev.Dockerfile     
    # container_name: backend
    image: mprove/mprove-base-m-backend:$MPROVE_BASE_RELEASE_TAG 
    env_file:
      - $BACKEND_ENV_FILE_PATH    
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: $BACKEND_ENV_FILE_PATH
        target: $BACKEND_ENV_FILE_PATH      
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: backend    

  blockml-main:
    build:
      context: ../../../
      dockerfile: tools/docker/blockml.dev.Dockerfile     
    # container_name: blockml-main
    image: mprove/mprove-base-m-blockml:$MPROVE_BASE_RELEASE_TAG 
    env_file:
      - $BLOCKML_MAIN_ENV_FILE_PATH  
    ports:
      - 3001:3001       
    volumes:
      - type: bind
        source: $BLOCKML_MAIN_ENV_FILE_PATH
        target: $BLOCKML_MAIN_ENV_FILE_PATH  
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: blockml

  blockml-worker:
    build:
      context: ../../../
      dockerfile: tools/docker/blockml.dev.Dockerfile     
    image: mprove/mprove-base-m-blockml:$MPROVE_BASE_RELEASE_TAG 
    env_file:
      - $BLOCKML_WORKER_ENV_FILE_PATH    
    volumes:
      - type: bind
        source: $BLOCKML_WORKER_ENV_FILE_PATH
        target: $BLOCKML_WORKER_ENV_FILE_PATH      
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: blockml-worker

  disk:
    build:
      context: ../../../
      dockerfile: tools/docker/disk.dev.Dockerfile     
    image: mprove/mprove-base-m-disk:$MPROVE_BASE_RELEASE_TAG  
    # container_name: disk
    env_file:
      - $DISK_ENV_FILE_PATH
    ports:
      - 3002:3002          
    volumes:
      - type: bind
        source: $DISK_ENV_FILE_PATH
        target: $DISK_ENV_FILE_PATH        
      - type: bind
        source: $M_DATA_ORG_PATH
        target: $M_DATA_ORG_PATH
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: 0.0.0.0:24224
    #     fluentd-async-connect: "true"
    #     tag: disk      


    
      

