apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scheduler
  labels:
    app: backend-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend-scheduler
      annotations:
        # sidecar.istio.io/proxyCPU: "100m"
        checksum/secret-backend-common-envs: '{{ include (print $.Template.BasePath "/secret-backend-common-envs.yaml") . | sha256sum }}'        
        checksum/secret-backend-common-secret-files: '{{ include (print $.Template.BasePath "/secret-backend-common-secret-files.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret    
      containers:
      - name: backend-scheduler
        resources:
          limits:
            memory: "2000Mi"        
          # requests:
          #   memory: "2000Mi"
            # cpu: "100m"
        image: {{ .Values.werf.image.backend }}
        command:  
        - sh
        - '-c'
        - >
          until wget http://$BACKEND_RABBIT_USER:$BACKEND_RABBIT_PASS@$BACKEND_RABBIT_HOST:15672/api/aliveness-test/%2F > /dev/null 2>&1; 
          do echo waiting for rabbit ...; sleep 10; done && 
          echo rabbit is ready &&
          until yarn typeorm query "SELECT 1" -d apps/backend/src/typeorm-datasource.ts > /dev/null 2>&1; 
          do echo waiting for db ...; sleep 10; done && 
          echo db is ready && 
          yarn serve:backend
        env:
        - name: BACKEND_IS_SCHEDULER
          value: 'TRUE'
        - name: CLI_TYPEORM_MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: backend-common-envs
              key: BACKEND_MYSQL_HOST
        - name: CLI_TYPEORM_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-common-envs
              key: BACKEND_MYSQL_USERNAME
        - name: CLI_TYPEORM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-common-envs
              key: BACKEND_MYSQL_PASSWORD
        - name: CLI_TYPEORM_DATABASE
          valueFrom:
            secretKeyRef:
              name: backend-common-envs
              key: BACKEND_MYSQL_DATABASE                                                                
        envFrom:
        - secretRef:
            name: backend-common-envs
        ports:
        - containerPort: 9229
          name: backend-s-debug
        volumeMounts:
        - name: scheduler-secrets-volume
          mountPath: /usr/src/app/secrets
      volumes:
      - name: scheduler-secrets-volume
        secret:
          secretName: backend-common-secret-files
          items:
          - key: contentBigqueryCredentials
            path: first-project-bigquery-credentials.json
          - key: contentRemotePrivateKey
            path: first-project-remote-private-key.pem
          - key: contentRemotePublicKey
            path: first-project-remote-public-key.pem

---
apiVersion: v1
kind: Service
metadata:
  name: backend-scheduler
  labels:
    app: backend-scheduler
spec:
  selector:
    app: backend-scheduler
  type: NodePort
  ports:
  - port: 9232
    targetPort: 9229
    name: backend-s-debug 
