apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
      annotations:
        # sidecar.istio.io/proxyCPU: "100m"    
        checksum/secret-backend-common-envs: '{{ include (print $.Template.BasePath "/secret-backend-common-envs.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret    
      containers:
      - name: backend
        resources:
          limits:
            memory: "2000Mi"        
          # requests:
          #   memory: "2000Mi"
            # cpu: "100m"            
        image: {{ .Values.werf.image.backend }}
        command:  
        - sh
        - '-c'
        - >
          until wget http://$BACKEND_RABBIT_USER:$BACKEND_RABBIT_PASS@$BACKEND_RABBIT_HOST:15672/api/aliveness-test/%2F > /dev/null 2>&1; 
          do echo waiting for rabbit ...; sleep 10; done && 
          echo rabbit is ready &&
          until yarn typeorm query "SELECT 1" > /dev/null 2>&1; 
          do echo waiting for db ...; sleep 10; done && 
          echo db is ready && 
          yarn serve:backend
        env:
        - name: TYPEORM_CONNECTION
          value: mysql
        - name: TYPEORM_HOST
          valueFrom:
            secretKeyRef:
              name: backend-common-envs
              key: BACKEND_MYSQL_HOST
        - name: TYPEORM_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-common-envs
              key: BACKEND_MYSQL_USERNAME
        - name: TYPEORM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-common-envs
              key: BACKEND_MYSQL_PASSWORD                
        envFrom:
        - secretRef:
            name: backend-common-envs          
        ports:
        - containerPort: 3000
          name: backend
        - containerPort: 9229
          name: backend-debug          

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    name: backend 
  - port: 9231
    targetPort: 9229
    name: backend-debug 