apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scheduler
  labels:
    app: backend-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend-scheduler
      annotations:
        checksum/secret-backend-scheduler-envs: '{{ include (print $.Template.BasePath "/secret-backend-scheduler-envs.yaml") . | sha256sum }}'        
        checksum/secret-backend-bigquery: '{{ include (print $.Template.BasePath "/secret-backend-bigquery.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret    
      containers:
      - name: backend-scheduler
        image: {{ .Values.werf.image.backend }}
        command: ['yarn']
        args: ['serve:backend']        
        envFrom:
        - secretRef:
            name: backend-scheduler-envs
        ports:
        - containerPort: 9229
          name: backend-s-debug
        volumeMounts:
        - name: scheduler-secrets-volume
          mountPath: /usr/src/app/secrets
      volumes:
      - name: scheduler-secrets-volume
        secret:
          secretName: backend-bigquery
          items:
          - key: content
            path: bigquery-test.json

---
apiVersion: v1
kind: Service
metadata:
  name: backend-scheduler
  labels:
    app: backend-scheduler
spec:
  selector:
    app: backend-scheduler
  type: NodePort
  ports:
  - port: 9232
    targetPort: 9229
    name: backend-s-debug 
