apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scheduler
  labels:
    app: backend-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend-scheduler
      annotations:
        # sidecar.istio.io/proxyCPU: "100m"
        checksum/secret-backend-scheduler-envs: '{{ include (print $.Template.BasePath "/secret-backend-scheduler-envs.yaml") . | sha256sum }}'        
        checksum/secret-backend-bigquery: '{{ include (print $.Template.BasePath "/secret-backend-bigquery.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret    
      containers:
      - name: backend-scheduler
        resources:
          limits:
            memory: "2000Mi"        
          # requests:
          #   memory: "2000Mi"
            # cpu: "100m"
        image: {{ .Values.werf.image.backend }}
        command:  
        - sh
        - '-c'
        - >
          until wget http://$BACKEND_RABBIT_USER:$BACKEND_RABBIT_PASS@$BACKEND_RABBIT_HOST:15672/api/aliveness-test/%2F > /dev/null 2>&1; 
          do echo waiting for rabbit ...; sleep 10; done && 
          echo rabbit is ready &&
          until yarn typeorm query "SELECT 1" > /dev/null 2>&1; 
          do echo waiting for db ...; sleep 10; done && 
          echo db is ready && 
          yarn serve:backend
        env:
        - name: TYPEORM_CONNECTION
          value: mysql
        - name: TYPEORM_HOST
          valueFrom:
            secretKeyRef:
              name: backend-scheduler-envs
              key: BACKEND_MYSQL_HOST
        - name: TYPEORM_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-scheduler-envs
              key: BACKEND_MYSQL_USERNAME
        - name: TYPEORM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-scheduler-envs
              key: BACKEND_MYSQL_PASSWORD        
        envFrom:
        - secretRef:
            name: backend-scheduler-envs
        ports:
        - containerPort: 9229
          name: backend-s-debug
        volumeMounts:
        - name: scheduler-secrets-volume
          mountPath: /usr/src/app/secrets
      volumes:
      - name: scheduler-secrets-volume
        secret:
          secretName: backend-bigquery
          items:
          - key: content
            path: bigquery-test.json

---
apiVersion: v1
kind: Service
metadata:
  name: backend-scheduler
  labels:
    app: backend-scheduler
spec:
  selector:
    app: backend-scheduler
  type: NodePort
  ports:
  - port: 9232
    targetPort: 9229
    name: backend-s-debug 
