apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockml-main
  labels:
    app: blockml-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockml-main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blockml-main
      annotations:
        checksum/secret-blockml-main-envs: '{{ include (print $.Template.BasePath "/secret-blockml-main-envs.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret    
      containers:
      - name: blockml-main
        image: {{ .Values.werf.image.blockml }}
        envFrom:
        - secretRef:
            name: blockml-main-envs          

