apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockml-main
  labels:
    app: blockml-main
spec:
  replicas: 0
  selector:
    matchLabels:
      app: blockml-main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blockml-main
      annotations:
        # sidecar.istio.io/proxyCPU: "100m"    
        checksum/secret-blockml-main-envs: '{{ include (print $.Template.BasePath "/secret-blockml-main-envs.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret    
      containers:
      - name: blockml-main
        resources:
          requests:
            memory: "1800Mi"
            # cpu: "100m"
        image: {{ .Values.werf.image.blockml }}
        command: ['yarn']
        args: ['serve:blockml']        
        envFrom:
        - secretRef:
            name: blockml-main-envs
        ports:
        - containerPort: 9229
          name: blockml-m-debug

---
apiVersion: v1
kind: Service
metadata:
  name: blockml-main
  labels:
    app: blockml-main
spec:
  selector:
    app: blockml-main
  type: NodePort
  ports:
  - port: 9234
    targetPort: 9229
    name: blockml-m-debug                      

