apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disk
  labels:
    app: disk
spec:
  serviceName: disk
  selector:
    matchLabels:
      app: disk
  template:
    metadata:
      labels:
        app: disk
      annotations:
        # sidecar.istio.io/proxyCPU: "100m"    
        checksum/secret-disk-envs: '{{ include (print $.Template.BasePath "/secret-disk-envs.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret    
      containers:
      - name: disk
        resources:
          requests:
            memory: "1800Mi"
            # cpu: "100m"
        image: {{ .Values.werf.image.disk }}
        command: ['yarn']
        args: ['serve:disk']        
        envFrom:
        - secretRef:
            name: disk-envs     
        ports:
        - containerPort: 9229
          name: disk-debug                 
        volumeMounts:
        - name: disk-persistent-storage
          mountPath: /root/mprove_data/organizations
      volumes:
      - name: disk-persistent-storage
        persistentVolumeClaim:
          claimName: disk-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: disk
  labels:
    app: disk
spec:
  selector:
    app: disk
  type: NodePort
  ports:
  - port: 9230
    targetPort: 9229
    name: disk-debug 
