apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontnode
  name: frontnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontnode
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: frontnode
      # annotations:
      #   sidecar.istio.io/proxyCPU: "100m"       
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: frontnode
        resources:
          limits:
            memory: "2500Mi"        
          # requests:
          #   memory: "2500Mi"        
            # cpu: "100m"
        image: {{ .Values.werf.image.frontnode }}
        ports:
        - containerPort: 4200
          name: frontnode
          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontnode
  name: frontnode
spec:
  type: ClusterIP
  selector:
    app: frontnode
  ports:
  - name: frontnode
    port: 4200
    targetPort: 4200