apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: front
      # annotations:
      #   sidecar.istio.io/proxyCPU: "100m"      
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: front
        # resources:
        #   requests:
        #     cpu: "100m"
        image: {{ .Values.werf.image.front }}
        ports:
        - containerPort: 80
          name: front
          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
  - name: front
    port: 80
    targetPort: 80