apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontnode
  name: frontnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontnode
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: frontnode
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: frontnode
        image: {{ .Values.werf.image.frontnode }}
        resources:
          limits:
            memory: "2500Mi"
          requests:
            memory: "2000Mi"        
        ports:
        - containerPort: 4200
          name: frontnode
          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontnode
  name: frontnode
spec:
  type: ClusterIP
  selector:
    app: frontnode
  ports:
  - name: frontnode
    port: 4200
    targetPort: 4200