apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: integra
  name: integra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integra
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: integra
      # annotations:
      #   sidecar.istio.io/proxyCPU: "100m"      
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: integra
        # resources:
        #   requests:
        #     cpu: "100m"
        image: {{ .Values.werf.image.integra }}

