apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mcli
  name: mcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcli
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: mcli
      annotations:
        # sidecar.istio.io/proxyCPU: "100m"    
        checksum/secret-mcli-envs: '{{ include (print $.Template.BasePath "/secret-mcli-envs.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: mcli
        # resources:
        #   requests:
        #     cpu: "100m"
        image: {{ .Values.werf.image.mcli }}
        envFrom:
        - secretRef:
            name: mcli-envs        

