apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mcli
  name: mcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcli
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: mcli
      annotations:
        # sidecar.istio.io/proxyCPU: "100m"    
        checksum/secret-mcli-envs: '{{ include (print $.Template.BasePath "/secret-mcli-envs.yaml") . | sha256sum }}'   
        checksum/secret-backend-common-secret-files: '{{ include (print $.Template.BasePath "/secret-backend-common-secret-files.yaml") . | sha256sum }}'        
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: mcli
        # resources:
        #   requests:
        #     cpu: "100m"
        image: {{ .Values.werf.image.mcli }}
        envFrom:
        - secretRef:
            name: mcli-envs
        volumeMounts:
        - name: mcli-secrets-volume
          mountPath: /usr/src/app/secrets
      volumes:
      - name: mcli-secrets-volume
        secret:
          secretName: backend-common-secret-files
          items:
          - key: contentRemotePrivateKey
            path: first-project-remote-private-key.pem
          - key: contentRemotePublicKey
            path: first-project-remote-public-key.pem                  

