apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - istio-system/gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: backend
        port:
          number: 3000 
  - route:
    - destination:
        host: front
        port:
          number: 80