apiVersion: v1
kind: Secret
metadata:
  name: backend-common-secret-files
type: Opaque
data:
  contentBigquery: {{ werf_secret_file "bigquery-test.json" | b64enc }}
  contentRemotePrivateKey: {{ werf_secret_file "first-project-remote-private-key.pem" | b64enc }}
  contentRemotePublicKey: {{ werf_secret_file "first-project-remote-public-key.pem" | b64enc }}