apiVersion: v1
kind: Secret
metadata:
  name: backend-common-secret-files
type: Opaque
data:
  contentTypeormDataSource: {{ werf_secret_file "typeorm-datasource.ts" | b64enc }}
  contentBigqueryCredentials: {{ werf_secret_file "first-project-bigquery-credentials.json" | b64enc }}
  contentRemotePrivateKey: {{ werf_secret_file "first-project-remote-private-key.pem" | b64enc }}
  contentRemotePublicKey: {{ werf_secret_file "first-project-remote-public-key.pem" | b64enc }}