import fs from 'node:fs/promises';

type ModelsDevProvider = {
  id: string;
  env: string[];
  npm: string;
  api?: string;
  name: string;
  models: Record<string, Record<string, unknown>>;
};

async function main(item: { modelId: string }): Promise<void> {
  let apiKey: string | undefined = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    throw new Error('OPENAI_API_KEY not set');
  }

  let modelsDevResponse: Response = await fetch('https://models.dev/api.json');

  if (!modelsDevResponse.ok) {
    let responseText: string = await modelsDevResponse.text();

    throw new Error(
      `models.dev request failed (${modelsDevResponse.status}): ${responseText}`
    );
  }

  let providers: Record<string, ModelsDevProvider> =
    await modelsDevResponse.json();

  let provider: ModelsDevProvider = providers.openai;

  if (!provider) {
    throw new Error('OpenAI provider not found in models.dev');
  }

  let model: Record<string, unknown> = provider.models[item.modelId];

  if (!model) {
    throw new Error(`${item.modelId} not found in models.dev`);
  }

  let openAiResponse: Response = await fetch(
    `https://api.openai.com/v1/models/${encodeURIComponent(item.modelId)}`,
    {
      headers: {
        Authorization: `Bearer ${apiKey}`
      }
    }
  );

  if (!openAiResponse.ok) {
    let responseText: string = await openAiResponse.text();

    throw new Error(
      `OpenAI model request failed (${openAiResponse.status}): ${responseText}`
    );
  }

  let openAiModel: Record<string, unknown> = await openAiResponse.json();

  let modelInfo: Record<string, unknown> = {
    modelsDev: model,
    modelsDevProvider: {
      api: provider.api,
      name: provider.name,
      env: provider.env,
      id: provider.id,
      npm: provider.npm
    },
    openAi: openAiModel
  };

  let outputPath: string =
    'apps/backend/src/controllers/sessions/create-editor-session/tests/openai-model-info.fixture.ts';

  let modelInfoJson: string = JSON.stringify(modelInfo, null, 2);

  let content: string = `// Generated by "pnpm fetch:openai-model-fixture". Do not edit by hand.\nimport type { Model } from '@opencode-ai/models';\nimport type OpenAI from 'openai';\n\ntype OpenAiModelInfo = {\n  modelsDev: Model;\n  modelsDevProvider: {\n    api?: string;\n    name: string;\n    env: string[];\n    id: string;\n    npm: string;\n  };\n  openAi: OpenAI.Models.Model;\n};\n\nexport let OPENAI_MODEL_INFO: OpenAiModelInfo = ${modelInfoJson};\n`;

  await fs.writeFile(outputPath, content, 'utf8');

  console.log(`Wrote ${item.modelId} metadata to ${outputPath}`);
}

main({ modelId: 'gpt-5.6-sol' }).catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
