import fs from 'node:fs/promises';

type ModelsDevProvider = {
  id: string;
  env: string[];
  npm: string;
  api?: string;
  name: string;
  models: Record<string, Record<string, unknown>>;
};

async function main(item: {
  fixtures: { modelId: string; outputPath: string; exportName: string }[];
}): Promise<void> {
  let apiKey: string | undefined = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    throw new Error('OPENAI_API_KEY not set');
  }

  let modelsDevResponse: Response = await fetch('https://models.dev/api.json');

  if (!modelsDevResponse.ok) {
    let responseText: string = await modelsDevResponse.text();

    throw new Error(
      `models.dev request failed (${modelsDevResponse.status}): ${responseText}`
    );
  }

  let providers: Record<string, ModelsDevProvider> =
    await modelsDevResponse.json();

  let provider: ModelsDevProvider = providers.openai;

  if (!provider) {
    throw new Error('OpenAI provider not found in models.dev');
  }

  await Promise.all(
    item.fixtures.map(async fixture => {
      let model: Record<string, unknown> = provider.models[fixture.modelId];

      if (!model) {
        throw new Error(`${fixture.modelId} not found in models.dev`);
      }

      let openAiResponse: Response = await fetch(
        `https://api.openai.com/v1/models/${encodeURIComponent(fixture.modelId)}`,
        {
          headers: {
            Authorization: `Bearer ${apiKey}`
          }
        }
      );

      if (!openAiResponse.ok) {
        let responseText: string = await openAiResponse.text();

        throw new Error(
          `OpenAI model request failed (${openAiResponse.status}): ${responseText}`
        );
      }

      let openAiModel: Record<string, unknown> = await openAiResponse.json();

      let modelInfo: Record<string, unknown> = {
        modelsDev: model,
        modelsDevProvider: {
          api: provider.api,
          name: provider.name,
          env: provider.env,
          id: provider.id,
          npm: provider.npm
        },
        openAi: openAiModel
      };

      let modelInfoJson: string = JSON.stringify(modelInfo, null, 2);

      let content: string = `// Generated by "pnpm fetch:openai-model-fixture". Do not edit by hand.\nimport type { Model } from '@opencode-ai/models';\nimport type OpenAI from 'openai';\n\ntype OpenAiModelInfo = {\n  modelsDev: Model;\n  modelsDevProvider: {\n    api?: string;\n    name: string;\n    env: string[];\n    id: string;\n    npm: string;\n  };\n  openAi: OpenAI.Models.Model;\n};\n\nexport let ${fixture.exportName}: OpenAiModelInfo = ${modelInfoJson};\n`;

      await fs.writeFile(fixture.outputPath, content, 'utf8');

      console.log(`Wrote ${fixture.modelId} metadata to ${fixture.outputPath}`);
    })
  );
}

main({
  fixtures: [
    {
      modelId: 'gpt-5.6-sol',
      outputPath:
        'apps/backend/src/controllers/sessions/create-editor-session/tests/fixtures/openai-gpt-5-6-sol-model-info.fixture.ts',
      exportName: 'OPENAI_GPT_5_6_SOL_MODEL_INFO'
    },
    {
      modelId: 'gpt-5.6-luna',
      outputPath:
        'apps/backend/src/controllers/sessions/get-session/tests/fixtures/openai-gpt-5-6-luna-model-info.fixture.ts',
      exportName: 'OPENAI_GPT_5_6_LUNA_MODEL_INFO'
    }
  ]
}).catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
