import fs from 'node:fs/promises';

async function main(item: { modelId: string }): Promise<void> {
  let apiKey: string | undefined = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY not set');
  }

  let response: Response = await fetch(
    `https://api.anthropic.com/v1/models/${encodeURIComponent(item.modelId)}`,
    {
      headers: {
        'anthropic-version': '2023-06-01',
        'x-api-key': apiKey
      }
    }
  );

  if (!response.ok) {
    let responseText: string = await response.text();

    throw new Error(
      `Anthropic model request failed (${response.status}): ${responseText}`
    );
  }

  let modelInfo: Record<string, unknown> = await response.json();

  let outputPath: string =
    'apps/backend/src/controllers/sessions/create-editor-session/tests/anthropic-model-info.fixture.ts';

  let modelInfoJson: string = JSON.stringify(modelInfo, null, 2);

  let content: string = `// Generated by \"pnpm fetch:anthropic-model-fixture\". Do not edit by hand.\nimport type Anthropic from '@anthropic-ai/sdk';\n\nexport let ANTHROPIC_MODEL_INFO: Anthropic.Models.ModelInfo = ${modelInfoJson};\n`;

  await fs.writeFile(outputPath, content, 'utf8');

  console.log(`Wrote ${item.modelId} metadata to ${outputPath}`);
}

main({ modelId: 'claude-sonnet-4-5' }).catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
