import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

let rootDir = resolve(import.meta.dirname, '..', '..');
let skillsDir = join(rootDir, 'skills');
let outFile = join(
  rootDir,
  'libs',
  'common',
  'src',
  'constants',
  'skills-data.ts'
);

// Read skill subdirectories
let entries = readdirSync(skillsDir, { withFileTypes: true });

let skills: { name: string; content: string }[] = [];

entries.forEach(entry => {
  if (entry.isDirectory() === false) {
    return;
  }

  let skillFilePath = join(skillsDir, entry.name, 'SKILL.md');

  let isExist = true;
  try {
    statSync(skillFilePath);
  } catch {
    isExist = false;
  }

  if (isExist === false) {
    return;
  }

  let content = readFileSync(skillFilePath, 'utf-8');
  skills.push({ name: entry.name, content: content });
});

skills.sort((a, b) => a.name.localeCompare(b.name));

// Generate TypeScript file
let lines: string[] = [];

lines.push('// biome-ignore-all format: auto-generated file');
lines.push(
  '// Auto-generated by scripts/dev/skills-write.ts — do not edit manually'
);
lines.push('');
lines.push('export const SKILLS_DATA: { name: string; content: string }[] = [');

skills.forEach((skill, index) => {
  let comma = index < skills.length - 1 ? ',' : '';
  lines.push(
    '  { name: ' +
      JSON.stringify(skill.name) +
      ', content: ' +
      JSON.stringify(skill.content) +
      ' }' +
      comma
  );
});

lines.push('];');
lines.push('');

writeFileSync(outFile, lines.join('\n'), 'utf-8');

console.log('skills-write: generated ' + outFile);
skills.forEach(s => {
  console.log(s.name);
});
