import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

let rootDir = resolve(import.meta.dirname, '..', '..');
let outFile = resolve(
  rootDir,
  'libs',
  'common',
  'src',
  'constants',
  'skills-data.ts'
);

let mproveDocsHost = process.env.MPROVE_DOCS_HOST;

if (!mproveDocsHost) {
  throw new Error('MPROVE_DOCS_HOST is required to generate skills-data.ts');
}

let docsOrigin = mproveDocsHost.replace(/\/+$/, '');
let docsIndexUrl = `${docsOrigin}/content/docs/docs-for-ai.mdx`;
let skillsPathPrefix = '/content/skills/';

let indexContent = await fetchText({ url: docsIndexUrl });

let skillNames = getSkillNames({ indexContent: indexContent });

let skills = await Promise.all(
  skillNames.map(async name => {
    let url = `${docsOrigin}${skillsPathPrefix}${name}.mdx`;
    let content = await fetchText({ url: url });
    return { name: name, content: content };
  })
);

skills.sort((a, b) => a.name.localeCompare(b.name));

let lines: string[] = [];

lines.push('// biome-ignore-all format: auto-generated file');
lines.push(
  '// Auto-generated by scripts/dev/skills-write.ts — do not edit manually'
);
lines.push('');
lines.push('export const SKILLS_DATA: { name: string; content: string }[] = [');

skills.forEach((skill, index) => {
  let comma = index < skills.length - 1 ? ',' : '';
  lines.push(
    '  { name: ' +
      JSON.stringify(skill.name) +
      ', content: ' +
      JSON.stringify(skill.content) +
      ' }' +
      comma
  );
});

lines.push('];');
lines.push('');

writeFileSync(outFile, lines.join('\n'), 'utf-8');

console.log(`skills-write: fetched ${docsIndexUrl}`);
console.log(`skills-write: pulled ${skills.length} skills from docs`);
console.log(`skills-write: generated ${outFile}`);
skills.forEach(s => {
  console.log(s.name);
});

async function fetchText(item: { url: string }) {
  let { url } = item;

  let response = await fetch(url);

  if (!response.ok) {
    throw new Error(
      `Failed to fetch ${url}: ${response.status} ${response.statusText}`
    );
  }

  return response.text();
}

function getSkillNames(item: { indexContent: string }) {
  let { indexContent } = item;

  let matches = indexContent.matchAll(/href="([^"]+\.mdx)"/g);

  let names = Array.from(matches)
    .map(match => match[1])
    .filter(path => path.startsWith(skillsPathPrefix))
    .map(path => path.slice(skillsPathPrefix.length))
    .map(file => file.replace(/\.mdx$/, ''));

  return Array.from(new Set(names)).sort((a, b) => a.localeCompare(b));
}
