name: werf-converge
on:
  push:
    branches:
      - test-converge
jobs:
  converge:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Converge repo
        uses: werf/actions/converge@v1.2
        env:
          WERF_REPO_CONTAINER_REGISTRY: "github"        
          WERF_REPO: "ghcr.io/mprove-io/mprove"
          WERF_KUBE_CONTEXT: ${{ secrets.WERF_KUBE_CONTEXT }}       
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}       
          WERF_PARALLEL: false
        with:
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}